<a href="https://colab.research.google.com/github/EmilyHong77/degentrificAItion/blob/main/Census_Data_Cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# 2016 Data Cleaning

In [ ]:
import pandas as pd

# census_2016 = pd.read_csv('/content/drive/MyDrive/Ai4Good Colabs (Emily Hong)/Copy of 2016_montreal_data.csv')
census_2016 = pd.read_csv('/content/drive/MyDrive/GentrificAItion/Montreal_data_from_census/2016_montreal_data.csv')

print(census_2016)
print(len(census_2016))

<ipython-input-15-57798f823d07>:4: DtypeWarning: Columns (3,11) have mixed types. Specify dtype option on import or set low_memory=False.
  census_2016 = pd.read_csv('/content/drive/MyDrive/GentrificAItion/Montreal_data_from_census/2016_montreal_data.csv')

         CENSUS_YEAR  GEO_CODE (POR)  GEO_LEVEL  GEO_NAME  GNR  GNR_LF  \
0               2016           462.0          1  Montréal  3.3     3.7
1               2016           462.0          1  Montréal  3.3     3.7
2               2016           462.0          1  Montréal  3.3     3.7
3               2016           462.0          1  Montréal  3.3     3.7
4               2016           462.0          1  Montréal  3.3     3.7
...              ...             ...        ...       ...  ...     ...
2179585         2016       4622401.0          2    2401.0  1.8     2.6
2179586         2016       4622401.0          2    2401.0  1.8     2.6
2179587         2016       4622401.0          2    2401.0  1.8     2.6
2179588         2016       4622402.0          2    2402.0  2.5     5.2
2179589         2016       4622402.0          2    2402.0  2.5     5.2

         DATA_QUALITY_FLAG  ALT_GEO_CODE  \
0                    20000           462
1                    20000           462
2                    20000           462
3                    20000           462
4                    20000           462
...                    ...           ...
2179585                  0     462240100
2179586                  0     462240100
2179587                  0     462240100
2179588                  0     462240200
2179589                  0     462240200

                  DIM: Profile of Census Tracts (2247)  \
0           Population percentage change, 2011 to 2016
1                              Total private dwellings
2        Private dwellings occupied by usual residents
3              Population density per square kilometre
4                       Land area in square kilometres
...                                                ...
2179585                       Intraprovincial migrants
2179586                       Interprovincial migrants
2179587                              External migrants
2179588                               Population, 2016
2179589                               Population, 2011

         Member ID: Profile of Census Tracts (2247)  \
0                                                 3
1                                                 4
2                                                 5
3                                                 6
4                                                 7
...                                             ...
2179585                                        2245
2179586                                        2246
2179587                                        2247
2179588                                           1
2179589                                           2

         Notes: Profile of Census Tracts (2247)  \
0                                           NaN
1                                           3.0
2                                           4.0
3                                           NaN
4                                           NaN
...                                         ...
2179585                                     NaN
2179586                                     NaN
2179587                                     NaN
2179588                                     1.0
2179589                                     2.0

        Dim: Sex (3): Member ID: [1]: Total - Sex  \
0                                             4.2
1                                       1823281.0
2                                       1727310.0
3                                           890.2
4                                         4604.26
...                                           ...
2179585                                       380
2179586                                        35
2179587                                         0
2179588                                      3484
2179589                                      2685

        Dim: Sex (3): Member ID: [2]: Male  \
0                                      ...
1                                      ...
2                                      ...
3                                      ...
4                                      ...
...                                    ...
2179585                                175
2179586                                 20
2179587                                  0
2179588                                ...
2179589                                ...

        Dim: Sex (3): Member ID: [3]: Female
0                                        ...
1                                        ...
2                                        ...
3                                        ...
4                                        ...
...                                      ...
2179585                                  205
2179586                                   20
2179587                                    0
2179588                                  ...
2179589                                  ...

[2179590 rows x 14 columns]
2179590

In [ ]:
# Loop through questions and save the ones we want to keep

conditions_2016 = [
    'Population, 2016',
    'Population percentage change, 2011 to 2016',
    'Total private dwellings',
    'Private dwellings occupied by usual residents',
    'Population density per square kilometre',
    'Total - Age groups and average age of the population - 100% data',
    '0 to 14 years',
    '15 to 19 years',
    '20 to 24 years',
    '25 to 29 years',
    '30 to 34 years',
    '35 to 39 years',
    '40 to 44 years',
    '45 to 49 years',
    '50 to 54 years',
    '55 to 59 years',
    '60 to 64 years',
    '65 years and over',
    'Median age of the population',
    'Average age of the population',
    'Total - Occupied private dwellings by structural type of dwelling - 100% data',
    'Single-detached house',
    'Apartment in a building that has five or more storeys',
    'Semi-detached house',
    'Row house',
    'Apartment or flat in a duplex',
    'Apartment in a building that has fewer than five storeys',
    'Other single-attached house',
    'Movable dwelling',
    'Average household size',
    'Total - Marital status for the population aged 15 years and over - 100% data',
    'Married or living common law',
    'Not married and not living common law',
    'Median total income of households in 2015 ($)',
    'Median after-tax income of households in 2015 ($)',
    'Prevalence of low income based on the Low-income measure, after tax (LIM-AT) (%)',
    'Prevalence of low income based on the Low-income cut-offs, after tax (LICO-AT) (%)',
    'Total - Citizenship for the population in private households - 25% sample data',
    'Canadian citizens',
    'Not Canadian citizens',
    'Total - Immigrant status and period of immigration for the population in private households - 25% sample data',
    'Non-immigrants',
    'Immigrants',
    'Non-permanent residents',
    'Total - Visible minority for the population in private households - 25% sample data',
    'Total visible minority population',
    'Not a visible minority',
    'Total - Private households by tenure - 25% sample data',
    'Owner',
    'Renter',
    'Band housing',
    'Total - Occupied private dwellings by condominium status - 25% sample data',
    'Condominium',
    'Not condominium',
    'Total - Private households by housing suitability - 25% sample data',
    'Suitable',
    'Not suitable',
    'Total - Occupied private dwellings by dwelling condition - 25% sample data',
    'Only regular maintenance or minor repairs needed',
    'Major repairs needed',
    'Average number of rooms per dwelling',
    '% of tenant households in subsidized housing',
    'Median monthly shelter costs for owned dwellings ($)',
    'Average monthly shelter costs for owned dwellings ($)',
    'Median value of dwellings ($)',
    'Average value of dwellings ($)',
    'Median monthly shelter costs for rented dwellings ($)',
    'Median monthly shelter costs for rented dwellings ($)',
    'Total - Highest certificate, diploma or degree for the population aged 15 years and over in private households - 25% sample data',
    'No certificate, diploma or degree',
    'Secondary (high) school diploma or equivalency certificate',
    'Postsecondary certificate, diploma or degree',
    'Apprenticeship or trades certificate or diploma',
    'College, CEGEP or other non-university certificate or diploma',
    'University certificate or diploma below bachelor level',
    'University certificate, diploma or degree at bachelor level or above',
    'Total - Location of study compared with province or territory of residence with countries outside Canada for the population aged 15 years and over in private households - 25% sample data',
    'Location of study inside Canada',
    'Same as province or territory of residence',
    'Different than province or territory of residence',
    'Location of study outside Canada',
    'Total - Population aged 15 years and over by Labour force status - 25% sample data',
    'In the labour force',
    'Not in the labour force',
    'Total - Main mode of commuting for the employed labour force aged 15 years and over in private households with a usual place of work or no fixed workplace address - 25% sample data',
    'Car, truck, van - as a driver',
    'Car, truck, van - as a passenger',
    'Public transit',
    'Walked',
    'Bicycle',
    'Other method',
    'Total - Commuting duration for the employed labour force aged 15 years and over in private households with a usual place of work or no fixed workplace address - 25% sample data',
    'Less than 15 minutes',
    '15 to 29 minutes',
    '30 to 44 minutes',
    '45 to 59 minutes',
    '60 minutes and over',
    'Total - Mobility status 1 year ago - 25% sample data',
    'Non-movers',
    'Movers'
]

# Filtering the DataFrame to get rows that match the conditions
new_df = census_2016.loc[census_2016['DIM: Profile of Census Tracts (2247)'].isin(conditions_2016)]

# Find values in conditions that are not in 'CHARACTERISTIC_NAME' in new_df
missing_conditions = [condition for condition in conditions_2016 if condition not in new_df['DIM: Profile of Census Tracts (2247)'].values]

# Print the missing values
print("\nConditions not found in 'DIM: Profile of Census Tracts (2247)':")
if len(missing_conditions) == 0:
    print("No missing values found.")
else:
  for condition in missing_conditions:
    print(condition)

print(new_df)

NameError: name 'census_2016' is not defined

In [ ]:
# drop gender columns

new_df = new_df.drop('Dim: Sex (3): Member ID: [2]: Male', axis=1)
new_df = new_df.drop('Dim: Sex (3): Member ID: [3]: Female', axis=1)
new_df = new_df.drop('Notes: Profile of Census Tracts (2247)', axis=1)
new_df = new_df.drop('Member ID: Profile of Census Tracts (2247)', axis=1)
new_df = new_df.drop('GEO_LEVEL', axis=1)
# new_df = new_df.drop('GEO_CODE (POR)', axis=1)
new_df = new_df.drop('GNR', axis=1)
new_df = new_df.drop('GNR_LF', axis=1)
new_df = new_df.drop('DATA_QUALITY_FLAG', axis=1)
new_df = new_df.drop('ALT_GEO_CODE', axis=1)


print(new_df.head())

   CENSUS_YEAR  GEO_CODE (POR)  GEO_NAME  \
0         2016           462.0  Montréal
1         2016           462.0  Montréal
2         2016           462.0  Montréal
3         2016           462.0  Montréal
5         2016           462.0  Montréal

                DIM: Profile of Census Tracts (2247)  \
0         Population percentage change, 2011 to 2016
1                            Total private dwellings
2      Private dwellings occupied by usual residents
3            Population density per square kilometre
5  Total - Age groups and average age of the popu...

  Dim: Sex (3): Member ID: [1]: Total - Sex
0                                       4.2
1                                 1823281.0
2                                 1727310.0
3                                     890.2
5                                 4098930.0

In [ ]:
print(len(new_df))

115430

In [ ]:
# loop over rows, make a dict
# items = {'region':{}}
items = {}
for i in range(len(new_df)):
  # if i > 10:
  #   break
  # print(new_df.iloc[i]['GEO_NAME'])
  outer_key = new_df.iloc[i]['GEO_NAME']
  if outer_key in items:
    inner_key = new_df.iloc[i]['DIM: Profile of Census Tracts (2247)'] + ' 2016'
    items[outer_key][inner_key] = new_df.iloc[i]['Dim: Sex (3): Member ID: [1]: Total - Sex']
  else:
    items[outer_key] = {'ctuid': new_df.iloc[i]['GEO_CODE (POR)']}
    inner_key = new_df.iloc[i]['DIM: Profile of Census Tracts (2247)'] + ' 2016'
    items[outer_key][inner_key] = new_df.iloc[i]['Dim: Sex (3): Member ID: [1]: Total - Sex']
print(items.keys())

dict_keys(['Montréal', '0001.00', '0002.00', '0003.00', '0004.00', '0005.00', '0006.00', '0007.00', '0008.00', '0009.00', '0010.00', '0011.00', '0012.01', '0012.02', '0013.00', '0014.01', '14.01', '14.02', '15.0', '16.0', '17.0', '18.0', '19.0', '21.0', '22.0', '23.0', '24.0', '25.0', '26.0', '27.0', '28.0', 28.0, 29.0, 30.0, 31.0, 32.0, 33.0, 34.0, 35.0, 36.0, 37.0, 38.0, 39.0, 40.0, 41.0, 42.0, 43.0, 44.0, 45.0, 46.0, 47.0, 48.0, 49.0, 50.0, 51.0, 52.0, 53.0, 54.0, 55.01, 55.02, 56.0, 57.0, 58.0, 59.0, 60.0, 61.0, 62.0, 63.0, 64.0, 65.01, 65.02, 66.01, 66.02, 67.0, 68.0, 69.01, 69.02, 70.01, 70.02, 71.0, 72.0, 73.0, 74.0, 75.0, 76.0, 77.0, 78.0, 79.0, 80.0, 81.0, 82.0, 83.0, 84.0, 85.0, 86.0, 87.0, 88.0, 89.0, 90.0, 91.0, 92.0, 93.0, 94.01, 94.02, 95.0, 96.0, 97.01, 97.02, 98.0, 99.0, 100.01, 100.02, 101.01, 101.02, 102.0, 103.0, 104.0, 105.0, 106.0, 107.0, 108.0, 109.0, 110.0, 111.0, 112.01, 112.02, 113.0, 114.0, 115.01, 115.02, 116.0, 117.0, 118.0, 119.0, 120.01, 120.02, 121.0, 122.0, 123.0, 124.0, 125.0, 126.0, 127.01, 127.02, 128.0, 129.01, 129.02, 130.0, 131.0, 132.0, 133.0, 134.0, 135.0, 136.0, 137.0, 138.0, 139.0, 140.0, 141.0, 142.0, 143.0, 144.0, 145.0, 146.0, 147.0, 148.0, 149.0, 150.0, 151.0, 152.0, 153.0, 154.0, 155.0, 156.0, 157.0, 158.0, 159.0, 160.0, 161.0, 162.0, 163.0, 164.0, 165.0, 166.0, 167.0, 168.0, 169.0, 170.0, 171.0, 172.0, 173.0, 174.0, 175.0, 176.0, 177.0, 178.0, 179.0, 180.0, 181.0, 182.0, 183.0, 184.0, 185.0, 186.0, 187.01, 187.03, 187.04, 188.01, 188.02, 189.0, 190.01, 190.02, 191.0, 192.0, 193.0, 194.0, 195.01, 195.02, 195.03, 196.0, 197.0, 198.0, 199.0, 200.0, 201.0, 202.0, 203.0, 204.0, 205.0, 206.0, 207.0, 208.0, 209.0, 210.0, 211.0, 212.0, 213.0, 214.0, 215.0, 216.0, 217.0, 218.0, 219.0, 220.0, 221.0, 222.0, 223.01, 223.02, 224.0, 225.0, 226.0, 227.0, 228.0, 229.0, 230.0, 231.0, 232.0, 233.0, 234.0, 235.0, 236.0, 237.0, 238.0, 239.0, 240.0, 241.0, 242.0, 243.0, 244.0, 245.0, 247.0, 249.0, 250.0, 251.01, 251.02, 252.0, 253.0, 254.0, 256.0, 257.0, 258.0, 259.0, 260.0, 261.0, 262.0, 263.0, 264.01, 264.02, 265.0, 266.0, 267.0, 268.01, 268.02, 268.03, 269.0, 270.0, 271.0, 272.0, 273.0, 274.0, 275.0, 276.0, 277.0, 278.0, 279.0, 280.0, 281.0, 282.0, 283.01, 283.02, 284.0, 285.0, 286.0, 287.01, 287.02, 288.0, 290.01, 290.02, 290.03, 290.04, 290.05, 290.06, 290.07, 290.08, 290.09, 291.01, 291.03, 291.04, 300.0, 301.0, 302.0, 303.0, 304.0, 305.0, 306.0, 307.0, 308.0, 309.0, 310.0, 311.0, 312.0, 313.0, 314.0, 315.0, 316.0, 317.02, 317.03, 317.04, 320.0, 321.0, 322.02, 322.03, 322.04, 323.0, 324.01, 324.02, 325.01, 325.02, 325.03, 325.05, 325.06, 326.01, 326.02, 326.03, 327.0, 328.0, 329.0, 330.0, 340.0, 350.0, 351.0, 352.0, 353.0, 354.0, 355.0, 356.0, 360.0, 361.0, 362.0, 363.0, 364.0, 365.0, 366.0, 367.0, 370.0, 380.0, 381.0, 382.01, 382.02, 383.01, 383.02, 385.0, 390.0, 391.0, 392.0, 393.0, 394.0, 395.01, 395.02, 395.03, 396.0, 397.0, 400.0, 401.0, 402.0, 403.0, 404.0, 410.01, 410.02, 410.03, 412.0, 413.01, 413.02, 415.03, 415.04, 415.05, 415.06, 416.01, 416.02, 417.01, 417.02, 418.0, 419.0, 420.0, 421.01, 421.02, 430.0, 431.0, 432.0, 433.0, 440.0, 450.0, 451.0, 452.0, 453.01, 453.02, 460.0, 461.0, 462.01, 462.02, 470.01, 470.03, 470.04, 470.05, 480.0, 490.0, 491.0, 500.0, 511.01, 511.02, 512.02, 512.03, 512.04, 513.01, 513.02, 514.01, 514.02, 515.01, 515.02, 515.03, 515.04, 520.02, 520.03, 520.04, 521.01, 521.04, 521.05, 521.06, 521.07, 522.01, 522.02, 523.0, 530.0, 540.0, 550.02, 550.03, 550.04, 570.0, 580.01, 580.02, 580.03, 581.01, 581.02, 582.01, 582.02, 583.0, 584.0, 585.01, 585.02, 590.01, 590.02, 591.01, 591.02, 592.0, 593.01, 593.02, 594.01, 594.02, 600.01, 600.02, 600.03, 601.01, 601.02, 602.01, 602.02, 603.01, 603.02, 603.03, 604.01, 604.02, 604.03, 604.04, 604.05, 605.01, 605.02, 605.03, 605.04, 605.05, 610.01, 610.02, 610.03, 610.04, 610.05, 610.06, 610.07, 611.01, 611.02, 612.0, 613.0, 614.0, 615.0, 616.0, 617.01, 617.02, 618.0, 619.0, 625.01, 625.02, 626.0, 627.0, 628.01, 628.02, 629.0, 630.01, 630.02, 631.0, 632.01, 632.02, 632.03, 632.04, 633.0, 634.0, 635.0, 636.0, 637.01, 637.02, 638.01, 638.02, 638.03, 638.04, 639.0, 640.0, 641.01, 641.02, 642.0, 643.01, 643.02, 643.03, 644.0, 645.0, 646.01, 646.02, 646.03, 647.01, 647.02, 648.0, 649.01, 649.02, 650.01, 650.02, 650.04, 650.05, 651.01, 651.02, 652.01, 652.04, 652.06, 652.07, 652.08, 652.09, 653.0, 654.0, 655.01, 655.02, 656.01, 656.03, 656.04, 657.01, 657.02, 657.03, 658.01, 658.02, 658.03, 659.04, 659.05, 659.06, 659.08, 659.09, 659.1, 659.11, 660.01, 660.02, 660.03, 661.01, 661.03, 661.04, 662.0, 675.0, 676.01, 676.02, 676.03, 676.04, 677.01, 677.02, 677.05, 677.06, 677.07, 677.08, 677.09, 677.1, 681.0, 682.02, 682.03, 682.04, 682.05, 682.06, 683.0, 684.03, 684.05, 684.08, 684.09, 684.1, 684.11, 685.02, 685.03, 685.04, 685.05, 685.07, 685.08, 686.01, 686.02, 686.03, 687.01, 687.03, 687.04, 687.06, 687.07, 687.09, 687.1, 688.02, 688.03, 688.04, 689.01, 689.02, 689.03, 689.04, 690.0, 691.0, 692.0, 693.0, 694.0, 700.01, 700.03, 700.04, 701.01, 701.02, 702.01, 702.02, 703.02, 703.03, 703.04, 704.01, 704.04, 704.05, 704.06, 704.08, 704.09, 705.01, 705.02, 706.0, 707.0, 708.01, 708.02, 709.01, 709.02, 710.03, 710.05, 710.06, 710.07, 710.08, 710.09, 710.1, 710.11, 725.03, 725.04, 725.06, 725.07, 725.09, 725.1, 726.01, 726.03, 726.04, 727.01, 727.02, 728.01, 728.02, 728.03, 729.0, 730.01, 730.02, 731.0, 732.01, 732.03, 732.04, 733.01, 733.02, 734.03, 734.04, 734.05, 734.06, 734.07, 735.01, 735.02, 740.01, 740.03, 740.04, 750.01, 750.02, 750.04, 750.06, 750.07, 751.01, 751.02, 755.01, 755.02, 756.02, 756.03, 756.04, 756.05, 757.0, 758.03, 758.04, 758.05, 758.06, 760.0, 775.0, 776.0, 777.01, 777.02, 780.0, 781.0, 782.0, 783.0, 784.0, 785.0, 786.0, 787.0, 788.0, 789.0, 790.0, 791.0, 792.0, 800.01, 800.02, 801.0, 802.0, 804.01, 804.02, 805.0, 806.01, 806.02, 807.01, 807.02, 825.02, 825.03, 825.04, 825.05, 825.06, 825.07, 825.08, 826.02, 826.05, 826.06, 826.07, 826.08, 826.09, 826.1, 826.11, 826.13, 826.14, 827.02, 827.03, 827.04, 828.03, 828.04, 828.05, 828.06, 829.0, 830.01, 830.03, 830.04, 831.03, 831.04, 831.05, 831.07, 831.08, 831.09, 832.0, 833.0, 834.0, 850.01, 850.03, 850.04, 850.05, 851.0, 852.01, 852.02, 853.02, 853.03, 853.04, 854.01, 854.02, 855.01, 855.03, 855.04, 856.0, 857.01, 857.02, 857.06, 857.07, 857.08, 857.09, 857.1, 857.11, 857.12, 858.01, 858.02, 858.04, 858.05, 859.0, 860.01, 860.02, 861.0, 862.0, 863.01, 863.02, 864.0, 865.0, 866.0, 867.0, 868.01, 868.02, 869.0, 870.01, 870.02, 871.01, 871.02, 872.0, 873.01, 873.02, 874.0, 875.0, 876.01, 876.04, 876.05, 876.06, 876.07, 877.01, 877.02, 878.0, 879.01, 879.02, 880.0, 881.01, 881.02, 882.0, 883.0, 884.01, 884.02, 885.0, 886.01, 886.02, 886.03, 887.03, 887.04, 887.05, 887.06, 887.07, 888.01, 888.02, 888.03, 889.01, 889.02, 889.03, 900.0, 901.01, 901.02, 901.03, 902.0, 903.01, 903.04, 903.05, 903.08, 903.09, 903.1, 903.11, 903.12, 903.13, 903.14, 904.02, 904.03, 904.04, 904.05, 904.06, 926.01, 926.02, 929.01, 929.02, 930.02, 930.03, 930.04, 1000.0, 1001.0, 1002.0, 1003.0, 1004.0, 1005.0, 1006.0, 2001.0, 2002.0, 2003.0, 2004.0, 2005.0, 2006.0, 2007.0, 2008.0, 2009.0, 2010.0, 2011.0, 2012.0, 2013.0, 2014.0, 2015.0, 2100.0, 2101.0, 2102.0, 2103.0, 2200.0, 2201.0, 2202.0, 2203.0, 2204.0, 2205.0, 2206.0, 2207.0, 2300.0, 2301.0, 2302.0, 2303.0, 2304.0, 2400.0, 2401.0, 2402.0])

In [ ]:
# Check if a specific condition is an inner key of a specific GEO location

specific_outer_key = "Montréal"
specific_inner_key = "Population, 2016 2016"

if specific_outer_key in items:
    if specific_inner_key in items[specific_outer_key]:
        print(f'Item with outer key "{specific_outer_key}" and inner key "{specific_inner_key}" is in the dictionary.')
    else:
        print(f'Inner key "{specific_inner_key}" is not in the dictionary for outer key "{specific_outer_key}".')
else:
    print(f'Outer key "{specific_outer_key}" is not in the dictionary.')

Inner key "Population, 2016 2016" is not in the dictionary for outer key "Montréal".

In [ ]:
# Convert the dictionary of dictionaries into a DataFrame
df = pd.DataFrame.from_dict(items, orient='index')

# Write the DataFrame to a CSV file
# df.to_csv('/content/drive/MyDrive/Ai4Good Colabs (Emily Hong)/2016_output.csv')
df.to_csv('/content/drive/MyDrive/GentrificAItion/Montreal_data_from_census/2016_emilie_v1.csv')

print(df)
print(df.columns)

              ctuid Population percentage change, 2011 to 2016 2016  \
Montréal      462.0                                             4.2
0001.00   4620001.0                                             1.2
0002.00   4620002.0                                            15.7
0003.00   4620003.0                                             2.2
0004.00   4620004.0                                            -2.6
...             ...                                             ...
2303.0    4622303.0                                             ...
2304.0    4622304.0                                            -1.1
2400.0    4622400.0                                            -2.5
2401.0    4622401.0                                            11.4
2402.0    4622402.0                                             NaN

         Total private dwellings 2016  \
Montréal                    1823281.0
0001.00                        1452.0
0002.00                        1902.0
0003.00                        3103.0
0004.00                        1704.0
...                               ...
2303.0                              0
2304.0                            445
2400.0                           1180
2401.0                           1400
2402.0                            NaN

         Private dwellings occupied by usual residents 2016  \
Montréal                                          1727310.0
0001.00                                              1328.0
0002.00                                              1762.0
0003.00                                              2937.0
0004.00                                              1603.0
...                                                     ...
2303.0                                                    0
2304.0                                                  443
2400.0                                                 1132
2401.0                                                 1381
2402.0                                                  NaN

         Population density per square kilometre 2016  \
Montréal                                        890.2
0001.00                                        5710.0
0002.00                                        9029.3
0003.00                                        8612.2
0004.00                                        7087.7
...                                               ...
2303.0                                            0.0
2304.0                                         1557.5
2400.0                                           58.8
2401.0                                          837.5
2402.0                                            NaN

         Total - Age groups and average age of the population - 100% data 2016  \
Montréal                                          4098930.0
0001.00                                              2635.0
0002.00                                              3515.0
0003.00                                              6375.0
0004.00                                              3175.0
...                                                     ...
2303.0                                                    x
2304.0                                                 1095
2400.0                                                 2730
2401.0                                                 3690
2402.0                                                  NaN

         0 to 14 years 2016 15 to 19 years 2016 20 to 24 years 2016  \
Montréal               16.9            225350.0            271640.0
0001.00                12.5               120.0               160.0
0002.00                15.6               145.0               230.0
0003.00                15.5               305.0               350.0
0004.00                12.1               145.0               205.0
...                     ...                 ...                 ...
2303.0                    x                   x                   x
2304.0                 15.1                  70                  60
2400.0                 15.9                 135                 150
2401.0                 21.4                 215                 175
2402.0                  NaN                 NaN                 NaN

         25 to 29 years 2016  ...  \
Montréal            270735.0  ...
0001.00                200.0  ...
0002.00                255.0  ...
0003.00                430.0  ...
0004.00                220.0  ...
...                      ...  ...
2303.0                     x  ...
2304.0                    40  ...
2400.0                   145  ...
2401.0                   230  ...
2402.0                   NaN  ...

         Total - Commuting duration for the employed labour force aged 15 years and over in private households with a usual place of work or no fixed workplace address - 25% sample data 2016  \
Montréal                                          1883815.0
0001.00                                              1375.0
0002.00                                              1650.0
0003.00                                              2810.0
0004.00                                              1585.0
...                                                     ...
2303.0                                                    x
2304.0                                                  570
2400.0                                                 1205
2401.0                                                 1880
2402.0                                                  NaN

         Less than 15 minutes 2016 15 to 29 minutes 2016  \
Montréal                  341880.0              601245.0
0001.00                      220.0                 415.0
0002.00                      255.0                 525.0
0003.00                      385.0                 885.0
0004.00                      270.0                 455.0
...                            ...                   ...
2303.0                           x                     x
2304.0                         260                   110
2400.0                         385                   355
2401.0                         610                   575
2402.0                         NaN                   NaN

         30 to 44 minutes 2016 45 to 59 minutes 2016 60 minutes and over 2016  \
Montréal              489215.0              235365.0                 216115.0
0001.00                  350.0                 200.0                    195.0
0002.00                  375.0                 280.0                    220.0
0003.00                  780.0                 410.0                    360.0
0004.00                  425.0                 275.0                    155.0
...                        ...                   ...                      ...
2303.0                       x                     x                        x
2304.0                      95                    45                       60
2400.0                     235                   130                       95
2401.0                     325                   215                      160
2402.0                     NaN                   NaN                      NaN

         Total - Mobility status 1 year ago - 25% sample data 2016  \
Montréal                                          3965040.0
0001.00                                              2670.0
0002.00                                              3305.0
0003.00                                              6195.0
0004.00                                              3110.0
...                                                     ...
2303.0                                                    x
2304.0                                                 1085
2400.0                                                 2700
2401.0                                                 3640
2402.0                                                  NaN

         Non-movers 2016 Movers 2016 Population, 2016 2016
Montréal       2325075.0   1453460.0                   NaN
0001.00           1470.0      1075.0                2638.0
0002.00           1345.0      1780.0                3516.0
0003.00           3485.0      2440.0                6373.0
0004.00           1760.0      1230.0                3176.0
...                  ...         ...                   ...
2303.0                 x           x                     0
2304.0               790         260                  1094
2400.0              1890         680                  2729
2401.0              2355        1080                  3691
2402.0               NaN         NaN                  3484

[973 rows x 100 columns]
Index(['ctuid', 'Population percentage change, 2011 to 2016 2016',
       'Total private dwellings 2016',
       'Private dwellings occupied by usual residents 2016',
       'Population density per square kilometre 2016',
       'Total - Age groups and average age of the population - 100% data 2016',
       '0 to 14 years 2016', '15 to 19 years 2016', '20 to 24 years 2016',
       '25 to 29 years 2016', '30 to 34 years 2016', '35 to 39 years 2016',
       '40 to 44 years 2016', '45 to 49 years 2016', '50 to 54 years 2016',
       '55 to 59 years 2016', '60 to 64 years 2016', '65 years and over 2016',
       'Average age of the population 2016',
       'Median age of the population 2016',
       'Total - Occupied private dwellings by structural type of dwelling - 100% data 2016',
       'Single-detached house 2016',
       'Apartment in a building that has five or more storeys 2016',
       'Semi-detached house 2016', 'Row house 2016',
       'Apartment or flat in a duplex 2016',
       'Apartment in a building that has fewer than five storeys 2016',
       'Other single-attached house 2016', 'Movable dwelling 2016',
       'Average household size 2016',
       'Total - Marital status for the population aged 15 years and over - 100% data 2016',
       'Married or living common law 2016',
       'Not married and not living common law 2016',
       'Median total income of households in 2015 ($) 2016',
       'Median after-tax income of households in 2015 ($) 2016',
       'Prevalence of low income based on the Low-income measure, after tax (LIM-AT) (%) 2016',
       'Prevalence of low income based on the Low-income cut-offs, after tax (LICO-AT) (%) 2016',
       'Total - Citizenship for the population in private households - 25% sample data 2016',
       'Canadian citizens 2016', 'Not Canadian citizens 2016',
       'Total - Immigrant status and period of immigration for the population in private households - 25% sample data 2016',
       'Non-immigrants 2016', 'Immigrants 2016',
       'Non-permanent residents 2016',
       'Total - Visible minority for the population in private households - 25% sample data 2016',
       'Total visible minority population 2016', 'Not a visible minority 2016',
       'Total - Private households by tenure - 25% sample data 2016',
       'Owner 2016', 'Renter 2016', 'Band housing 2016',
       'Total - Occupied private dwellings by condominium status - 25% sample data 2016',
       'Condominium 2016', 'Not condominium 2016',
       'Average number of rooms per dwelling 2016',
       'Total - Private households by housing suitability - 25% sample data 2016',
       'Suitable 2016', 'Not suitable 2016',
       'Total - Occupied private dwellings by dwelling condition - 25% sample data 2016',
       'Only regular maintenance or minor repairs needed 2016',
       'Major repairs needed 2016',
       'Median monthly shelter costs for owned dwellings ($) 2016',
       'Average monthly shelter costs for owned dwellings ($) 2016',
       'Median value of dwellings ($) 2016',
       'Average value of dwellings ($) 2016',
       '% of tenant households in subsidized housing 2016',
       'Median monthly shelter costs for rented dwellings ($) 2016',
       'Total - Highest certificate, diploma or degree for the population aged 15 years and over in private households - 25% sample data 2016',
       'No certificate, diploma or degree 2016',
       'Secondary (high) school diploma or equivalency certificate 2016',
       'Postsecondary certificate, diploma or degree 2016',
       'Apprenticeship or trades certificate or diploma 2016',
       'College, CEGEP or other non-university certificate or diploma 2016',
       'University certificate or diploma below bachelor level 2016',
       'University certificate, diploma or degree at bachelor level or above 2016',
       'Total - Location of study compared with province or territory of residence with countries outside Canada for the population aged 15 years and over in private households - 25% sample data 2016',
       'Location of study inside Canada 2016',
       'Same as province or territory of residence 2016',
       'Different than province or territory of residence 2016',
       'Location of study outside Canada 2016',
       'Total - Population aged 15 years and over by Labour force status - 25% sample data 2016',
       'In the labour force 2016', 'Not in the labour force 2016',
       'Total - Main mode of commuting for the employed labour force aged 15 years and over in private households with a usual place of work or no fixed workplace address - 25% sample data 2016',
       'Car, truck, van - as a driver 2016',
       'Car, truck, van - as a passenger 2016', 'Public transit 2016',
       'Walked 2016', 'Bicycle 2016', 'Other method 2016',
       'Total - Commuting duration for the employed labour force aged 15 years and over in private households with a usual place of work or no fixed workplace address - 25% sample data 2016',
       'Less than 15 minutes 2016', '15 to 29 minutes 2016',
       '30 to 44 minutes 2016', '45 to 59 minutes 2016',
       '60 minutes and over 2016',
       'Total - Mobility status 1 year ago - 25% sample data 2016',
       'Non-movers 2016', 'Movers 2016', 'Population, 2016 2016'],
      dtype='object')

In [ ]:
# check if a specific column exists in the cleaned df

if "Movers 2016" in df.columns:
    print('"Population, 2016" is in the column.')
else:
    print('"Population, 2016" is not in the column.')

"Population, 2016" is in the column.

# 2021 Data Cleaning

In [ ]:
import pandas as pd

# census_2021 = pd.read_csv('/content/drive/MyDrive/Ai4Good Colabs (Emily Hong)/Copy of 2021_montreal_data.csv')
census_2021 = pd.read_csv('/content/drive/MyDrive/GentrificAItion/Montreal_data_from_census/2021_montreal_data.csv')

print(census_2021)
print(len(census_2021))

<ipython-input-2-e3ffa475c9ba>:4: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  census_2021 = pd.read_csv('/content/drive/MyDrive/GentrificAItion/Montreal_data_from_census/2021_montreal_data.csv')

         CENSUS_YEAR                DGUID  ALT_GEO_CODE  \
0               2021         2021S0503462         462.0
1               2021         2021S0503462         462.0
2               2021         2021S0503462         462.0
3               2021         2021S0503462         462.0
4               2021         2021S0503462         462.0
...              ...                  ...           ...
2641519         2021  2021S05074622401.00     4622401.0
2641520         2021  2021S05074622401.00     4622401.0
2641521         2021  2021S05074622401.00     4622401.0
2641522         2021  2021S05074622402.00     4622402.0
2641523         2021  2021S05074622402.00     4622402.0

                        GEO_LEVEL   GEO_NAME  TNR_SF  TNR_LF  \
0        Census metropolitan area   Montréal     2.6     3.4
1        Census metropolitan area   Montréal     2.6     3.4
2        Census metropolitan area   Montréal     2.6     3.4
3        Census metropolitan area   Montréal     2.6     3.4
4        Census metropolitan area   Montréal     2.6     3.4
...                           ...        ...     ...     ...
2641519              Census tract  4622401.0     1.2     1.8
2641520              Census tract  4622401.0     1.2     1.8
2641521              Census tract  4622401.0     1.2     1.8
2641522              Census tract  4622402.0     0.9     1.5
2641523              Census tract  4622402.0     0.9     1.5

         DATA_QUALITY_FLAG  CHARACTERISTIC_ID  \
0                    20000                  3
1                    20000                  4
2                    20000                  5
3                    20000                  6
4                    20000                  7
...                    ...                ...
2641519                  0               2629
2641520                  0               2630
2641521                  0               2631
2641522                  0                  1
2641523                  0                  2

                                       CHARACTERISTIC_NAME  ...  \
0               Population percentage change, 2016 to 2021  ...
1                                  Total private dwellings  ...
2            Private dwellings occupied by usual residents  ...
3                  Population density per square kilometre  ...
4                           Land area in square kilometres  ...
...                                                    ...  ...
2641519      Eligible children who have been instructed...  ...
2641520      Eligible children who have not been instru...  ...
2641521    Children not eligible for instruction in the...  ...
2641522                                   Population, 2021  ...
2641523                                   Population, 2016  ...

         C2_COUNT_MEN+  SYMBOL.1 C3_COUNT_WOMEN+  SYMBOL.2 C10_RATE_TOTAL  \
0                  NaN       ...             NaN       ...            4.6
1                  NaN       ...             NaN       ...            NaN
2                  NaN       ...             NaN       ...            NaN
3                  NaN       ...             NaN       ...          919.0
4                  NaN       ...             NaN       ...            NaN
...                ...       ...             ...       ...            ...
2641519           25.0       NaN            20.0       NaN            6.8
2641520            5.0       NaN            10.0       NaN            2.0
2641521          330.0       NaN           340.0       NaN           91.8
2641522            NaN       ...             NaN       ...            NaN
2641523            NaN       ...             NaN       ...            NaN

         SYMBOL.3 C11_RATE_MEN+  SYMBOL.4 C12_RATE_WOMEN+  SYMBOL.5
0             NaN           NaN       ...             NaN       ...
1             ...           NaN       ...             NaN       ...
2             ...           NaN       ...             NaN       ...
3             NaN           NaN       ...             NaN       ...
4             ...           NaN       ...             NaN       ...
...           ...           ...       ...             ...       ...
2641519       NaN           6.8       NaN             5.4       NaN
2641520       NaN           1.4       NaN             2.7       NaN
2641521       NaN          90.4       NaN            91.9       NaN
2641522       ...           NaN       ...             NaN       ...
2641523       ...           NaN       ...             NaN       ...

[2641524 rows x 23 columns]
2641524

In [ ]:
# Loop through questions and save the ones we want to keep

conditions_2021 = [
    'Population, 2021',
    'Population percentage change, 2016 to 2021',
    'Total private dwellings',
    'Private dwellings occupied by usual residents',
    'Population density per square kilometre',
    'Total - Age groups of the population - 100% data',
    '0 to 14 years',
    '15 to 19 years',
    '20 to 24 years',
    '25 to 29 years',
    '30 to 34 years',
    '35 to 39 years',
    '40 to 44 years',
    '45 to 49 years',
    '50 to 54 years',
    '55 to 59 years',
    '60 to 64 years',
    '65 years and over',
    'Median age of the population',
    'Average age of the population',
    'Total - Occupied private dwellings by structural type of dwelling - 100% data',
    'Single-detached house',
    'Apartment in a building that has five or more storeys',
    'Semi-detached house',
    'Row house',
    'Apartment or flat in a duplex',
    'Apartment in a building that has fewer than five storeys',
    'Other single-attached house',
    'Movable dwelling',
    'Average household size',
    'Total - Marital status for the total population aged 15 years and over - 100% data',
    'Married or living common-law',
    'Not married and not living common-law',
    'Median total income of household in 2020 ($)',
    'Median after-tax income of household in 2020 ($)',
    'Prevalence of low income based on the Low-income measure, after tax (LIM-AT) (%)',
    'Prevalence of low income based on the Low-income cut-offs, after tax (LICO-AT) (%)',
    'Total - Citizenship for the population in private households - 25% sample data',
    'Canadian citizens',
    'Not Canadian citizens',
    'Total - Immigrant status and period of immigration for the population in private households - 25% sample data',
    'Non-immigrants',
    'Immigrants',
    'Non-permanent residents',
    'Total - Visible minority for the population in private households - 25% sample data',
    'Total visible minority population',
    'Not a visible minority',
    'Total - Private households by tenure - 25% sample data',
    'Owner',
    'Renter',
    'Dwelling provided by the local government, First Nation or Indian band', # band housing in 2016
    'Total - Occupied private dwellings by condominium status - 25% sample data',
    'Condominium',
    'Not condominium',
    'Total - Private households by housing suitability - 25% sample data',
    'Suitable',
    'Not suitable',
    'Total - Occupied private dwellings by dwelling condition - 25% sample data',
    'Only regular maintenance and minor repairs needed',
    'Major repairs needed',
    'Average number of rooms per dwelling',
    '% of tenant households in subsidized housing',
    'Median monthly shelter costs for owned dwellings ($)',
    'Average monthly shelter costs for owned dwellings ($)',
    'Median value of dwellings ($)',
    'Average value of dwellings ($)',
    'Median monthly shelter costs for rented dwellings ($)',
    'Median monthly shelter costs for rented dwellings ($)',
    'Total - Highest certificate, diploma or degree for the population aged 15 years and over in private households - 25% sample data',
    'No certificate, diploma or degree',
    'High (secondary) school diploma or equivalency certificate',
    'Postsecondary certificate, diploma or degree',
    'Apprenticeship or trades certificate or diploma',
    'College, CEGEP or other non-university certificate or diploma',
    'University certificate or diploma below bachelor level',
    'Bachelor\'s degree or higher',
    'Total - Location of study compared with province or territory of residence for the population aged 25 to 64 years in private households - 25% sample data',
    'Location of study inside Canada',
    'Same as province or territory of residence',
    'Different than province or territory of residence',
    'Location of study outside Canada',
    'Total - Population aged 15 years and over by labour force status - 25% sample data',
    'In the labour force',
    'Not in the labour force',
    'Total - Main mode of commuting for the employed labour force aged 15 years and over with a usual place of work or no fixed workplace address - 25% sample data',
    'Car, truck or van - as a driver',
    'Car, truck or van - as a passenger',
    'Public transit',
    'Walked',
    'Bicycle',
    'Other method',
    'Total - Commuting duration for the employed labour force aged 15 years and over with a usual place of work or no fixed workplace address - 25% sample data',
    'Less than 15 minutes',
    '15 to 29 minutes',
    '30 to 44 minutes',
    '45 to 59 minutes',
    '60 minutes and over',
    'Total - Mobility status 1 year ago - 25% sample data',
    'Non-movers',
    'Movers'
]

# remove values in df with leading spaces
census_2021['CHARACTERISTIC_NAME'] = census_2021['CHARACTERISTIC_NAME'].str.strip()

new_df = census_2021.loc[census_2021['CHARACTERISTIC_NAME'].isin(conditions_2021)]

# Find values in conditions that are not in 'CHARACTERISTIC_NAME' in new_df
missing_conditions = [condition for condition in conditions_2021 if condition not in new_df['CHARACTERISTIC_NAME'].values]

# Print the missing values
print("\nConditions not found in 'DIM: Profile of Census Tracts (2247)':")
if len(missing_conditions) == 0:
    print("No missing values found.")
else:
  for condition in missing_conditions:
    print(condition)

print(new_df)

Conditions not found in 'DIM: Profile of Census Tracts (2247)':
No missing values found.
         CENSUS_YEAR                DGUID  ALT_GEO_CODE  \
0               2021         2021S0503462         462.0
1               2021         2021S0503462         462.0
2               2021         2021S0503462         462.0
3               2021         2021S0503462         462.0
5               2021         2021S0503462         462.0
...              ...                  ...           ...
2641503         2021  2021S05074622401.00     4622401.0
2641504         2021  2021S05074622401.00     4622401.0
2641505         2021  2021S05074622401.00     4622401.0
2641506         2021  2021S05074622401.00     4622401.0
2641522         2021  2021S05074622402.00     4622402.0

                        GEO_LEVEL   GEO_NAME  TNR_SF  TNR_LF  \
0        Census metropolitan area   Montréal     2.6     3.4
1        Census metropolitan area   Montréal     2.6     3.4
2        Census metropolitan area   Montréal     2.6     3.4
3        Census metropolitan area   Montréal     2.6     3.4
5        Census metropolitan area   Montréal     2.6     3.4
...                           ...        ...     ...     ...
2641503              Census tract  4622401.0     1.2     1.8
2641504              Census tract  4622401.0     1.2     1.8
2641505              Census tract  4622401.0     1.2     1.8
2641506              Census tract  4622401.0     1.2     1.8
2641522              Census tract  4622402.0     0.9     1.5

         DATA_QUALITY_FLAG  CHARACTERISTIC_ID  \
0                    20000                  3
1                    20000                  4
2                    20000                  5
3                    20000                  6
5                    20000                  8
...                    ...                ...
2641503                  0               2613
2641504                  0               2614
2641505                  0               2615
2641506                  0               2616
2641522                  0                  1

                                      CHARACTERISTIC_NAME  ...  C2_COUNT_MEN+  \
0              Population percentage change, 2016 to 2021  ...            NaN
1                                 Total private dwellings  ...            NaN
2           Private dwellings occupied by usual residents  ...            NaN
3                 Population density per square kilometre  ...            NaN
5        Total - Age groups of the population - 100% data  ...      2104805.0
...                                                   ...  ...            ...
2641503                                  15 to 29 minutes  ...          295.0
2641504                                  30 to 44 minutes  ...          250.0
2641505                                  45 to 59 minutes  ...          120.0
2641506                               60 minutes and over  ...           55.0
2641522                                  Population, 2021  ...            NaN

         SYMBOL.1 C3_COUNT_WOMEN+  SYMBOL.2 C10_RATE_TOTAL  SYMBOL.3  \
0             ...             NaN       ...            4.6       NaN
1             ...             NaN       ...            NaN       ...
2             ...             NaN       ...            NaN       ...
3             ...             NaN       ...          919.0       NaN
5             NaN       2186925.0       NaN          100.0       NaN
...           ...             ...       ...            ...       ...
2641503       NaN           300.0       NaN           31.6       NaN
2641504       NaN           120.0       NaN           19.9       NaN
2641505       NaN            75.0       NaN           10.4       NaN
2641506       NaN            40.0       NaN            5.3       NaN
2641522       ...             NaN       ...            NaN       ...

        C11_RATE_MEN+  SYMBOL.4 C12_RATE_WOMEN+  SYMBOL.5
0                 NaN       ...             NaN       ...
1                 NaN       ...             NaN       ...
2                 NaN       ...             NaN       ...
3                 NaN       ...             NaN       ...
5               100.0       NaN           100.0       NaN
...               ...       ...             ...       ...
2641503          29.8       NaN            33.7       NaN
2641504          25.3       NaN            13.5       NaN
2641505          12.1       NaN             8.4       NaN
2641506           5.6       NaN             4.5       NaN
2641522           NaN       ...             NaN       ...

[115460 rows x 23 columns]

In [ ]:
print(len(new_df))

115460

In [ ]:
# drop unecessary columns

new_df = new_df.drop('DGUID', axis=1)
# new_df = new_df.drop('ALT_GEO_CODE', axis=1)
new_df = new_df.drop('GEO_LEVEL', axis=1)
new_df = new_df.drop('TNR_SF', axis=1)
new_df = new_df.drop('TNR_LF', axis=1)
new_df = new_df.drop('DATA_QUALITY_FLAG', axis=1)
new_df = new_df.drop('CHARACTERISTIC_ID', axis=1)
new_df = new_df.drop('CHARACTERISTIC_NOTE', axis=1)
new_df = new_df.drop('SYMBOL', axis=1)
new_df = new_df.drop('C2_COUNT_MEN+', axis=1)
new_df = new_df.drop('SYMBOL.1', axis=1)
new_df = new_df.drop('C3_COUNT_WOMEN+', axis=1)
new_df = new_df.drop('SYMBOL.2', axis=1)
new_df = new_df.drop('C10_RATE_TOTAL', axis=1)
new_df = new_df.drop('SYMBOL.3', axis=1)
new_df = new_df.drop('C11_RATE_MEN+', axis=1)
new_df = new_df.drop('SYMBOL.4', axis=1)
new_df = new_df.drop('C12_RATE_WOMEN+', axis=1)
new_df = new_df.drop('SYMBOL.5', axis=1)

print(new_df.head())

   CENSUS_YEAR  ALT_GEO_CODE  GEO_NAME  \
0         2021         462.0  Montréal
1         2021         462.0  Montréal
2         2021         462.0  Montréal
3         2021         462.0  Montréal
5         2021         462.0  Montréal

                                CHARACTERISTIC_NAME  C1_COUNT_TOTAL
0        Population percentage change, 2016 to 2021             4.6
1                           Total private dwellings       1929263.0
2     Private dwellings occupied by usual residents       1835698.0
3           Population density per square kilometre           919.0
5  Total - Age groups of the population - 100% data       4291735.0

In [ ]:
# loop over rows, make a dict
# items = {'region':{}}
items = {}
for i in range(len(new_df)):
  # if i > 10:
  #   break
  # print(new_df.iloc[i]['GEO_NAME'])
  outer_key = new_df.iloc[i]['GEO_NAME']
  if outer_key in items:
    inner_key = new_df.iloc[i]['CHARACTERISTIC_NAME'] + ' 2021'
    items[outer_key][inner_key] = new_df.iloc[i]['C1_COUNT_TOTAL']
  else:
    items[outer_key] = {'ctuid': new_df.iloc[i]['ALT_GEO_CODE']}
    inner_key = new_df.iloc[i]['CHARACTERISTIC_NAME'] + ' 2021'
    items[outer_key][inner_key] = new_df.iloc[i]['C1_COUNT_TOTAL']
print(items.keys())

dict_keys(['Montréal', '4620001.00', '4620002.00', '4620002.0', '4620003.0', '4620004.0', '4620005.0', '4620006.0', '4620007.0', '4620008.0', '4620009.0', '4620010.0', '4620011.0', '4620012.01', 4620012.01, 4620012.02, 4620013.0, 4620014.02, 4620014.03, 4620014.04, 4620015.0, 4620016.0, 4620017.0, 4620018.0, 4620019.0, 4620021.0, 4620022.0, 4620023.0, 4620024.0, 4620025.0, 4620026.0, 4620027.0, 4620028.0, 4620029.0, 4620030.0, 4620031.0, 4620032.0, 4620033.0, 4620034.0, 4620035.0, 4620036.0, 4620037.0, 4620038.0, 4620039.0, 4620040.0, 4620041.0, 4620042.0, 4620043.0, 4620044.0, 4620045.0, 4620046.0, 4620047.0, 4620048.0, 4620049.0, 4620050.0, 4620051.0, 4620052.0, 4620053.0, 4620054.0, 4620055.01, 4620055.02, 4620056.0, 4620057.0, 4620058.0, 4620059.0, 4620060.0, 4620061.0, 4620062.0, 4620063.0, 4620064.0, 4620065.01, 4620065.02, 4620066.01, 4620066.02, 4620067.0, 4620068.0, 4620069.01, 4620069.02, 4620070.01, 4620070.02, 4620071.0, 4620072.0, 4620073.0, 4620074.0, 4620075.0, 4620076.0, 4620077.0, 4620078.0, 4620079.0, 4620080.0, 4620081.0, 4620082.0, 4620083.0, 4620084.0, 4620085.0, 4620086.0, 4620087.0, 4620088.0, 4620089.0, 4620090.0, 4620091.0, 4620092.0, 4620093.0, 4620094.01, 4620094.02, 4620095.0, 4620096.0, 4620097.01, 4620097.02, 4620098.0, 4620099.0, 4620100.01, 4620100.02, 4620101.01, 4620101.02, 4620102.0, 4620103.0, 4620104.0, 4620105.0, 4620106.0, 4620107.0, 4620108.0, 4620109.0, 4620110.0, 4620111.0, 4620112.01, 4620112.02, 4620113.0, 4620114.0, 4620115.01, 4620115.02, 4620116.0, 4620117.0, 4620118.0, 4620119.0, 4620120.01, 4620120.02, 4620121.0, 4620122.0, 4620123.0, 4620124.0, 4620125.0, 4620126.0, 4620127.01, 4620127.02, 4620128.0, 4620129.01, 4620129.02, 4620130.0, 4620131.0, 4620132.0, 4620133.0, 4620134.0, 4620135.0, 4620136.0, 4620137.0, 4620138.0, 4620139.0, 4620140.0, 4620141.0, 4620142.0, 4620143.0, 4620144.0, 4620145.0, 4620146.0, 4620147.0, 4620148.0, 4620149.0, 4620150.0, 4620151.0, 4620152.0, 4620153.0, 4620154.0, 4620155.0, 4620156.0, 4620157.0, 4620158.0, 4620159.0, 4620160.0, 4620161.0, 4620162.0, 4620163.0, 4620164.0, 4620165.0, 4620166.0, 4620167.0, 4620168.0, 4620169.0, 4620170.0, 4620171.0, 4620172.0, 4620173.0, 4620174.0, 4620175.0, 4620176.0, 4620177.0, 4620178.0, 4620179.0, 4620180.0, 4620181.0, 4620182.0, 4620183.0, 4620184.0, 4620185.0, 4620186.0, 4620187.01, 4620187.03, 4620187.04, 4620188.01, 4620188.02, 4620189.0, 4620190.01, 4620190.02, 4620191.0, 4620192.0, 4620193.0, 4620194.01, 4620194.02, 4620195.01, 4620195.02, 4620195.03, 4620196.0, 4620197.0, 4620198.0, 4620199.0, 4620200.0, 4620201.0, 4620202.0, 4620203.0, 4620204.0, 4620205.0, 4620206.0, 4620207.0, 4620208.0, 4620209.0, 4620210.0, 4620211.0, 4620212.0, 4620213.0, 4620214.0, 4620215.0, 4620216.0, 4620217.0, 4620218.0, 4620219.0, 4620220.0, 4620221.0, 4620222.0, 4620223.01, 4620223.02, 4620224.0, 4620225.0, 4620226.0, 4620227.0, 4620228.0, 4620229.0, 4620230.0, 4620231.0, 4620232.0, 4620233.0, 4620234.0, 4620235.0, 4620236.0, 4620237.0, 4620238.0, 4620239.0, 4620240.0, 4620241.0, 4620242.0, 4620243.0, 4620244.0, 4620245.0, 4620247.0, 4620249.0, 4620250.0, 4620251.01, 4620251.02, 4620252.0, 4620253.0, 4620254.0, 4620256.0, 4620257.0, 4620258.0, 4620259.0, 4620260.0, 4620261.0, 4620262.0, 4620263.0, 4620264.01, 4620264.02, 4620265.0, 4620266.0, 4620267.0, 4620268.01, 4620268.02, 4620268.03, 4620269.0, 4620270.0, 4620271.0, 4620272.0, 4620273.0, 4620274.0, 4620275.0, 4620276.0, 4620277.0, 4620278.0, 4620279.0, 4620280.0, 4620281.0, 4620282.0, 4620283.01, 4620283.02, 4620284.0, 4620285.0, 4620286.0, 4620287.01, 4620287.02, 4620288.0, 4620290.01, 4620290.02, 4620290.03, 4620290.04, 4620290.05, 4620290.06, 4620290.07, 4620290.08, 4620290.09, 4620291.01, 4620291.03, 4620291.04, 4620300.0, 4620301.0, 4620302.0, 4620303.0, 4620304.0, 4620305.0, 4620306.0, 4620307.0, 4620308.0, 4620309.0, 4620310.0, 4620311.0, 4620312.0, 4620313.0, 4620314.0, 4620315.0, 4620316.0, 4620317.03, 4620317.05, 4620317.06, 4620317.07, 4620317.08, 4620320.0, 4620321.0, 4620322.02, 4620322.03, 4620322.04, 4620323.0, 4620324.01, 4620324.02, 4620325.01, 4620325.02, 4620325.03, 4620325.05, 4620325.06, 4620326.01, 4620326.02, 4620326.03, 4620327.0, 4620328.0, 4620329.0, 4620330.0, 4620340.0, 4620350.0, 4620351.0, 4620352.0, 4620353.0, 4620354.0, 4620355.0, 4620356.0, 4620360.0, 4620361.0, 4620362.0, 4620363.0, 4620364.0, 4620365.0, 4620366.0, 4620367.0, 4620370.0, 4620380.0, 4620381.0, 4620382.01, 4620382.02, 4620383.01, 4620383.02, 4620385.0, 4620390.0, 4620391.0, 4620392.0, 4620393.0, 4620394.0, 4620395.01, 4620395.02, 4620395.03, 4620396.0, 4620397.0, 4620400.0, 4620401.0, 4620402.0, 4620403.0, 4620404.0, 4620410.01, 4620410.02, 4620410.03, 4620412.0, 4620413.01, 4620413.02, 4620415.03, 4620415.04, 4620415.07, 4620415.08, 4620415.09, 4620415.1, 4620416.01, 4620416.02, 4620417.01, 4620417.02, 4620418.0, 4620419.0, 4620420.0, 4620421.03, 4620421.04, 4620421.05, 4620421.06, 4620430.0, 4620431.0, 4620432.0, 4620433.0, 4620440.0, 4620450.0, 4620451.0, 4620452.0, 4620453.01, 4620453.02, 4620460.0, 4620461.0, 4620462.01, 4620462.02, 4620470.01, 4620470.03, 4620470.04, 4620470.05, 4620480.0, 4620490.0, 4620491.0, 4620500.0, 4620511.01, 4620511.02, 4620512.02, 4620512.03, 4620512.04, 4620513.01, 4620513.02, 4620514.01, 4620514.02, 4620515.01, 4620515.02, 4620515.03, 4620515.04, 4620520.02, 4620520.03, 4620520.04, 4620521.01, 4620521.04, 4620521.05, 4620521.06, 4620521.07, 4620522.01, 4620522.02, 4620523.0, 4620530.0, 4620540.0, 4620550.02, 4620550.03, 4620550.04, 4620570.0, 4620580.01, 4620580.02, 4620580.03, 4620581.01, 4620581.02, 4620582.01, 4620582.02, 4620583.0, 4620584.0, 4620585.01, 4620585.02, 4620590.01, 4620590.02, 4620591.01, 4620591.02, 4620592.0, 4620593.01, 4620593.02, 4620594.01, 4620594.02, 4620600.01, 4620600.02, 4620600.03, 4620601.01, 4620601.02, 4620602.01, 4620602.02, 4620603.01, 4620603.02, 4620603.03, 4620604.01, 4620604.02, 4620604.03, 4620604.04, 4620604.05, 4620605.01, 4620605.02, 4620605.03, 4620605.04, 4620605.05, 4620610.01, 4620610.02, 4620610.03, 4620610.04, 4620610.05, 4620610.06, 4620610.07, 4620611.01, 4620611.02, 4620612.0, 4620613.0, 4620614.0, 4620615.0, 4620616.0, 4620617.01, 4620617.02, 4620618.0, 4620619.0, 4620625.01, 4620625.02, 4620626.0, 4620627.0, 4620628.01, 4620628.02, 4620629.0, 4620630.01, 4620630.02, 4620631.0, 4620632.01, 4620632.02, 4620632.03, 4620632.04, 4620633.0, 4620634.0, 4620635.0, 4620636.0, 4620637.01, 4620637.02, 4620638.01, 4620638.02, 4620638.03, 4620638.04, 4620639.0, 4620640.0, 4620641.01, 4620641.02, 4620642.0, 4620643.01, 4620643.02, 4620643.03, 4620644.0, 4620645.0, 4620646.01, 4620646.02, 4620646.03, 4620647.01, 4620647.02, 4620648.0, 4620649.01, 4620649.02, 4620650.01, 4620650.02, 4620650.04, 4620650.05, 4620651.01, 4620651.02, 4620652.01, 4620652.04, 4620652.06, 4620652.07, 4620652.08, 4620652.09, 4620653.0, 4620654.0, 4620655.01, 4620655.02, 4620656.01, 4620656.03, 4620656.04, 4620657.01, 4620657.02, 4620657.03, 4620658.01, 4620658.02, 4620658.03, 4620659.04, 4620659.05, 4620659.06, 4620659.08, 4620659.09, 4620659.1, 4620659.11, 4620660.01, 4620660.02, 4620660.03, 4620661.01, 4620661.03, 4620661.04, 4620662.0, 4620675.0, 4620676.01, 4620676.02, 4620676.03, 4620676.04, 4620677.01, 4620677.02, 4620677.05, 4620677.07, 4620677.09, 4620677.1, 4620677.11, 4620677.12, 4620677.13, 4620677.14, 4620681.0, 4620682.02, 4620682.04, 4620682.05, 4620682.06, 4620682.07, 4620682.08, 4620683.0, 4620684.05, 4620684.08, 4620684.09, 4620684.1, 4620684.11, 4620684.12, 4620684.13, 4620684.14, 4620685.02, 4620685.03, 4620685.04, 4620685.05, 4620685.07, 4620685.09, 4620685.1, 4620685.11, 4620686.01, 4620686.02, 4620686.03, 4620687.01, 4620687.04, 4620687.06, 4620687.07, 4620687.09, 4620687.11, 4620687.12, 4620687.13, 4620687.14, 4620688.02, 4620688.03, 4620688.04, 4620689.01, 4620689.02, 4620689.04, 4620689.05, 4620689.06, 4620690.0, 4620691.0, 4620692.01, 4620692.02, 4620693.0, 4620694.01, 4620694.02, 4620700.01, 4620700.03, 4620700.04, 4620701.01, 4620701.02, 4620702.01, 4620702.02, 4620703.02, 4620703.03, 4620703.04, 4620704.01, 4620704.04, 4620704.05, 4620704.06, 4620704.08, 4620704.09, 4620705.01, 4620705.02, 4620706.0, 4620707.0, 4620708.01, 4620708.02, 4620709.01, 4620709.02, 4620710.03, 4620710.05, 4620710.06, 4620710.07, 4620710.08, 4620710.09, 4620710.1, 4620710.11, 4620725.03, 4620725.04, 4620725.06, 4620725.07, 4620725.09, 4620725.1, 4620726.01, 4620726.03, 4620726.04, 4620727.01, 4620727.02, 4620728.01, 4620728.02, 4620728.03, 4620729.0, 4620730.01, 4620730.02, 4620731.0, 4620732.01, 4620732.03, 4620732.04, 4620733.01, 4620733.02, 4620734.03, 4620734.04, 4620734.05, 4620734.06, 4620734.07, 4620735.01, 4620735.02, 4620740.01, 4620740.03, 4620740.04, 4620750.01, 4620750.02, 4620750.04, 4620750.06, 4620750.07, 4620751.01, 4620751.02, 4620755.01, 4620755.03, 4620755.04, 4620755.05, 4620756.02, 4620756.03, 4620756.04, 4620756.05, 4620757.0, 4620758.03, 4620758.04, 4620758.05, 4620758.06, 4620760.0, 4620775.0, 4620776.0, 4620777.01, 4620777.02, 4620780.0, 4620781.0, 4620782.0, 4620783.0, 4620784.0, 4620785.0, 4620786.0, 4620787.01, 4620787.02, 4620788.0, 4620789.01, 4620789.02, 4620790.01, 4620790.02, 4620791.01, 4620791.02, 4620792.0, 4620800.01, 4620800.02, 4620801.0, 4620802.0, 4620804.01, 4620804.02, 4620805.01, 4620805.02, 4620806.01, 4620806.02, 4620807.01, 4620807.02, 4620825.02, 4620825.03, 4620825.04, 4620825.05, 4620825.06, 4620825.07, 4620825.08, 4620826.02, 4620826.05, 4620826.06, 4620826.07, 4620826.08, 4620826.09, 4620826.1, 4620826.11, 4620826.13, 4620826.15, 4620826.16, 4620827.02, 4620827.03, 4620827.04, 4620828.03, 4620828.04, 4620828.05, 4620828.06, 4620829.0, 4620830.01, 4620830.03, 4620830.04, 4620831.03, 4620831.04, 4620831.05, 4620831.07, 4620831.08, 4620831.09, 4620832.0, 4620833.0, 4620834.0, 4620850.03, 4620850.04, 4620850.05, 4620850.06, 4620850.07, 4620851.0, 4620852.02, 4620852.03, 4620852.04, 4620852.05, 4620853.02, 4620853.03, 4620853.04, 4620854.01, 4620854.02, 4620855.01, 4620855.03, 4620855.04, 4620856.0, 4620857.01, 4620857.02, 4620857.06, 4620857.07, 4620857.08, 4620857.09, 4620857.1, 4620857.11, 4620857.12, 4620858.01, 4620858.02, 4620858.04, 4620858.05, 4620859.0, 4620860.01, 4620860.02, 4620861.0, 4620862.0, 4620863.01, 4620863.02, 4620864.0, 4620865.0, 4620866.0, 4620867.0, 4620868.01, 4620868.02, 4620869.0, 4620870.01, 4620870.02, 4620871.01, 4620871.02, 4620872.0, 4620873.01, 4620873.02, 4620874.0, 4620875.0, 4620876.01, 4620876.04, 4620876.05, 4620876.06, 4620876.07, 4620877.01, 4620877.02, 4620878.0, 4620879.01, 4620879.02, 4620880.0, 4620881.01, 4620881.02, 4620882.0, 4620883.0, 4620884.01, 4620884.02, 4620885.0, 4620886.01, 4620886.02, 4620886.03, 4620887.03, 4620887.04, 4620887.05, 4620887.06, 4620887.07, 4620888.01, 4620888.02, 4620888.03, 4620889.01, 4620889.02, 4620889.03, 4620900.0, 4620901.01, 4620901.02, 4620901.03, 4620902.0, 4620903.01, 4620903.04, 4620903.05, 4620903.08, 4620903.09, 4620903.1, 4620903.11, 4620903.12, 4620903.13, 4620903.14, 4620904.02, 4620904.03, 4620904.04, 4620904.05, 4620904.06, 4620926.01, 4620926.02, 4620929.01, 4620929.02, 4620930.02, 4620930.03, 4620930.04, 4621000.0, 4621001.0, 4621002.0, 4621003.0, 4621004.0, 4621005.0, 4621006.01, 4621006.02, 4621006.03, 4621009.0, 4622001.0, 4622002.0, 4622003.0, 4622004.0, 4622005.0, 4622006.0, 4622007.0, 4622008.0, 4622009.0, 4622010.0, 4622011.0, 4622012.0, 4622013.0, 4622014.0, 4622015.0, 4622100.0, 4622101.0, 4622102.0, 4622103.0, 4622200.0, 4622201.0, 4622202.0, 4622203.0, 4622204.0, 4622205.0, 4622206.0, 4622207.0, 4622300.0, 4622301.0, 4622302.0, 4622303.0, 4622304.0, 4622400.0, 4622401.0, 4622402.0])

In [ ]:
print(items.keys())

dict_keys(['Montréal', '4620001.00', '4620002.00', '4620002.0', '4620003.0', '4620004.0', '4620005.0', '4620006.0', '4620007.0', '4620008.0', '4620009.0', '4620010.0', '4620011.0', '4620012.01', 4620012.01, 4620012.02, 4620013.0, 4620014.02, 4620014.03, 4620014.04, 4620015.0, 4620016.0, 4620017.0, 4620018.0, 4620019.0, 4620021.0, 4620022.0, 4620023.0, 4620024.0, 4620025.0, 4620026.0, 4620027.0, 4620028.0, 4620029.0, 4620030.0, 4620031.0, 4620032.0, 4620033.0, 4620034.0, 4620035.0, 4620036.0, 4620037.0, 4620038.0, 4620039.0, 4620040.0, 4620041.0, 4620042.0, 4620043.0, 4620044.0, 4620045.0, 4620046.0, 4620047.0, 4620048.0, 4620049.0, 4620050.0, 4620051.0, 4620052.0, 4620053.0, 4620054.0, 4620055.01, 4620055.02, 4620056.0, 4620057.0, 4620058.0, 4620059.0, 4620060.0, 4620061.0, 4620062.0, 4620063.0, 4620064.0, 4620065.01, 4620065.02, 4620066.01, 4620066.02, 4620067.0, 4620068.0, 4620069.01, 4620069.02, 4620070.01, 4620070.02, 4620071.0, 4620072.0, 4620073.0, 4620074.0, 4620075.0, 4620076.0, 4620077.0, 4620078.0, 4620079.0, 4620080.0, 4620081.0, 4620082.0, 4620083.0, 4620084.0, 4620085.0, 4620086.0, 4620087.0, 4620088.0, 4620089.0, 4620090.0, 4620091.0, 4620092.0, 4620093.0, 4620094.01, 4620094.02, 4620095.0, 4620096.0, 4620097.01, 4620097.02, 4620098.0, 4620099.0, 4620100.01, 4620100.02, 4620101.01, 4620101.02, 4620102.0, 4620103.0, 4620104.0, 4620105.0, 4620106.0, 4620107.0, 4620108.0, 4620109.0, 4620110.0, 4620111.0, 4620112.01, 4620112.02, 4620113.0, 4620114.0, 4620115.01, 4620115.02, 4620116.0, 4620117.0, 4620118.0, 4620119.0, 4620120.01, 4620120.02, 4620121.0, 4620122.0, 4620123.0, 4620124.0, 4620125.0, 4620126.0, 4620127.01, 4620127.02, 4620128.0, 4620129.01, 4620129.02, 4620130.0, 4620131.0, 4620132.0, 4620133.0, 4620134.0, 4620135.0, 4620136.0, 4620137.0, 4620138.0, 4620139.0, 4620140.0, 4620141.0, 4620142.0, 4620143.0, 4620144.0, 4620145.0, 4620146.0, 4620147.0, 4620148.0, 4620149.0, 4620150.0, 4620151.0, 4620152.0, 4620153.0, 4620154.0, 4620155.0, 4620156.0, 4620157.0, 4620158.0, 4620159.0, 4620160.0, 4620161.0, 4620162.0, 4620163.0, 4620164.0, 4620165.0, 4620166.0, 4620167.0, 4620168.0, 4620169.0, 4620170.0, 4620171.0, 4620172.0, 4620173.0, 4620174.0, 4620175.0, 4620176.0, 4620177.0, 4620178.0, 4620179.0, 4620180.0, 4620181.0, 4620182.0, 4620183.0, 4620184.0, 4620185.0, 4620186.0, 4620187.01, 4620187.03, 4620187.04, 4620188.01, 4620188.02, 4620189.0, 4620190.01, 4620190.02, 4620191.0, 4620192.0, 4620193.0, 4620194.01, 4620194.02, 4620195.01, 4620195.02, 4620195.03, 4620196.0, 4620197.0, 4620198.0, 4620199.0, 4620200.0, 4620201.0, 4620202.0, 4620203.0, 4620204.0, 4620205.0, 4620206.0, 4620207.0, 4620208.0, 4620209.0, 4620210.0, 4620211.0, 4620212.0, 4620213.0, 4620214.0, 4620215.0, 4620216.0, 4620217.0, 4620218.0, 4620219.0, 4620220.0, 4620221.0, 4620222.0, 4620223.01, 4620223.02, 4620224.0, 4620225.0, 4620226.0, 4620227.0, 4620228.0, 4620229.0, 4620230.0, 4620231.0, 4620232.0, 4620233.0, 4620234.0, 4620235.0, 4620236.0, 4620237.0, 4620238.0, 4620239.0, 4620240.0, 4620241.0, 4620242.0, 4620243.0, 4620244.0, 4620245.0, 4620247.0, 4620249.0, 4620250.0, 4620251.01, 4620251.02, 4620252.0, 4620253.0, 4620254.0, 4620256.0, 4620257.0, 4620258.0, 4620259.0, 4620260.0, 4620261.0, 4620262.0, 4620263.0, 4620264.01, 4620264.02, 4620265.0, 4620266.0, 4620267.0, 4620268.01, 4620268.02, 4620268.03, 4620269.0, 4620270.0, 4620271.0, 4620272.0, 4620273.0, 4620274.0, 4620275.0, 4620276.0, 4620277.0, 4620278.0, 4620279.0, 4620280.0, 4620281.0, 4620282.0, 4620283.01, 4620283.02, 4620284.0, 4620285.0, 4620286.0, 4620287.01, 4620287.02, 4620288.0, 4620290.01, 4620290.02, 4620290.03, 4620290.04, 4620290.05, 4620290.06, 4620290.07, 4620290.08, 4620290.09, 4620291.01, 4620291.03, 4620291.04, 4620300.0, 4620301.0, 4620302.0, 4620303.0, 4620304.0, 4620305.0, 4620306.0, 4620307.0, 4620308.0, 4620309.0, 4620310.0, 4620311.0, 4620312.0, 4620313.0, 4620314.0, 4620315.0, 4620316.0, 4620317.03, 4620317.05, 4620317.06, 4620317.07, 4620317.08, 4620320.0, 4620321.0, 4620322.02, 4620322.03, 4620322.04, 4620323.0, 4620324.01, 4620324.02, 4620325.01, 4620325.02, 4620325.03, 4620325.05, 4620325.06, 4620326.01, 4620326.02, 4620326.03, 4620327.0, 4620328.0, 4620329.0, 4620330.0, 4620340.0, 4620350.0, 4620351.0, 4620352.0, 4620353.0, 4620354.0, 4620355.0, 4620356.0, 4620360.0, 4620361.0, 4620362.0, 4620363.0, 4620364.0, 4620365.0, 4620366.0, 4620367.0, 4620370.0, 4620380.0, 4620381.0, 4620382.01, 4620382.02, 4620383.01, 4620383.02, 4620385.0, 4620390.0, 4620391.0, 4620392.0, 4620393.0, 4620394.0, 4620395.01, 4620395.02, 4620395.03, 4620396.0, 4620397.0, 4620400.0, 4620401.0, 4620402.0, 4620403.0, 4620404.0, 4620410.01, 4620410.02, 4620410.03, 4620412.0, 4620413.01, 4620413.02, 4620415.03, 4620415.04, 4620415.07, 4620415.08, 4620415.09, 4620415.1, 4620416.01, 4620416.02, 4620417.01, 4620417.02, 4620418.0, 4620419.0, 4620420.0, 4620421.03, 4620421.04, 4620421.05, 4620421.06, 4620430.0, 4620431.0, 4620432.0, 4620433.0, 4620440.0, 4620450.0, 4620451.0, 4620452.0, 4620453.01, 4620453.02, 4620460.0, 4620461.0, 4620462.01, 4620462.02, 4620470.01, 4620470.03, 4620470.04, 4620470.05, 4620480.0, 4620490.0, 4620491.0, 4620500.0, 4620511.01, 4620511.02, 4620512.02, 4620512.03, 4620512.04, 4620513.01, 4620513.02, 4620514.01, 4620514.02, 4620515.01, 4620515.02, 4620515.03, 4620515.04, 4620520.02, 4620520.03, 4620520.04, 4620521.01, 4620521.04, 4620521.05, 4620521.06, 4620521.07, 4620522.01, 4620522.02, 4620523.0, 4620530.0, 4620540.0, 4620550.02, 4620550.03, 4620550.04, 4620570.0, 4620580.01, 4620580.02, 4620580.03, 4620581.01, 4620581.02, 4620582.01, 4620582.02, 4620583.0, 4620584.0, 4620585.01, 4620585.02, 4620590.01, 4620590.02, 4620591.01, 4620591.02, 4620592.0, 4620593.01, 4620593.02, 4620594.01, 4620594.02, 4620600.01, 4620600.02, 4620600.03, 4620601.01, 4620601.02, 4620602.01, 4620602.02, 4620603.01, 4620603.02, 4620603.03, 4620604.01, 4620604.02, 4620604.03, 4620604.04, 4620604.05, 4620605.01, 4620605.02, 4620605.03, 4620605.04, 4620605.05, 4620610.01, 4620610.02, 4620610.03, 4620610.04, 4620610.05, 4620610.06, 4620610.07, 4620611.01, 4620611.02, 4620612.0, 4620613.0, 4620614.0, 4620615.0, 4620616.0, 4620617.01, 4620617.02, 4620618.0, 4620619.0, 4620625.01, 4620625.02, 4620626.0, 4620627.0, 4620628.01, 4620628.02, 4620629.0, 4620630.01, 4620630.02, 4620631.0, 4620632.01, 4620632.02, 4620632.03, 4620632.04, 4620633.0, 4620634.0, 4620635.0, 4620636.0, 4620637.01, 4620637.02, 4620638.01, 4620638.02, 4620638.03, 4620638.04, 4620639.0, 4620640.0, 4620641.01, 4620641.02, 4620642.0, 4620643.01, 4620643.02, 4620643.03, 4620644.0, 4620645.0, 4620646.01, 4620646.02, 4620646.03, 4620647.01, 4620647.02, 4620648.0, 4620649.01, 4620649.02, 4620650.01, 4620650.02, 4620650.04, 4620650.05, 4620651.01, 4620651.02, 4620652.01, 4620652.04, 4620652.06, 4620652.07, 4620652.08, 4620652.09, 4620653.0, 4620654.0, 4620655.01, 4620655.02, 4620656.01, 4620656.03, 4620656.04, 4620657.01, 4620657.02, 4620657.03, 4620658.01, 4620658.02, 4620658.03, 4620659.04, 4620659.05, 4620659.06, 4620659.08, 4620659.09, 4620659.1, 4620659.11, 4620660.01, 4620660.02, 4620660.03, 4620661.01, 4620661.03, 4620661.04, 4620662.0, 4620675.0, 4620676.01, 4620676.02, 4620676.03, 4620676.04, 4620677.01, 4620677.02, 4620677.05, 4620677.07, 4620677.09, 4620677.1, 4620677.11, 4620677.12, 4620677.13, 4620677.14, 4620681.0, 4620682.02, 4620682.04, 4620682.05, 4620682.06, 4620682.07, 4620682.08, 4620683.0, 4620684.05, 4620684.08, 4620684.09, 4620684.1, 4620684.11, 4620684.12, 4620684.13, 4620684.14, 4620685.02, 4620685.03, 4620685.04, 4620685.05, 4620685.07, 4620685.09, 4620685.1, 4620685.11, 4620686.01, 4620686.02, 4620686.03, 4620687.01, 4620687.04, 4620687.06, 4620687.07, 4620687.09, 4620687.11, 4620687.12, 4620687.13, 4620687.14, 4620688.02, 4620688.03, 4620688.04, 4620689.01, 4620689.02, 4620689.04, 4620689.05, 4620689.06, 4620690.0, 4620691.0, 4620692.01, 4620692.02, 4620693.0, 4620694.01, 4620694.02, 4620700.01, 4620700.03, 4620700.04, 4620701.01, 4620701.02, 4620702.01, 4620702.02, 4620703.02, 4620703.03, 4620703.04, 4620704.01, 4620704.04, 4620704.05, 4620704.06, 4620704.08, 4620704.09, 4620705.01, 4620705.02, 4620706.0, 4620707.0, 4620708.01, 4620708.02, 4620709.01, 4620709.02, 4620710.03, 4620710.05, 4620710.06, 4620710.07, 4620710.08, 4620710.09, 4620710.1, 4620710.11, 4620725.03, 4620725.04, 4620725.06, 4620725.07, 4620725.09, 4620725.1, 4620726.01, 4620726.03, 4620726.04, 4620727.01, 4620727.02, 4620728.01, 4620728.02, 4620728.03, 4620729.0, 4620730.01, 4620730.02, 4620731.0, 4620732.01, 4620732.03, 4620732.04, 4620733.01, 4620733.02, 4620734.03, 4620734.04, 4620734.05, 4620734.06, 4620734.07, 4620735.01, 4620735.02, 4620740.01, 4620740.03, 4620740.04, 4620750.01, 4620750.02, 4620750.04, 4620750.06, 4620750.07, 4620751.01, 4620751.02, 4620755.01, 4620755.03, 4620755.04, 4620755.05, 4620756.02, 4620756.03, 4620756.04, 4620756.05, 4620757.0, 4620758.03, 4620758.04, 4620758.05, 4620758.06, 4620760.0, 4620775.0, 4620776.0, 4620777.01, 4620777.02, 4620780.0, 4620781.0, 4620782.0, 4620783.0, 4620784.0, 4620785.0, 4620786.0, 4620787.01, 4620787.02, 4620788.0, 4620789.01, 4620789.02, 4620790.01, 4620790.02, 4620791.01, 4620791.02, 4620792.0, 4620800.01, 4620800.02, 4620801.0, 4620802.0, 4620804.01, 4620804.02, 4620805.01, 4620805.02, 4620806.01, 4620806.02, 4620807.01, 4620807.02, 4620825.02, 4620825.03, 4620825.04, 4620825.05, 4620825.06, 4620825.07, 4620825.08, 4620826.02, 4620826.05, 4620826.06, 4620826.07, 4620826.08, 4620826.09, 4620826.1, 4620826.11, 4620826.13, 4620826.15, 4620826.16, 4620827.02, 4620827.03, 4620827.04, 4620828.03, 4620828.04, 4620828.05, 4620828.06, 4620829.0, 4620830.01, 4620830.03, 4620830.04, 4620831.03, 4620831.04, 4620831.05, 4620831.07, 4620831.08, 4620831.09, 4620832.0, 4620833.0, 4620834.0, 4620850.03, 4620850.04, 4620850.05, 4620850.06, 4620850.07, 4620851.0, 4620852.02, 4620852.03, 4620852.04, 4620852.05, 4620853.02, 4620853.03, 4620853.04, 4620854.01, 4620854.02, 4620855.01, 4620855.03, 4620855.04, 4620856.0, 4620857.01, 4620857.02, 4620857.06, 4620857.07, 4620857.08, 4620857.09, 4620857.1, 4620857.11, 4620857.12, 4620858.01, 4620858.02, 4620858.04, 4620858.05, 4620859.0, 4620860.01, 4620860.02, 4620861.0, 4620862.0, 4620863.01, 4620863.02, 4620864.0, 4620865.0, 4620866.0, 4620867.0, 4620868.01, 4620868.02, 4620869.0, 4620870.01, 4620870.02, 4620871.01, 4620871.02, 4620872.0, 4620873.01, 4620873.02, 4620874.0, 4620875.0, 4620876.01, 4620876.04, 4620876.05, 4620876.06, 4620876.07, 4620877.01, 4620877.02, 4620878.0, 4620879.01, 4620879.02, 4620880.0, 4620881.01, 4620881.02, 4620882.0, 4620883.0, 4620884.01, 4620884.02, 4620885.0, 4620886.01, 4620886.02, 4620886.03, 4620887.03, 4620887.04, 4620887.05, 4620887.06, 4620887.07, 4620888.01, 4620888.02, 4620888.03, 4620889.01, 4620889.02, 4620889.03, 4620900.0, 4620901.01, 4620901.02, 4620901.03, 4620902.0, 4620903.01, 4620903.04, 4620903.05, 4620903.08, 4620903.09, 4620903.1, 4620903.11, 4620903.12, 4620903.13, 4620903.14, 4620904.02, 4620904.03, 4620904.04, 4620904.05, 4620904.06, 4620926.01, 4620926.02, 4620929.01, 4620929.02, 4620930.02, 4620930.03, 4620930.04, 4621000.0, 4621001.0, 4621002.0, 4621003.0, 4621004.0, 4621005.0, 4621006.01, 4621006.02, 4621006.03, 4621009.0, 4622001.0, 4622002.0, 4622003.0, 4622004.0, 4622005.0, 4622006.0, 4622007.0, 4622008.0, 4622009.0, 4622010.0, 4622011.0, 4622012.0, 4622013.0, 4622014.0, 4622015.0, 4622100.0, 4622101.0, 4622102.0, 4622103.0, 4622200.0, 4622201.0, 4622202.0, 4622203.0, 4622204.0, 4622205.0, 4622206.0, 4622207.0, 4622300.0, 4622301.0, 4622302.0, 4622303.0, 4622304.0, 4622400.0, 4622401.0, 4622402.0])

In [ ]:
# Convert the dictionary of dictionaries into a DataFrame
census_2021 = pd.DataFrame.from_dict(items, orient='index')

# Write the DataFrame to a CSV file
# census_2021.to_csv('/content/drive/MyDrive/Ai4Good Colabs (Emily Hong)/2021_output.csv')
census_2021.to_csv('/content/drive/MyDrive/GentrificAItion/Montreal_data_from_census/2021_emilie_v1.csv')

print(census_2021)

                ctuid  Population percentage change, 2016 to 2021 2021  \
Montréal        462.0                                              4.6
4620001.00  4620001.0                                              1.7
4620002.00  4620002.0                                              7.5
4620002.0   4620002.0                                              NaN
4620003.0   4620003.0                                              3.6
...               ...                                              ...
4622303.0   4622303.0                                              NaN
4622304.0   4622304.0                                             -2.4
4622400.0   4622400.0                                              1.8
4622401.0   4622401.0                                             10.8
4622402.0   4622402.0                                              NaN

            Total private dwellings 2021  \
Montréal                       1929263.0
4620001.00                        1463.0
4620002.00                        2022.0
4620002.0                            NaN
4620003.0                         3174.0
...                                  ...
4622303.0                            3.0
4622304.0                          451.0
4622400.0                         1196.0
4622401.0                         1574.0
4622402.0                            NaN

            Private dwellings occupied by usual residents 2021  \
Montréal                                            1835698.0
4620001.00                                             1402.0
4620002.00                                             1944.0
4620002.0                                                 NaN
4620003.0                                              3016.0
...                                                       ...
4622303.0                                                 3.0
4622304.0                                               444.0
4622400.0                                              1148.0
4622401.0                                              1546.0
4622402.0                                                 NaN

            Population density per square kilometre 2021  \
Montréal                                           919.0
4620001.00                                        5780.7
4620002.00                                        9797.8
4620002.0                                            NaN
4620003.0                                         8917.7
...                                                  ...
4622303.0                                            7.8
4622304.0                                         1530.5
4622400.0                                           59.9
4622401.0                                          925.4
4622402.0                                            NaN

            Total - Age groups of the population - 100% data 2021  \
Montréal                                            4291735.0
4620001.00                                             2685.0
4620002.00                                             3780.0
4620002.0                                                 NaN
4620003.0                                              6600.0
...                                                       ...
4622303.0                                                 NaN
4622304.0                                              1065.0
4622400.0                                              2785.0
4622401.0                                              4095.0
4622402.0                                                 NaN

            0 to 14 years 2021  15 to 19 years 2021  20 to 24 years 2021  \
Montréal                  16.8             227955.0             257910.0
4620001.00                13.6                 85.0                145.0
4620002.00                16.5                155.0                190.0
4620002.0                  NaN                  NaN                  NaN
4620003.0                 16.7                305.0                365.0
...                        ...                  ...                  ...
4622303.0                  NaN                  NaN                  NaN
4622304.0                 15.0                 60.0                 50.0
4622400.0                 16.7                140.0                110.0
4622401.0                 21.7                205.0                175.0
4622402.0                  NaN                  NaN                  NaN

            25 to 29 years 2021  ...  Walked 2021  Bicycle 2021  \
Montréal               291650.0  ...      89445.0       28240.0
4620001.00                235.0  ...         15.0          20.0
4620002.00                280.0  ...          NaN           NaN
4620002.0                   NaN  ...         30.0          10.0
4620003.0                 445.0  ...        135.0          50.0
...                         ...  ...          ...           ...
4622303.0                   NaN  ...          NaN           NaN
4622304.0                  40.0  ...         10.0           0.0
4622400.0                 170.0  ...          0.0           0.0
4622401.0                 235.0  ...         20.0           0.0
4622402.0                   NaN  ...          NaN           NaN

            Other method 2021  \
Montréal              25780.0
4620001.00               10.0
4620002.00                NaN
4620002.0                 0.0
4620003.0                35.0
...                       ...
4622303.0                 NaN
4622304.0                 0.0
4622400.0                 0.0
4622401.0                 0.0
4622402.0                 NaN

            Total - Commuting duration for the employed labour force aged 15 years and over with a usual place of work or no fixed workplace address - 25% sample data 2021  \
Montréal                                            1566265.0
4620001.00                                             1030.0
4620002.00                                                NaN
4620002.0                                              1395.0
4620003.0                                              2530.0
...                                                       ...
4622303.0                                                 NaN
4622304.0                                               360.0
4622400.0                                              1170.0
4622401.0                                              1880.0
4622402.0                                                 NaN

            Less than 15 minutes 2021  15 to 29 minutes 2021  \
Montréal                     338465.0               556715.0
4620001.00                      180.0                  360.0
4620002.00                        NaN                    NaN
4620002.0                       210.0                  485.0
4620003.0                       470.0                  800.0
...                               ...                    ...
4622303.0                         NaN                    NaN
4622304.0                       185.0                   65.0
4622400.0                       350.0                  360.0
4622401.0                       620.0                  595.0
4622402.0                         NaN                    NaN

            30 to 44 minutes 2021  45 to 59 minutes 2021  \
Montréal                 393635.0               151820.0
4620001.00                  255.0                  135.0
4620002.00                    NaN                    NaN
4620002.0                   325.0                  185.0
4620003.0                   660.0                  370.0
...                           ...                    ...
4622303.0                     NaN                    NaN
4622304.0                    50.0                   45.0
4622400.0                   280.0                  145.0
4622401.0                   375.0                  195.0
4622402.0                     NaN                    NaN

            60 minutes and over 2021  Population, 2021 2021
Montréal                    125625.0                    NaN
4620001.00                     100.0                 2684.0
4620002.00                       NaN                 3780.0
4620002.0                      185.0                    NaN
4620003.0                      230.0                 6600.0
...                              ...                    ...
4622303.0                        NaN                   10.0
4622304.0                       10.0                 1068.0
4622400.0                       35.0                 2778.0
4622401.0                      100.0                 4091.0
4622402.0                        NaN                 3787.0

[1007 rows x 100 columns]

# 2011 Data Cleaning

In [3]:
import pandas as pd

census_2011_1 = pd.read_csv('/content/drive/MyDrive/GentrificAItion/Montreal_data_from_census/2011_montreal_data.csv')

print(census_2011_1)

        Unnamed: 0    Geo_Code Prov_Name CMACA_Name  CT_Name  \
0           294056  4620725.07    Quebec   Montréal   725.07
1           294057  4620725.07    Quebec   Montréal   725.07
2           294058  4620725.07    Quebec   Montréal   725.07
3           294059  4620725.07    Quebec   Montréal   725.07
4           294060  4620725.07    Quebec   Montréal   725.07
...            ...         ...       ...        ...      ...
434707      728763  4620831.07    Quebec   Montréal   831.07
434708      728764  4620831.07    Quebec   Montréal   831.07
434709      728765  4620831.07    Quebec   Montréal   831.07
434710      728766  4620831.07    Quebec   Montréal   831.07
434711      728767  4620831.07    Quebec   Montréal   831.07

                                                   Topic  \
0                         Population and dwelling counts
1                         Population and dwelling counts
2                         Population and dwelling counts
3                         Population and dwelling counts
4                         Population and dwelling counts
...                                                  ...
434707  Detailed other language spoken regularly at home
434708  Detailed other language spoken regularly at home
434709  Detailed other language spoken regularly at home
434710  Detailed other language spoken regularly at home
434711  Detailed other language spoken regularly at home

                                        Characteristic  Note   Total  \
0                                   Population in 2011   1.0  6440.0
1                                   Population in 2006   1.0  6339.0
2                   2006 to 2011 population change (%)   NaN     1.6
3                              Total private dwellings   2.0  2168.0
4        Private dwellings occupied by usual residents   3.0  2159.0
...                                                ...   ...     ...
434707                     Multiple responses            NaN    10.0
434708                             English and French    NaN     5.0
434709              English and non-official language    NaN     0.0
434710               French and non-official language    NaN     0.0
434711      English, French and non-official language    NaN     0.0

       Flag_Total  Male Flag_Male  Female Flag_female
0             NaN   NaN       ...     NaN         ...
1             NaN   NaN       ...     NaN         ...
2             NaN   NaN       ...     NaN         ...
3             NaN   NaN       ...     NaN         ...
4             NaN   NaN       ...     NaN         ...
...           ...   ...       ...     ...         ...
434707        NaN   0.0       NaN     5.0         NaN
434708        NaN   0.0       NaN     0.0         NaN
434709        NaN   0.0       NaN     5.0         NaN
434710        NaN   0.0       NaN     0.0         NaN
434711        NaN   0.0       NaN     0.0         NaN

[434712 rows x 14 columns]

In [4]:
census_2011_2 = pd.read_csv('/content/drive/MyDrive/GentrificAItion/Montreal_data_from_census/2011_montreal_data_2.csv')
print(census_2011_2)

<ipython-input-4-ca738f9b6672>:1: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  census_2011_2 = pd.read_csv('/content/drive/MyDrive/GentrificAItion/Montreal_data_from_census/2011_montreal_data_2.csv')

        Unnamed: 0    Geo_Code Prov_Name CMA_CA_Name  CT_Name   GNR  \
0           357120  4620725.07    Quebec    Montréal   725.07  20.4
1           357121  4620725.07    Quebec    Montréal   725.07  20.4
2           357122  4620725.07    Quebec    Montréal   725.07  20.4
3           357123  4620725.07    Quebec    Montréal   725.07  20.4
4           357124  4620725.07    Quebec    Montréal   725.07  20.4
...            ...         ...       ...         ...      ...   ...
866875     1223995  4620876.05    Quebec    Montréal   876.05  19.4
866876     1223996  4620876.05    Quebec    Montréal   876.05  19.4
866877     1223997  4620876.05    Quebec    Montréal   876.05  19.4
866878     1223998  4620876.05    Quebec    Montréal   876.05  19.4
866879     1223999  4620876.05    Quebec    Montréal   876.05  19.4

                                Topic  \
0                         Citizenship
1                         Citizenship
2                         Citizenship
3                         Citizenship
4                         Citizenship
...                               ...
866875  Income of individuals in 2010
866876  Income of individuals in 2010
866877  Income of individuals in 2010
866878  Income of individuals in 2010
866879  Income of individuals in 2010

                                           Characteristic  Note   Total  \
0       Total population in private households by citi...   1.0  6440.0
1                                       Canadian citizens   NaN  6360.0
2                         Canadian citizens aged under 18   NaN  1895.0
3                      Canadian citizens aged 18 and over   NaN  4465.0
4                                   Not Canadian citizens   2.0    80.0
...                                                   ...   ...     ...
866875  Prevalence of low income in 2010 based on afte...   NaN     8.5
866876                             Less than 18 years (%)   NaN    12.9
866877                              Less than 6 years (%)   NaN     7.7
866878                                 18 to 64 years (%)   NaN     6.4
866879                              65 years and over (%)   NaN    12.5

       Flag_Total    Male Flag_Male  Female Flag_Female
0             NaN  3140.0       NaN  3300.0         NaN
1             NaN  3105.0       NaN  3255.0         NaN
2             NaN   940.0       NaN   955.0         NaN
3             NaN  2165.0       NaN  2300.0         NaN
4             NaN    35.0       NaN    50.0         NaN
...           ...     ...       ...     ...         ...
866875        NaN     8.2       NaN     8.7         NaN
866876        NaN    11.1       NaN    15.7         NaN
866877        NaN     6.4       NaN    11.4         NaN
866878        NaN     6.4       NaN     6.3         NaN
866879        NaN    12.6       NaN    12.5         NaN

[866880 rows x 15 columns]

In [8]:
# Loop through questions and save the ones we want to keep

conditions_2011 = [
    'Population in 2011',
    '2006 to 2011 population change (%)',
    'Total private dwellings',
    'Private dwellings occupied by usual residents',
    'Population density per square kilometre',
    'Total population by age groups',
    '0 to 4 years', '5 to 9 years', '10 to 14 years',
    '15 to 19 years',
    '20 to 24 years',
    '25 to 29 years',
    '30 to 34 years',
    '35 to 39 years',
    '40 to 44 years',
    '45 to 49 years',
    '50 to 54 years',
    '55 to 59 years',
    '60 to 64 years',
    '65 to 69 years', '70 to 74 years', '75 to 79 years', '80 to 84 years', '85 years and over',
    'Median age of the population',
    'Total number of occupied private dwellings by structural type of dwelling',
    'Single-detached house',
    'Apartment, building that has five or more storeys',
    'Semi-detached house',
    'Row house',
    'Apartment, duplex',
    'Apartment, building that has fewer than five storeys',
    'Other single-attached house',
    'Movable dwelling',
    'Average number of persons in private households',
    'Total population 15 years and over by marital status',
    'Married or living with a common-law partner',
    'Not married and not living with a common-law partner',
    'Median total income ($)',
    'Median after-tax income ($)',
    'Prevalence of low income in 2010 based on after-tax low-income measure (%)',
    'Total population in private households by citizenship',
    'Canadian citizens',
    'Not Canadian citizens',
    'Total population in private households by immigrant status and period of immigration',
    'Non-immigrants',
    'Immigrants',
    'Non-permanent residents',
    'Total population in private households by visible minority',
    'Total visible minority population',
    'Not a visible minority',
    'Total number of private households by tenure',
    'Owner',
    'Renter',
    'Band housing',
    'Total number of private households by condominium status',
    'Part of a condominium development',
    'Not part of a condominium development',
    'Total number of private households by housing suitability',
    'Suitable',
    'Not suitable',
    'Total number of occupied private dwellings by condition of dwelling',
    'Only regular maintenance or minor repairs needed',
    'Major repairs needed',
    'Average number of rooms per dwelling',
    '% of tenant households in subsidized housing',
    'Median monthly shelter costs for owned dwellings ($)',
    'Average monthly shelter costs for owned dwellings ($)',
    'Median value of dwellings ($)',
    'Average value of dwellings ($)',
    'Median monthly shelter costs for rented dwellings ($)',
    'Median monthly shelter costs for rented dwellings ($)',
    'Total population aged 15 years and over by highest certificate, diploma or degree',
    'No certificate, diploma or degree',
    'High school diploma or equivalent',
    'Postsecondary certificate, diploma or degree',
    'Apprenticeship or trades certificate or diploma',
    'College, CEGEP or other non-university certificate or diploma',
    'University certificate or diploma below bachelor level',
    'University certificate, diploma or degree at bachelor level or above',
    'Total population aged 15 years and over by location of study compared with province or territory of residence',
    'Location of study inside Canada',
    'Same as province or territory of residence',
    'Another province or territory',
    'Location of study outside Canada',
    'Total population aged 15 years and over by labour force status',
    'In the labour force',
    'Not in the labour force',
    'Total employed population aged 15 years and over with a usual place of work or no fixed workplace address by mode of transportation',
    'Car, truck or van - as a driver',
    'Car, truck or van - as a passenger',
    'Public transit',
    'Walked',
    'Bicycle',
    'Other methods',
    'Median commuting duration',
    'Total - Mobility status 1 year ago',
    'Non-movers',
    'Movers'
]

# remove values in df with leading spaces
census_2011_1['Characteristic'] = census_2011_1['Characteristic'].str.strip()
census_2011_2['Characteristic'] = census_2011_2['Characteristic'].str.strip()

# Filtering the DataFrame to get rows that match the conditions
new_df_1 = census_2011_1.loc[census_2011_1['Characteristic'].isin(conditions_2011)]
new_df_2 = census_2011_2.loc[census_2011_2['Characteristic'].isin(conditions_2011)]

# Concatenate the two DataFrames
new_df = pd.concat([new_df_1, new_df_2])

'''
# Find values in conditions that are not in 'CHARACTERISTIC_NAME' in new_df
missing_conditions = [condition for condition in conditions_2011 if condition not in new_df['Characteristic'].values]

# check if condition list is similar to other years
if (len(conditions_2011) == len(conditions_2016)): # missing "average age of population", added more years for ages, missing 1 low-income measure, missing commuting times
  print("Same number of variables in 2011 and 2016")
else:
  print("Different number of variables in 2011 and 2016")

# Print the missing values
print("\nConditions not found in 'Characteristic':")
if len(missing_conditions) == 0:
    print("No missing values found.")
else:
  for condition in missing_conditions:
    print(condition)
'''
print(new_df.columns)
print(new_df.head())

Index(['Unnamed: 0', 'Geo_Code', 'Prov_Name', 'CMACA_Name', 'CT_Name', 'Topic',
       'Characteristic', 'Note', 'Total', 'Flag_Total', 'Male', 'Flag_Male',
       'Female', 'Flag_female', 'CMA_CA_Name', 'GNR', 'Flag_Female'],
      dtype='object')
   Unnamed: 0    Geo_Code Prov_Name CMACA_Name  CT_Name  \
0      294056  4620725.07    Quebec   Montréal   725.07
2      294058  4620725.07    Quebec   Montréal   725.07
3      294059  4620725.07    Quebec   Montréal   725.07
4      294060  4620725.07    Quebec   Montréal   725.07
5      294061  4620725.07    Quebec   Montréal   725.07

                            Topic  \
0  Population and dwelling counts
2  Population and dwelling counts
3  Population and dwelling counts
4  Population and dwelling counts
5  Population and dwelling counts

                                  Characteristic  Note   Total Flag_Total  \
0                             Population in 2011   1.0  6440.0        NaN
2             2006 to 2011 population change (%)   NaN     1.6        NaN
3                        Total private dwellings   2.0  2168.0        NaN
4  Private dwellings occupied by usual residents   3.0  2159.0        NaN
5        Population density per square kilometre   NaN  4481.2        NaN

   Male Flag_Male  Female Flag_female CMA_CA_Name  GNR Flag_Female
0   NaN       ...     NaN         ...         NaN  NaN         NaN
2   NaN       ...     NaN         ...         NaN  NaN         NaN
3   NaN       ...     NaN         ...         NaN  NaN         NaN
4   NaN       ...     NaN         ...         NaN  NaN         NaN
5   NaN       ...     NaN         ...         NaN  NaN         NaN

In [9]:
# drop unecessary columns

new_df = new_df.drop('Unnamed: 0', axis=1)
new_df = new_df.drop('Prov_Name', axis=1)
new_df = new_df.drop('CMACA_Name', axis=1)
new_df = new_df.drop('Topic', axis=1)
new_df = new_df.drop('Note', axis=1)
new_df = new_df.drop('CT_Name', axis=1)
new_df = new_df.drop('Flag_Total', axis=1)
new_df = new_df.drop('Male', axis=1)
new_df = new_df.drop('Female', axis=1)
new_df = new_df.drop('Flag_Male', axis=1)
new_df = new_df.drop('Flag_Female', axis=1)
new_df = new_df.drop('Flag_female', axis=1)
new_df = new_df.drop('CMA_CA_Name', axis=1)
new_df = new_df.drop('GNR', axis=1)


print(new_df.head())

     Geo_Code                                 Characteristic   Total
0  4620725.07                             Population in 2011  6440.0
2  4620725.07             2006 to 2011 population change (%)     1.6
3  4620725.07                        Total private dwellings  2168.0
4  4620725.07  Private dwellings occupied by usual residents  2159.0
5  4620725.07        Population density per square kilometre  4481.2

In [10]:
# loop over rows, make a dict
# items = {'region':{}}
items = {}
for i in range(len(new_df)):
  # if i > 10:
  #   break
  # print(new_df.iloc[i]['GEO_NAME'])
  outer_key = new_df.iloc[i]['Geo_Code']
  if outer_key in items:
    inner_key = new_df.iloc[i]['Characteristic'] + ' 2011'
    items[outer_key][inner_key] = new_df.iloc[i]['Total']
  else:
    items[outer_key] = {'ctuid': new_df.iloc[i]['Geo_Code']}
    inner_key = new_df.iloc[i]['Characteristic'] + ' 2011'
    items[outer_key][inner_key] = new_df.iloc[i]['Total']
print(items.keys())

dict_keys([4620725.07, 4620725.08, 4620652.04, 4620887.05, 4620887.06, 4620887.07, 4620688.03, 4620688.04, 4620001.0, 4620002.0, 4620003.0, 4620004.0, 4620005.0, 4620006.0, 4620007.0, 4620008.0, 4620009.0, 4620010.0, 4620011.0, 4620013.0, 4620015.0, 4620016.0, 4620017.0, 4620018.0, 4620019.0, 4620021.0, 4620022.0, 4620023.0, 4620024.0, 4620025.0, 4620026.0, 4620027.0, 4620028.0, 4620029.0, 4620030.0, 4620031.0, 4620032.0, 4620033.0, 4620034.0, 4620035.0, 4620036.0, 4620037.0, 4620038.0, 4620039.0, 4620040.0, 4620041.0, 4620042.0, 4620043.0, 4620044.0, 4620045.0, 4620046.0, 4620047.0, 4620048.0, 4620049.0, 4620050.0, 4620051.0, 4620052.0, 4620053.0, 4620054.0, 4620056.0, 4620057.0, 4620058.0, 4620059.0, 4620060.0, 4620061.0, 4620062.0, 4620063.0, 4620064.0, 4620067.0, 4620068.0, 4620069.0, 4620070.0, 4620071.0, 4620072.0, 4620073.0, 4620074.0, 4620075.0, 4620076.0, 4620077.0, 4620078.0, 4620079.0, 4620080.0, 4620081.0, 4620082.0, 4620083.0, 4620084.0, 4620085.0, 4620086.0, 4620087.0, 4620088.0, 4620089.0, 4620090.0, 4620091.0, 4620092.0, 4620093.0, 4620095.0, 4620096.0, 4620098.0, 4620099.0, 4620102.0, 4620103.0, 4620104.0, 4620105.0, 4620106.0, 4620107.0, 4620108.0, 4620109.0, 4620110.0, 4620111.0, 4620113.0, 4620114.0, 4620116.0, 4620117.0, 4620118.0, 4620119.0, 4620121.0, 4620122.0, 4620123.0, 4620124.0, 4620125.0, 4620126.0, 4620128.0, 4620130.0, 4620131.0, 4620132.0, 4620133.0, 4620134.0, 4620135.0, 4620136.0, 4620137.0, 4620138.0, 4620139.0, 4620140.0, 4620141.0, 4620142.0, 4620143.0, 4620144.0, 4620145.0, 4620146.0, 4620147.0, 4620148.0, 4620149.0, 4620150.0, 4620151.0, 4620152.0, 4620153.0, 4620154.0, 4620155.0, 4620156.0, 4620157.0, 4620158.0, 4620159.0, 4620160.0, 4620161.0, 4620162.0, 4620163.0, 4620164.0, 4620165.0, 4620166.0, 4620167.0, 4620168.0, 4620169.0, 4620170.0, 4620171.0, 4620172.0, 4620173.0, 4620174.0, 4620175.0, 4620176.0, 4620177.0, 4620178.0, 4620179.0, 4620180.0, 4620181.0, 4620182.0, 4620183.0, 4620184.0, 4620185.0, 4620186.0, 4620189.0, 4620191.0, 4620192.0, 4620193.0, 4620194.0, 4620196.0, 4620197.0, 4620198.0, 4620199.0, 4620200.0, 4620201.0, 4620202.0, 4620203.0, 4620204.0, 4620205.0, 4620206.0, 4620207.0, 4620208.0, 4620209.0, 4620210.0, 4620211.0, 4620212.0, 4620213.0, 4620214.0, 4620215.0, 4620216.0, 4620217.0, 4620218.0, 4620219.0, 4620220.0, 4620221.0, 4620222.0, 4620224.0, 4620225.0, 4620226.0, 4620227.0, 4620228.0, 4620229.0, 4620230.0, 4620231.0, 4620232.0, 4620233.0, 4620234.0, 4620235.0, 4620236.0, 4620237.0, 4620238.0, 4620239.0, 4620240.0, 4620241.0, 4620242.0, 4620243.0, 4620244.0, 4620245.0, 4620247.0, 4620249.0, 4620250.0, 4620252.0, 4620253.0, 4620254.0, 4620256.0, 4620257.0, 4620258.0, 4620259.0, 4620260.0, 4620261.0, 4620262.0, 4620263.0, 4620265.0, 4620266.0, 4620267.0, 4620269.0, 4620270.0, 4620271.0, 4620272.0, 4620273.0, 4620274.0, 4620275.0, 4620276.0, 4620277.0, 4620278.0, 4620279.0, 4620280.0, 4620281.0, 4620282.0, 4620284.0, 4620285.0, 4620286.0, 4620288.0, 4620300.0, 4620301.0, 4620302.0, 4620303.0, 4620304.0, 4620305.0, 4620306.0, 4620307.0, 4620308.0, 4620309.0, 4620310.0, 4620311.0, 4620312.0, 4620313.0, 4620314.0, 4620315.0, 4620316.0, 4620320.0, 4620321.0, 4620323.0, 4620327.0, 4620329.0, 4620330.0, 4620340.0, 4620350.0, 4620351.0, 4620352.0, 4620353.0, 4620354.0, 4620355.0, 4620356.0, 4620360.0, 4620361.0, 4620362.0, 4620363.0, 4620364.0, 4620365.0, 4620366.0, 4620367.0, 4620370.0, 4620380.0, 4620381.0, 4620385.0, 4620390.0, 4620391.0, 4620392.0, 4620393.0, 4620394.0, 4620396.0, 4620397.0, 4620400.0, 4620401.0, 4620402.0, 4620403.0, 4620404.0, 4620412.0, 4620418.0, 4620419.0, 4620420.0, 4620430.0, 4620431.0, 4620432.0, 4620433.0, 4620440.0, 4620450.0, 4620451.0, 4620452.0, 4620460.0, 4620461.0, 4620480.0, 4620490.0, 4620491.0, 4620500.0, 4620652.06, 4620652.07, 4620523.0, 4620530.0, 4620540.0, 4620570.0, 4620583.0, 4620584.0, 4620592.0, 4620511.01, 4620511.02, 4620830.03, 4620830.04, 4620612.0, 4620613.0, 4620614.0, 4620615.0, 4620616.0, 4620618.0, 4620619.0, 4620626.0, 4620627.0, 4620629.0, 4620631.0, 4620633.0, 4620634.0, 4620635.0, 4620636.0, 4620639.0, 4620640.0, 4620642.0, 4620644.0, 4620645.0, 4620648.0, 4620653.0, 4620654.0, 4620662.0, 4620675.0, 4620683.0, 4620706.0, 4620707.0, 4620729.0, 4620731.0, 4620801.0, 4620802.0, 4620805.0, 4620829.0, 4620832.0, 4620851.0, 4620755.01, 4620755.02, 4620856.0, 4620859.0, 4620861.0, 4620862.0, 4620864.0, 4620865.0, 4620866.0, 4620867.0, 4620869.0, 4620872.0, 4620874.0, 4620875.0, 4620878.0, 4620880.0, 4620882.0, 4620883.0, 4620885.0, 4620900.0, 4620902.0, 4621000.0, 4621001.0, 4621002.0, 4621003.0, 4621004.0, 4621005.0, 4620704.08, 4620704.09, 4620325.05, 4620325.06, 4620593.01, 4620593.02, 4620415.05, 4620415.06, 4620100.01, 4620100.02, 4620291.03, 4620291.04, 4620413.01, 4620413.02, 4620317.03, 4620317.04, 4620187.03, 4620187.04, 4620929.01, 4620929.02, 4620855.03, 4620855.04, 4620677.09, 4620677.1, 4620777.01, 4620777.02, 4620643.01, 4620643.02, 4620643.03, 4620652.08, 4620652.09, 4620656.03, 4620656.04, 4620659.08, 4620659.09, 4620661.03, 4620661.04, 4620804.01, 4620804.02, 4620701.01, 4620701.02, 4620758.03, 4620758.04, 4620758.05, 4620758.06, 4620740.01, 4620740.02, 4620750.04, 4620750.05, 4620903.11, 4620903.12, 4620858.04, 4620858.05, 4620876.06, 4620876.07, 4620684.08, 4620684.09, 4620681.0, 4620833.0, 4620012.01, 4620012.02, 4620097.01, 4620097.02, 4620283.01, 4620283.02, 4620322.02, 4620325.01, 4620325.02, 4620325.03, 4620326.01, 4620326.02, 4620328.0, 4620395.01, 4620395.02, 4620395.03, 4620520.02, 4620590.01, 4620590.02, 4620591.01, 4620591.02, 4620603.01, 4620603.02, 4620604.01, 4620604.02, 4620605.01, 4620605.02, 4620610.01, 4620610.02, 4620610.03, 4620610.04, 4620611.01, 4620611.02, 4620617.01, 4620617.02, 4620630.01, 4620630.02, 4620632.01, 4620632.02, 4620638.01, 4620638.02, 4620638.03, 4620646.01, 4620646.02, 4620646.03, 4620650.01, 4620650.02, 4620650.03, 4620652.01, 4620700.01, 4620756.02, 4620757.0, 4620775.0, 4620825.01, 4620825.02, 4620825.03, 4620825.04, 4620827.02, 4620852.01, 4620852.02, 4620857.01, 4620857.02, 4620868.01, 4620868.02, 4620879.01, 4620879.02, 4620881.01, 4620881.02, 4620889.01, 4620889.02, 4620889.03, 4620684.1, 4620684.11, 4620888.01, 4620888.02, 4620888.03, 4620687.09, 4620687.1, 4620065.01, 4620065.02, 4620066.01, 4620066.02, 4620115.01, 4620115.02, 4620188.01, 4620188.02, 4620195.01, 4620195.02, 4620223.01, 4620223.02, 4620251.01, 4620251.02, 4620290.01, 4620290.02, 4620324.01, 4620324.02, 4620382.01, 4620382.02, 4620462.01, 4620462.02, 4620470.01, 4620512.02, 4620514.01, 4620514.02, 4620521.01, 4620582.01, 4620582.02, 4620600.01, 4620600.02, 4620600.03, 4620601.01, 4620601.02, 4620602.01, 4620602.02, 4620603.03, 4620604.03, 4620604.04, 4620604.05, 4620605.03, 4620605.04, 4620605.05, 4620610.05, 4620610.06, 4620628.01, 4620628.02, 4620638.04, 4620641.01, 4620641.02, 4620657.01, 4620657.02, 4620658.01, 4620658.02, 4620658.03, 4620661.01, 4620676.01, 4620676.02, 4620676.03, 4620676.04, 4620687.01, 4620704.01, 4620825.05, 4620826.02, 4620855.01, 4620858.01, 4620858.02, 4620860.01, 4620860.02, 4620863.01, 4620863.02, 4620870.01, 4620870.02, 4620871.01, 4620871.02, 4620873.01, 4620873.02, 4620876.01, 4620884.01, 4620884.02, 4620903.01, 4620101.01, 4620101.02, 4620129.01, 4620129.02, 4620195.03, 4620287.01, 4620287.02, 4620290.03, 4620290.04, 4620326.03, 4620383.01, 4620383.02, 4620410.01, 4620410.02, 4620522.01, 4620522.02, 4620594.01, 4620594.02, 4620610.07, 4620632.03, 4620647.01, 4620647.02, 4620649.01, 4620649.02, 4620655.01, 4620655.02, 4620677.01, 4620677.02, 4620685.02, 4620687.03, 4620703.02, 4620726.01, 4620751.01, 4620751.02, 4620756.03, 4620850.01, 4620853.02, 4620854.01, 4620854.02, 4620901.01, 4620901.02, 4620901.03, 4620930.02, 4620733.0, 4620776.0, 4620834.0, 4620659.1, 4620659.11, 4620828.05, 4620828.06, 4620120.01, 4620120.02, 4620710.05, 4620710.06, 4620826.13, 4620826.14, 4620734.03, 4620734.04, 4620734.05, 4620710.07, 4620710.08, 4620710.09, 4620710.1, 4620710.11, 4620831.08, 4620831.09, 4620094.01, 4620094.02, 4620014.01, 4620014.02, 4620112.01, 4620112.02, 4620055.01, 4620055.02, 4620190.01, 4620190.02, 4620290.05, 4620187.01, 4620127.01, 4620127.02, 4620290.06, 4620290.07, 4620290.08, 4620581.01, 4620581.02, 4620290.09, 4620580.01, 4620580.02, 4620585.01, 4620585.02, 4620264.01, 4620264.02, 4620268.01, 4620268.02, 4620268.03, 4620677.05, 4620702.01, 4620702.02, 4620687.04, 4620806.01, 4620806.02, 4620682.02, 4620904.02, 4620637.01, 4620637.02, 4620625.01, 4620625.02, 4620656.01, 4620632.04, 4620657.03, 4620660.01, 4620660.02, 4620660.03, 4620550.02, 4620470.03, 4620453.01, 4620453.02, 4620317.02, 4620410.03, 4620417.01, 4620417.02, 4620580.03, 4620690.0, 4620691.0, 4620692.0, 4620693.0, 4620694.0, 4620760.0, 4620781.0, 4620782.0, 4620783.0, 4620784.0, 4620785.0, 4620786.0, 4620787.0, 4620788.0, 4620789.0, 4620790.0, 4620791.0, 4620792.0, 4620780.0, 4620322.03, 4620322.04, 4620470.04, 4620470.05, 4620550.03, 4620550.04, 4620688.02, 4620703.03, 4620703.04, 4620710.03, 4620730.01, 4620730.02, 4620732.01, 4620732.02, 4620734.01, 4620735.01, 4620735.02, 4620750.01, 4620750.02, 4620756.04, 4620756.05, 4620853.03, 4620853.04, 4620857.06, 4620857.07, 4620857.08, 4620857.09, 4620857.1, 4620857.11, 4620857.12, 4620887.03, 4620887.04, 4620926.01, 4620926.02, 4620416.01, 4620416.02, 4620415.03, 4620415.04, 4620708.01, 4620708.02, 4620291.01, 4620421.01, 4620421.02, 4620651.01, 4620651.02, 4620659.04, 4620659.05, 4620659.06, 4620677.06, 4620677.07, 4620677.08, 4620705.01, 4620705.02, 4620725.03, 4620725.04, 4620725.06, 4620726.03, 4620726.04, 4620727.01, 4620727.02, 4620830.01, 4620930.03, 4620930.04, 4620512.03, 4620512.04, 4620513.01, 4620513.02, 4620515.01, 4620515.02, 4620515.03, 4620515.04, 4620520.03, 4620520.04, 4620682.03, 4620682.04, 4620682.05, 4620682.06, 4620684.03, 4620684.05, 4620685.03, 4620685.04, 4620685.05, 4620685.06, 4620686.01, 4620686.02, 4620686.03, 4620687.06, 4620687.07, 4620689.01, 4620689.02, 4620689.03, 4620689.04, 4620700.03, 4620700.04, 4620704.04, 4620704.05, 4620704.06, 4620709.01, 4620709.02, 4620728.01, 4620728.02, 4620728.03, 4620800.01, 4620800.02, 4620826.05, 4620826.06, 4620826.07, 4620826.08, 4620826.09, 4620826.1, 4620826.11, 4620828.03, 4620828.04, 4620877.01, 4620877.02, 4620886.01, 4620886.02, 4620886.03, 4620903.04, 4620903.05, 4620903.07, 4620903.08, 4620903.09, 4620903.1, 4620904.03, 4620904.04, 4620904.05, 4620904.06, 4620521.04, 4620521.05, 4620521.06, 4620521.07, 4620807.01, 4620807.02, 4620827.03, 4620827.04, 4620831.03, 4620831.04, 4620831.05, 4620850.03, 4620850.04, 4620850.05, 4620876.04, 4620876.05, 4620831.07])

In [11]:
# Convert the dictionary of dictionaries into a DataFrame
census_2011 = pd.DataFrame.from_dict(items, orient='index')

# Write the DataFrame to a CSV file
census_2011.to_csv('/content/drive/MyDrive/GentrificAItion/Montreal_data_from_census/Cleaned_Census_Data/2011_emilie_v1.csv')

print(census_2011)

                 ctuid  Population in 2011 2011  \
4620725.07  4620725.07                   6440.0
4620725.08  4620725.08                   8220.0
4620652.04  4620652.04                   4203.0
4620887.05  4620887.05                   4855.0
4620887.06  4620887.06                   4613.0
...                ...                      ...
4620850.04  4620850.04                   3886.0
4620850.05  4620850.05                   3530.0
4620876.04  4620876.04                   6492.0
4620876.05  4620876.05                   7541.0
4620831.07  4620831.07                   2782.0

            2006 to 2011 population change (%) 2011  \
4620725.07                                      1.6
4620725.08                                     42.8
4620652.04                                     -1.0
4620887.05                                     -2.0
4620887.06                                     -0.2
...                                             ...
4620850.04                                     11.3
4620850.05                                      9.9
4620876.04                                      5.2
4620876.05                                     14.7
4620831.07                                      5.1

            Total private dwellings 2011  \
4620725.07                        2168.0
4620725.08                        3130.0
4620652.04                        1546.0
4620887.05                        1893.0
4620887.06                        1697.0
...                                  ...
4620850.04                        1297.0
4620850.05                        1309.0
4620876.04                        2298.0
4620876.05                        3357.0
4620831.07                        1150.0

            Private dwellings occupied by usual residents 2011  \
4620725.07                                             2159.0
4620725.08                                             3087.0
4620652.04                                             1528.0
4620887.05                                             1879.0
4620887.06                                             1685.0
...                                                       ...
4620850.04                                             1282.0
4620850.05                                             1289.0
4620876.04                                             2263.0
4620876.05                                             3262.0
4620831.07                                             1104.0

            Population density per square kilometre 2011  \
4620725.07                                        4481.2
4620725.08                                        1536.9
4620652.04                                        3348.2
4620887.05                                        2442.3
4620887.06                                        2569.3
...                                                  ...
4620850.04                                         464.6
4620850.05                                         457.1
4620876.04                                        2869.4
4620876.05                                        1577.1
4620831.07                                          36.3

            Total population by age groups 2011  0 to 4 years 2011  \
4620725.07                               6445.0              495.0
4620725.08                               8220.0              570.0
4620652.04                               4205.0              210.0
4620887.05                               4855.0              265.0
4620887.06                               4610.0              245.0
...                                         ...                ...
4620850.04                               3885.0              375.0
4620850.05                               3525.0              290.0
4620876.04                               6490.0              420.0
4620876.05                               7545.0              410.0
4620831.07                               2785.0              150.0

            5 to 9 years 2011  10 to 14 years 2011  ...  Not suitable 2011  \
4620725.07              495.0                555.0  ...               65.0
4620725.08              570.0                545.0  ...               75.0
4620652.04              245.0                265.0  ...               70.0
4620887.05              235.0                270.0  ...               50.0
4620887.06              370.0                375.0  ...               50.0
...                       ...                  ...  ...                ...
4620850.04              335.0                315.0  ...                0.0
4620850.05              265.0                280.0  ...               55.0
4620876.04              450.0                490.0  ...               85.0
4620876.05              295.0                355.0  ...              100.0
4620831.07              140.0                130.0  ...                NaN

            Median monthly shelter costs for owned dwellings ($) 2011  \
4620725.07                                             1133.0
4620725.08                                             1089.0
4620652.04                                             1009.0
4620887.05                                              824.0
4620887.06                                             1122.0
...                                                       ...
4620850.04                                             1305.0
4620850.05                                             1136.0
4620876.04                                             1100.0
4620876.05                                             1002.0
4620831.07                                                NaN

            Average monthly shelter costs for owned dwellings ($) 2011  \
4620725.07                                             1086.0
4620725.08                                             1132.0
4620652.04                                             1059.0
4620887.05                                              965.0
4620887.06                                             1240.0
...                                                       ...
4620850.04                                             1230.0
4620850.05                                             1119.0
4620876.04                                             1092.0
4620876.05                                             1036.0
4620831.07                                                NaN

            Median value of dwellings ($) 2011  \
4620725.07                            229838.0
4620725.08                            224964.0
4620652.04                            259979.0
4620887.05                            299566.0
4620887.06                            348407.0
...                                        ...
4620850.04                            255073.0
4620850.05                            229725.0
4620876.04                            299065.0
4620876.05                            249986.0
4620831.07                                 NaN

            Average value of dwellings ($) 2011  \
4620725.07                             243422.0
4620725.08                             251447.0
4620652.04                             289383.0
4620887.05                             311835.0
4620887.06                             363921.0
...                                         ...
4620850.04                             275950.0
4620850.05                             247148.0
4620876.04                             294038.0
4620876.05                             271959.0
4620831.07                                  NaN

            % of tenant households in subsidized housing 2011  \
4620725.07                                                0.0
4620725.08                                                0.0
4620652.04                                                0.0
4620887.05                                                0.0
4620887.06                                                0.0
...                                                       ...
4620850.04                                                0.0
4620850.05                                                0.0
4620876.04                                               56.7
4620876.05                                                5.9
4620831.07                                                NaN

            Median monthly shelter costs for rented dwellings ($) 2011  \
4620725.07                                              934.0
4620725.08                                              838.0
4620652.04                                              733.0
4620887.05                                              751.0
4620887.06                                              787.0
...                                                       ...
4620850.04                                              648.0
4620850.05                                              740.0
4620876.04                                              507.0
4620876.05                                              694.0
4620831.07                                                NaN

            Median after-tax income ($) 2011  Median total income ($) 2011  \
4620725.07                           42178.0                       52711.0
4620725.08                           33001.0                       37856.0
4620652.04                           26272.0                       30240.0
4620887.05                           38668.0                       47178.0
4620887.06                           56065.0                       71727.0
...                                      ...                           ...
4620850.04                           29013.0                       33961.0
4620850.05                           27204.0                       29586.0
4620876.04                           42768.0                       50283.0
4620876.05                           33024.0                       39899.0
4620831.07                               NaN                           NaN

            Prevalence of low income in 2010 based on after-tax low-income measure (%) 2011
4620725.07                                                3.4
4620725.08                                                8.3
4620652.04                                               11.7
4620887.05                                                4.5
4620887.06                                                4.7
...                                                       ...
4620850.04                                                4.5
4620850.05                                                8.9
4620876.04                                               10.8
4620876.05                                                8.5
4620831.07                                                NaN

[921 rows x 99 columns]

# 2006 Data Cleaning

In [ ]:
# Select only the columns you want to keep
census_2006_filtered = census_2006[columns_to_keep]
# Display the first few rows of the filtered DataFrame
print(census_2006_filtered.head())

# 2001 Data Cleaning

In [ ]:
import pandas as pd

census_2001 = pd.read_csv('/content/drive/MyDrive/GentrificAItion/Montreal_data_from_census/2001_montreal_data.csv')

# print(census_2001)
census_2001.columns

Index(['GeoUID', 'Type', 'Region Name', 'Area (sq km)', 'Population ',
       'Dwellings ', 'Households ', 'v_CA01_2: Population, 2001',
       'v_CA01_3: Population percentage change, 1996-2001',
       'v_CA01_4: Land area in square kilometres, 2001',
       ...
       'v_CA01_1611: Other',
       'v_CA01_1613: Total - Unattached individuals 15 years and over',
       'v_CA01_1617: Total - Population in private households',
       'v_CA01_1621: Household income in 2000 of all private households',
       'v_CA01_1633: Average household income $',
       'v_CA01_1634: Median household income $',
       'v_CA01_1635: Standard error of average household income $',
       'v_CA01_1667: Average gross rent $',
       'v_CA01_1670: Owner households in non-farm, non-reserve private dwellings',
       'v_CA01_1674: Average value of dwelling $'],
      dtype='object', length=169)

In [ ]:
# Rename the columns
census_2001.columns = census_2001.columns.str.replace(r'v_CA01_\d+: ', '', regex=True)
print(list(census_2001.columns))
import pprint
pprint.pprint(list(census_2001.columns))

['GeoUID', 'Type', 'Region Name', 'Area (sq km)', 'Population ', 'Dwellings ', 'Households ', 'Population, 2001', 'Population percentage change, 1996-2001', 'Land area in square kilometres, 2001', 'Total population 15 years and over by legal marital status', 'Never legally married (single)', 'Legally married (and not separated)', 'Separated, but still legally married', 'Divorced', 'Widowed', 'Total population 15 years and over by common-law status', 'Total population by sex and age groups', 'Male, total', '0-4', '5-9', '10-14', '15-19', '20-24', '25-29', '30-34', '35-39', '40-44', '45-49', '50-54', '55-59', '60-64', '65-69', '70-74', '75-79', '80-84', '85+', 'Female, total', '0-4', '5-9', '10-14', '15-19', '20-24', '25-29', '30-34', '35-39', '40-44', '45-49', '50-54', '55-59', '60-64', '65-69', '70-74', '75-79', '80-84', '85+', 'Not in a common-law relationship', 'In a common-law relationship', 'Average number of rooms per dwelling', 'Average number of bedrooms per dwelling', 'Owned', 'Rented', 'Total number of census families in private households', 'Total couple families by family structure and number of children', 'Married couples', 'Common-law couples', 'Total number of children at home', 'Average number of children at home per census family', 'Average number of persons per census family', 'Total number of persons in private households', 'Total number of private households by household size', 'Number of persons in private households', 'Average number of persons in private households', 'Band housing', 'Regular maintenance only', 'Minor repairs', 'Major repairs', 'Period of construction, before 1946', 'Period of construction, 1946-1960', 'Period of construction, 1961-1970', 'Period of construction, 1971-1980', 'Period of construction, 1981-1990', 'Period of construction, 1991-1995', 'Period of construction, 1996-2001', 'Total number of occupied private dwellings by structural type of dwelling', 'Single-detached house', 'Semi-detached house', 'Row house', 'Apartment, detached duplex', 'Apartment, building that has five or more storeys', 'Apartment, building that has fewer than five storeys', 'Other single-attached house', 'Movable dwelling', 'Total population 1 year and over by mobility status 1 year ago', 'Non-movers', 'Movers', 'Non-migrants', 'Migrants', 'Internal migrants', 'External migrants', 'Total population by citizenship', 'Canadian citizenship', 'Citizenship other than Canadian', 'Total population by immigrant status and place of birth', 'Non-immigrant population', 'Born in province of residence', 'Born outside province of residence', 'Total immigrants by selected places of birth', 'Non-permanent residents', 'Total population by visible minority groups', 'Total visible minority population', 'All others', 'Population 15 years and over by labour force activity', 'Participation rate', 'Employment rate', 'Unemployment rate', 'Total employed labour force 15 years and over by place of work status', 'Males', 'Females', 'Total employed labour force 15 years and over by mode of transportation', 'Males with usual place of work or no fixed workplace address', 'Car, truck, van, as driver', 'Car, truck, van, as passenger', 'Public transit', 'Walked', 'Bicycle', 'Motorcycle', 'Taxicab', 'Other method', 'Females with usual place of work or no fixed workplace address', 'Car, truck, van, as driver', 'Car, truck, van, as passenger', 'Public transit', 'Walked', 'Bicycle', 'Motorcycle', 'Taxicab', 'Other method', 'Total population 15 to 24 years by school attendance', 'Not attending school', 'Attending school full time', 'Attending school part time', 'Total population of males with postsecondary qualifications by major field of study', 'Total population of females with postsecondary qualifications by major field of study', 'Total population 20 years and over by highest level of schooling', 'Less than grade 9', 'Grades 9 to 13', 'Trades certificate or diploma', 'College', 'Without certificate or diploma', 'With certificate or diploma', 'University', 'Without degree', "With bachelor's degree or higher", 'Total income in 2000 of population 15 years and over', 'Average income $', 'Median income $', 'Total - Economic families', 'Low income', 'Other', 'Total - Unattached individuals 15 years and over', 'Total - Population in private households', 'Household income in 2000 of all private households', 'Average household income $', 'Median household income $', 'Standard error of average household income $', 'Average gross rent $', 'Owner households in non-farm, non-reserve private dwellings', 'Average value of dwelling $']
['GeoUID',
 'Type',
 'Region Name',
 'Area (sq km)',
 'Population ',
 'Dwellings ',
 'Households ',
 'Population, 2001',
 'Population percentage change, 1996-2001',
 'Land area in square kilometres, 2001',
 'Total population 15 years and over by legal marital status',
 'Never legally married (single)',
 'Legally married (and not separated)',
 'Separated, but still legally married',
 'Divorced',
 'Widowed',
 'Total population 15 years and over by common-law status',
 'Total population by sex and age groups',
 'Male, total',
 '0-4',
 '5-9',
 '10-14',
 '15-19',
 '20-24',
 '25-29',
 '30-34',
 '35-39',
 '40-44',
 '45-49',
 '50-54',
 '55-59',
 '60-64',
 '65-69',
 '70-74',
 '75-79',
 '80-84',
 '85+',
 'Female, total',
 '0-4',
 '5-9',
 '10-14',
 '15-19',
 '20-24',
 '25-29',
 '30-34',
 '35-39',
 '40-44',
 '45-49',
 '50-54',
 '55-59',
 '60-64',
 '65-69',
 '70-74',
 '75-79',
 '80-84',
 '85+',
 'Not in a common-law relationship',
 'In a common-law relationship',
 'Average number of rooms per dwelling',
 'Average number of bedrooms per dwelling',
 'Owned',
 'Rented',
 'Total number of census families in private households',
 'Total couple families by family structure and number of children',
 'Married couples',
 'Common-law couples',
 'Total number of children at home',
 'Average number of children at home per census family',
 'Average number of persons per census family',
 'Total number of persons in private households',
 'Total number of private households by household size',
 'Number of persons in private households',
 'Average number of persons in private households',
 'Band housing',
 'Regular maintenance only',
 'Minor repairs',
 'Major repairs',
 'Period of construction, before 1946',
 'Period of construction, 1946-1960',
 'Period of construction, 1961-1970',
 'Period of construction, 1971-1980',
 'Period of construction, 1981-1990',
 'Period of construction, 1991-1995',
 'Period of construction, 1996-2001',
 'Total number of occupied private dwellings by structural type of dwelling',
 'Single-detached house',
 'Semi-detached house',
 'Row house',
 'Apartment, detached duplex',
 'Apartment, building that has five or more storeys',
 'Apartment, building that has fewer than five storeys',
 'Other single-attached house',
 'Movable dwelling',
 'Total population 1 year and over by mobility status 1 year ago',
 'Non-movers',
 'Movers',
 'Non-migrants',
 'Migrants',
 'Internal migrants',
 'External migrants',
 'Total population by citizenship',
 'Canadian citizenship',
 'Citizenship other than Canadian',
 'Total population by immigrant status and place of birth',
 'Non-immigrant population',
 'Born in province of residence',
 'Born outside province of residence',
 'Total immigrants by selected places of birth',
 'Non-permanent residents',
 'Total population by visible minority groups',
 'Total visible minority population',
 'All others',
 'Population 15 years and over by labour force activity',
 'Participation rate',
 'Employment rate',
 'Unemployment rate',
 'Total employed labour force 15 years and over by place of work status',
 'Males',
 'Females',
 'Total employed labour force 15 years and over by mode of transportation',
 'Males with usual place of work or no fixed workplace address',
 'Car, truck, van, as driver',
 'Car, truck, van, as passenger',
 'Public transit',
 'Walked',
 'Bicycle',
 'Motorcycle',
 'Taxicab',
 'Other method',
 'Females with usual place of work or no fixed workplace address',
 'Car, truck, van, as driver',
 'Car, truck, van, as passenger',
 'Public transit',
 'Walked',
 'Bicycle',
 'Motorcycle',
 'Taxicab',
 'Other method',
 'Total population 15 to 24 years by school attendance',
 'Not attending school',
 'Attending school full time',
 'Attending school part time',
 'Total population of males with postsecondary qualifications by major field '
 'of study',
 'Total population of females with postsecondary qualifications by major field '
 'of study',
 'Total population 20 years and over by highest level of schooling',
 'Less than grade 9',
 'Grades 9 to 13',
 'Trades certificate or diploma',
 'College',
 'Without certificate or diploma',
 'With certificate or diploma',
 'University',
 'Without degree',
 "With bachelor's degree or higher",
 'Total income in 2000 of population 15 years and over',
 'Average income $',
 'Median income $',
 'Total - Economic families',
 'Low income',
 'Other',
 'Total - Unattached individuals 15 years and over',
 'Total - Population in private households',
 'Household income in 2000 of all private households',
 'Average household income $',
 'Median household income $',
 'Standard error of average household income $',
 'Average gross rent $',
 'Owner households in non-farm, non-reserve private dwellings',
 'Average value of dwelling $']

In [ ]:
columns_to_drop = ['Type',
 'Region Name',
 'Area (sq km)',
 'Population ',
 'Separated, but still legally married',
 'Divorced',
 'Widowed',
 'Total population 15 years and over by common-law status',
 'Not in a common-law relationship',
 'In a common-law relationship',
 'Average number of rooms per dwelling',
 'Average number of bedrooms per dwelling',
 'Total number of census families in private households',
 'Total couple families by family structure and number of children',
 'Married couples',
 'Common-law couples',
 'Total number of children at home',
 'Average number of children at home per census family',
 'Average number of persons per census family',
 'Total number of persons in private households',
 'Total number of private households by household size',
 'Internal migrants',
 'External migrants',
 'Total population by visible minority groups',
 'Total population 15 to 24 years by school attendance',
 'Not attending school',
 'Attending school full time',
 'Attending school part time',
 'Total - Unattached individuals 15 years and over',
 'Standard error of average household income $',
]

cleaned_2001_census = census_2001.drop(columns=columns_to_drop)

print(cleaned_2001_census.columns)

Index(['GeoUID', 'Dwellings ', 'Households ', 'Population, 2001',
       'Population percentage change, 1996-2001',
       'Land area in square kilometres, 2001',
       'Total population 15 years and over by legal marital status',
       'Never legally married (single)', 'Legally married (and not separated)',
       'Total population by sex and age groups',
       ...
       'Total - Economic families', 'Low income', 'Other',
       'Total - Population in private households',
       'Household income in 2000 of all private households',
       'Average household income $', 'Median household income $',
       'Average gross rent $',
       'Owner households in non-farm, non-reserve private dwellings',
       'Average value of dwelling $'],
      dtype='object', length=139)

In [ ]:
df = cleaned_2001_census.copy()

df = df.groupby(level=0, axis=1).sum()

pprint.pprint(list(df.columns))
df.head()

['0-4',
 '10-14',
 '15-19',
 '20-24',
 '25-29',
 '30-34',
 '35-39',
 '40-44',
 '45-49',
 '5-9',
 '50-54',
 '55-59',
 '60-64',
 '65-69',
 '70-74',
 '75-79',
 '80-84',
 '85+',
 'All others',
 'Apartment, building that has fewer than five storeys',
 'Apartment, building that has five or more storeys',
 'Apartment, detached duplex',
 'Average gross rent $',
 'Average household income $',
 'Average income $',
 'Average number of persons in private households',
 'Average value of dwelling $',
 'Band housing',
 'Bicycle',
 'Born in province of residence',
 'Born outside province of residence',
 'Canadian citizenship',
 'Car, truck, van, as driver',
 'Car, truck, van, as passenger',
 'Citizenship other than Canadian',
 'College',
 'Dwellings ',
 'Employment rate',
 'Female, total',
 'Females',
 'Females with usual place of work or no fixed workplace address',
 'GeoUID',
 'Grades 9 to 13',
 'Household income in 2000 of all private households',
 'Households ',
 'Land area in square kilometres, 2001',
 'Legally married (and not separated)',
 'Less than grade 9',
 'Low income',
 'Major repairs',
 'Male, total',
 'Males',
 'Males with usual place of work or no fixed workplace address',
 'Median household income $',
 'Median income $',
 'Migrants',
 'Minor repairs',
 'Motorcycle',
 'Movable dwelling',
 'Movers',
 'Never legally married (single)',
 'Non-immigrant population',
 'Non-migrants',
 'Non-movers',
 'Non-permanent residents',
 'Number of persons in private households',
 'Other',
 'Other method',
 'Other single-attached house',
 'Owned',
 'Owner households in non-farm, non-reserve private dwellings',
 'Participation rate',
 'Period of construction, 1946-1960',
 'Period of construction, 1961-1970',
 'Period of construction, 1971-1980',
 'Period of construction, 1981-1990',
 'Period of construction, 1991-1995',
 'Period of construction, 1996-2001',
 'Period of construction, before 1946',
 'Population 15 years and over by labour force activity',
 'Population percentage change, 1996-2001',
 'Population, 2001',
 'Public transit',
 'Regular maintenance only',
 'Rented',
 'Row house',
 'Semi-detached house',
 'Single-detached house',
 'Taxicab',
 'Total - Economic families',
 'Total - Population in private households',
 'Total employed labour force 15 years and over by mode of transportation',
 'Total employed labour force 15 years and over by place of work status',
 'Total immigrants by selected places of birth',
 'Total income in 2000 of population 15 years and over',
 'Total number of occupied private dwellings by structural type of dwelling',
 'Total population 1 year and over by mobility status 1 year ago',
 'Total population 15 years and over by legal marital status',
 'Total population 20 years and over by highest level of schooling',
 'Total population by citizenship',
 'Total population by immigrant status and place of birth',
 'Total population by sex and age groups',
 'Total population of females with postsecondary qualifications by major field '
 'of study',
 'Total population of males with postsecondary qualifications by major field '
 'of study',
 'Total visible minority population',
 'Trades certificate or diploma',
 'Unemployment rate',
 'University',
 'Walked',
 "With bachelor's degree or higher",
 'With certificate or diploma',
 'Without certificate or diploma',
 'Without degree']

,0-4,10-14,15-19,20-24,25-29,30-34,35-39,40-44,45-49,5-9,...,Total population of males with postsecondary qualifications by major field of study,Total visible minority population,Trades certificate or diploma,Unemployment rate,University,Walked,With bachelor's degree or higher,With certificate or diploma,Without certificate or diploma,Without degree
0,6050,4555,6560,5580,9070,8080,10595,115130,95115,7060,...,325,10,290,5.2,125,030,70,235,100,55
1,6045,7575,7085,8590,7575,95100,11595,100125,110130,9080,...,345,130,270,9.4,180,1035,95,195,125,85
2,160145,195185,185200,215215,190220,180220,270280,285300,265300,175195,...,805,370,510,8.5,620,25130,350,730,310,270
3,6050,8585,9075,95100,9595,9090,120135,170165,120135,7585,...,520,120,395,7.1,305,2060,195,360,105,110
4,5555,7575,8570,9590,9095,10085,135110,145150,140140,6590,...,485,45,230,7.3,355,3535,210,360,130,145

In [ ]:
# Merge and rename columns
df['0 to 19 years'] = df['0-4'] + df['5-9'] + df['10-14'] + df['15-19']
df['20 to 29 years'] = df['20-24'] + df['25-29']
df['30 to 39 years'] = df['30-34'] + df['35-39']
df['40 to 49 years'] = df['40-44'] + df['45-49']
df['50 to 59 years'] = df['50-54'] + df['55-59']
df['60+ years'] = df['60-64'] + df['65-69'] + df['70-74'] + df['75-79'] + df['80-84'] + df['85+']

# Drop the original columns
df = df.drop(['0-4',
 '10-14',
 '15-19',
 '20-24',
 '25-29',
 '30-34',
 '35-39',
 '40-44',
 '45-49',
 '5-9',
 '50-54',
 '55-59',
 '60-64',
 '65-69',
 '70-74',
 '75-79',
 '80-84',
 '85+'], axis=1)

df.head()

<ipython-input-6-327a2cb54377>:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['0 to 19 years'] = df['0-4'] + df['5-9'] + df['10-14'] + df['15-19']
<ipython-input-6-327a2cb54377>:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['20 to 29 years'] = df['20-24'] + df['25-29']
<ipython-input-6-327a2cb54377>:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['30 to 39 years'] = df['30-34'] + df['35-39']
<ipython-input-6-327a2cb54377>:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['40 to 49 years'] = df['40-44'] + df['45-49']
<ipython-input-6-327a2cb54377>:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['50 to 59 years'] = df['50-54'] + df['55-59']
<ipython-input-6-327a2cb54377>:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['60+ years'] = df['60-64'] + df['65-69'] + df['70-74'] + df['75-79'] + df['80-84'] + df['85+']

,All others,"Apartment, building that has fewer than five storeys","Apartment, building that has five or more storeys","Apartment, detached duplex",Average gross rent $,Average household income $,Average income $,Average number of persons in private households,Average value of dwelling $,Band housing,...,With bachelor's degree or higher,With certificate or diploma,Without certificate or diploma,Without degree,0 to 19 years,20 to 29 years,30 to 39 years,40 to 49 years,50 to 59 years,60+ years
0,2395,1025,0,30,554,42237,24971,2.1,107148,0,...,70,235,100,55,6050706045556560,55809070,808010595,11513095115,100959080,70704565457030501530515
1,2595,690,70,220,528,36451,21095,2.1,107098,0,...,95,195,125,85,6045908075757085,85907575,9510011595,100125110130,90807080,60856095657040852040015
2,6065,2250,0,115,541,43453,23997,2.3,139439,0,...,350,730,310,270,160145175195195185185200,215215190220,180220270280,285300265300,215260200230,1351751401851201657011035551540
3,3000,840,0,270,533,41685,24576,2.0,129464,0,...,195,360,105,110,6050758585859075,951009595,9090120135,170165120135,11514585100,709565907090559035501040
4,3025,1320,0,110,504,38463,23320,2.0,120973,0,...,210,360,130,145,5555659075758570,95909095,10085135110,145150140140,120150120105,65857510075100659010451015

In [ ]:
df = df.rename(columns={col: f"{col} 2001" for col in df.columns})

df.head()

,All others 2001,"Apartment, building that has fewer than five storeys 2001","Apartment, building that has five or more storeys 2001","Apartment, detached duplex 2001",Average gross rent $ 2001,Average household income $ 2001,Average income $ 2001,Average number of persons in private households 2001,Average value of dwelling $ 2001,Band housing 2001,...,With bachelor's degree or higher 2001,With certificate or diploma 2001,Without certificate or diploma 2001,Without degree 2001,0 to 19 years 2001,20 to 29 years 2001,30 to 39 years 2001,40 to 49 years 2001,50 to 59 years 2001,60+ years 2001
0,2395,1025,0,30,554,42237,24971,2.1,107148,0,...,70,235,100,55,6050706045556560,55809070,808010595,11513095115,100959080,70704565457030501530515
1,2595,690,70,220,528,36451,21095,2.1,107098,0,...,95,195,125,85,6045908075757085,85907575,9510011595,100125110130,90807080,60856095657040852040015
2,6065,2250,0,115,541,43453,23997,2.3,139439,0,...,350,730,310,270,160145175195195185185200,215215190220,180220270280,285300265300,215260200230,1351751401851201657011035551540
3,3000,840,0,270,533,41685,24576,2.0,129464,0,...,195,360,105,110,6050758585859075,951009595,9090120135,170165120135,11514585100,709565907090559035501040
4,3025,1320,0,110,504,38463,23320,2.0,120973,0,...,210,360,130,145,5555659075758570,95909095,10085135110,145150140140,120150120105,65857510075100659010451015

In [ ]:
df.to_csv('/content/drive/MyDrive/GentrificAItion/Montreal_data_from_census/Cleaned_Census_Data/2001_emilie_v1.csv')

# 1996 Data Cleaning

# Standardizing Census Tracts
do pop_dwe for dwelling

In [ ]:
# example of apportioning data from source tracts to target tracts using an apportionment (i.e. crosswalk) table
import numpy as np
# the apportionment table
# crosswalk_csv = '/content/drive/MyDrive/Ai4Good Colabs (Emily Hong)/ct_2016_2021.csv'
crosswalk_csv = '/content/drive/MyDrive/GentrificAItion/Montreal_data_from_census/ct_2016_2021.csv'

# the csv with source tract data to apportioned
data_csv = '/content/drive/MyDrive/GentrificAItion/Montreal_data_from_census/2016_emilie_v1.csv'


# the name of the field pertaining to the ctuid in data_csv
ctuidcol = "ctuid"

# names of columns we want to apportion
fields = [
    'Population, 2016',
    #'Population percentage change, 2011 to 2016',
    'Total private dwellings',
    'Private dwellings occupied by usual residents',
    'Population density per square kilometre',
    'Total - Age groups and average age of the population - 100% data',
    '0 to 14 years',
    '15 to 19 years',
    '20 to 24 years',
    '25 to 29 years',
    '30 to 34 years',
    '35 to 39 years',
    '40 to 44 years',
    '45 to 49 years',
    '50 to 54 years',
    '55 to 59 years',
    '60 to 64 years',
    '65 years and over',
    'Median age of the population',
    'Average age of the population',
    'Total - Occupied private dwellings by structural type of dwelling - 100% data',
    'Single-detached house',
    'Apartment in a building that has five or more storeys',
    'Semi-detached house',
    'Row house',
    'Apartment or flat in a duplex',
    'Apartment in a building that has fewer than five storeys',
    'Other single-attached house',
    'Movable dwelling',
    'Average household size',
    'Total - Marital status for the population aged 15 years and over - 100% data',
    'Married or living common law',
    'Not married and not living common law',
    'Total - Private households by household type - 100% data',
    'One-census-family households',
    'Multiple-census-family households',
    'Non-census-family households',
    'Median total income of households in 2015 ($)',
    'Median after-tax income of households in 2015 ($)',
    'Prevalence of low income based on the Low-income measure, after tax (LIM-AT) (%)',
    'Prevalence of low income based on the Low-income cut-offs, after tax (LICO-AT) (%)',
    'Total - Citizenship for the population in private households - 25% sample data',
    'Canadian citizens',
    'Not Canadian citizens',
    'Total - Immigrant status and period of immigration for the population in private households - 25% sample data',
    'Non-immigrants',
    'Immigrants',
    'Non-permanent residents',
    'Total - Visible minority for the population in private households - 25% sample data',
    'Total visible minority population',
    'Not a visible minority',
    'Total - Private households by tenure - 25% sample data',
    'Owner',
    'Renter',
    'Band housing',
    'Total - Occupied private dwellings by condominium status - 25% sample data',
    'Condominium',
    'Not condominium',
    'Total - Private households by housing suitability - 25% sample data',
    'Suitable',
    'Not suitable',
    'Total - Occupied private dwellings by dwelling condition - 25% sample data',
    'Only regular maintenance or minor repairs needed',
    'Major repairs needed',
    'Average number of rooms per dwelling',
    '% of tenant households in subsidized housing',
    'Median monthly shelter costs for owned dwellings ($)',
    'Average monthly shelter costs for owned dwellings ($)',
    'Median value of dwellings ($)',
    'Average value of dwellings ($)',
    'Median monthly shelter costs for rented dwellings ($)',
    'Median monthly shelter costs for rented dwellings ($)',
    'Total - Highest certificate, diploma or degree for the population aged 15 years and over in private households - 25% sample data',
    'No certificate, diploma or degree',
    'Secondary (high) school diploma or equivalency certificate',
    'Postsecondary certificate, diploma or degree',
    'College, CEGEP or other non-university certificate or diploma',
    'University certificate or diploma below bachelor level',
    'University certificate, diploma or degree at bachelor level or above',
    'Total - Location of study compared with province or territory of residence with countries outside Canada for the population aged 15 years and over in private households - 25% sample data',
    'Location of study inside Canada',
    'Same as province or territory of residence',
    'Different than province or territory of residence',
    'Location of study outside Canada',
    'Total - Population aged 15 years and over by Labour force status - 25% sample data',
    'In the labour force',
    'Not in the labour force',
    'Total - Main mode of commuting for the employed labour force aged 15 years and over in private households with a usual place of work or no fixed workplace address - 25% sample data',
    'Car, truck, van - as a driver',
    'Car, truck, van - as a passenger',
    'Public transit',
    'Walked',
    'Bicycle',
    'Other method',
    'Total - Commuting duration for the employed labour force aged 15 years and over in private households with a usual place of work or no fixed workplace address - 25% sample data',
    'Less than 15 minutes',
    '15 to 29 minutes',
    '30 to 44 minutes',
    '45 to 59 minutes',
    '60 minutes and over',
    'Total - Mobility status 1 year ago - 25% sample data',
    'Non-movers',
    'Movers'
]


# output file name
# output_file_name = '/content/drive/MyDrive/Ai4Good Colabs (Emily Hong)/data_from_2016_into_2021_CTs.csv'
output_file_name = '/content/drive/MyDrive/GentrificAItion/Montreal_data_from_census/2016_into_2021_CTs_EN_v1.csv'

# read in the data
df = pd.read_csv(data_csv)

# read in crosswalk table
cw = pd.read_csv(crosswalk_csv)

# joining the two input tables
merge_cw_df = cw.merge(df, how = "inner", left_on = "source_ctuid", right_on = ctuidcol)
# print(merge_cw_df.head())
# loop over each field, multiplying by the apportionment weight
output_fields = []
for f in fields:
    print(f)
    merge_cw_df["w_" + f] = np.asarray(merge_cw_df["w_pop"]) * np.asarray( pd.to_numeric(merge_cw_df[f], errors='coerce'))
    output_fields.append("w_" + f)

# group by the target census tracts, summing by the wanted fields
output_data = merge_cw_df.groupby(["target_ctuid"]).sum()
output_data = output_data[output_fields]
output_data= output_data.astype(int)

# write to file
output_data.to_csv(output_file_name)
output_data.head()

Population, 2016

KeyError: 'Population, 2016'

#  Combining Data Years Together

#  Cleaning Data

# Adding Other External Data

# Testing Models