<a href="https://colab.research.google.com/github/EmilyHong77/degentrificAItion/blob/main/Ding_Measures.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from google.colab import drive
drive.mount('/content/drive')

import numpy as np
import pandas as pd

Mounted at /content/drive


# Merging 5 datasets

In [3]:
df_2001 = pd.read_csv('/content/drive/MyDrive/GentrificAItion/Montreal_data_from_census/Standardized_Census_Data/2001_census_standardized.csv')
df_2006 = pd.read_csv('/content/drive/MyDrive/GentrificAItion/Montreal_data_from_census/Standardized_Census_Data/2006_census_standardized.csv')
df_2011 = pd.read_csv('/content/drive/MyDrive/GentrificAItion/Montreal_data_from_census/Standardized_Census_Data/2011_census_standardized.csv')
df_2016 = pd.read_csv('/content/drive/MyDrive/GentrificAItion/Montreal_data_from_census/Standardized_Census_Data/2016_census_standardized.csv')
df_2021 = pd.read_csv('/content/drive/MyDrive/GentrificAItion/Montreal_data_from_census/Standardized_Census_Data/2021_census_standardized.csv')

df_2001 = df_2001.rename(columns={'target_ctuid': 'ctuid'})
df_2006 = df_2006.rename(columns={'target_ctuid': 'ctuid'})
df_2011 = df_2011.rename(columns={'target_ctuid': 'ctuid'})
df_2016 = df_2016.rename(columns={'target_ctuid': 'ctuid'})


print(df_2021.describe())


'''
print(len(df_2006.columns))
print(len(df_2011.columns))
print(len(df_2016.columns))
print(len(df_2021.columns))
'''

              ctuid  Population percentage change, 2016 to 2021 2021  \
count  1.007000e+03                                       992.000000
mean   4.615959e+06                                         5.696875
std    1.455918e+05                                        26.155321
min    4.620000e+02                                      -100.000000
25%    4.620226e+06                                        -0.900000
50%    4.620593e+06                                         1.800000
75%    4.620740e+06                                         6.025000
max    4.622402e+06                                       500.000000

       Total private dwellings 2021  \
count                  1.002000e+03
mean                   3.849494e+03
std                    6.089298e+04
min                    0.000000e+00
25%                    1.337000e+03
50%                    1.810500e+03
75%                    2.432000e+03
max                    1.929263e+06

       Private dwellings occupied by usual residents 2021  \
count                                       1.002000e+03
mean                                        3.662768e+03
std                                         5.793976e+04
min                                         0.000000e+00
25%                                         1.279000e+03
50%                                         1.741000e+03
75%                                         2.324000e+03
max                                         1.835698e+06

       Population density per square kilometre 2021  \
count                                   1002.000000
mean                                    5666.015170
std                                     5434.557316
min                                        0.000000
25%                                     1933.125000
50%                                     3785.450000
75%                                     8294.400000
max                                    48864.000000

       Total - Age groups of the population - 100% data 2021  \
count                                       9.860000e+02
mean                                        8.701324e+03
std                                         1.365516e+05
min                                         4.000000e+02
25%                                         2.998750e+03
50%                                         4.160000e+03
75%                                         5.485000e+03
max                                         4.291735e+06

       0 to 14 years 2021  15 to 19 years 2021  20 to 24 years 2021  \
count          986.000000           986.000000           986.000000
mean            16.134888           462.216024           522.834686
std              4.414176          7253.426674          8206.387973
min              2.300000             5.000000             5.000000
25%             13.600000           130.000000           175.000000
50%             16.400000           215.000000           240.000000
75%             18.700000           310.000000           320.000000
max             38.700000        227955.000000        257910.000000

       25 to 29 years 2021  ...   Walked 2021  Bicycle 2021  \
count           986.000000  ...    986.000000    986.000000
mean            591.424949  ...    181.323529     56.577079
std            9279.952303  ...   2846.497848    899.103289
min              10.000000  ...      0.000000      0.000000
25%             190.000000  ...     45.000000      0.000000
50%             270.000000  ...     75.000000     15.000000
75%             365.000000  ...    120.000000     35.000000
max          291650.000000  ...  89445.000000  28240.000000

       Other method 2021  \
count         986.000000
mean           52.074037
std           820.349086
min             0.000000
25%            15.000000
50%            25.000000
75%            35.000000
max         25780.000000

       Total - Commuting duration for the employed labour force aged 15 years and over with a usual place of work or no fixed workplace address - 25% sample data 2021  \
count                                       9.860000e+02
mean                                        3.175375e+03
std                                         4.983593e+04
min                                         1.500000e+02
25%                                         1.001250e+03
50%                                         1.495000e+03
75%                                         2.030000e+03
max                                         1.566265e+06

       Less than 15 minutes 2021  15 to 29 minutes 2021  \
count                 986.000000             986.000000
mean                  685.689655            1128.950304
std                 10770.018260           17713.833744
min                    30.000000              50.000000
25%                   185.000000             360.000000
50%                   305.000000             520.000000
75%                   445.000000             720.000000
max                338465.000000          556715.000000

       30 to 44 minutes 2021  45 to 59 minutes 2021  60 minutes and over 2021  \
count             986.000000             986.000000                986.000000
mean              798.230223             307.834686                254.594320
std             12524.925775            4830.948047               3997.676748
min                25.000000               0.000000                  0.000000
25%               250.000000              85.000000                 65.000000
50%               370.000000             140.000000                110.000000
75%               515.000000             205.000000                170.000000
max            393635.000000          151820.000000             125625.000000

       Population, 2021 2021
count            1002.000000
mean             4283.165669
std              1983.267551
min                 0.000000
25%              2896.750000
50%              4133.500000
75%              5472.000000
max             14150.000000

[8 rows x 100 columns]

'\nprint(len(df_2006.columns))\nprint(len(df_2011.columns))\nprint(len(df_2016.columns))\nprint(len(df_2021.columns))\n'

In [4]:
from functools import reduce

df = reduce(lambda x,y: pd.merge(x,y, on='ctuid', how='outer'), [df_2001, df_2006, df_2011, df_2016, df_2021])

print(len(df.columns))

df.describe()

517

,ctuid,All others 2001,"Apartment, building that has fewer than five storeys 2001","Apartment, building that has five or more storeys 2001","Apartment, detached duplex 2001",Average gross rent $ 2001,Average household income $ 2001,Average income $ 2001,Average number of persons in private households 2001,Average value of dwelling $ 2001,...,Walked 2021,Bicycle 2021,Other method 2021,Total - Commuting duration for the employed labour force aged 15 years and over with a usual place of work or no fixed workplace address - 25% sample data 2021,Less than 15 minutes 2021,15 to 29 minutes 2021,30 to 44 minutes 2021,45 to 59 minutes 2021,60 minutes and over 2021,"Population, 2021 2021"
count,1.008000e+03,968.000000,968.000000,968.000000,968.000000,968.000000,968.000000,968.000000,968.000000,968.000000,...,986.000000,986.000000,986.000000,9.860000e+02,986.000000,986.000000,986.000000,986.000000,986.000000,1002.000000
mean,4.611379e+06,3022.377066,686.672521,126.982438,51.294421,509.099174,48063.589876,25607.246901,1.632231,130157.245868,...,181.323529,56.577079,52.074037,3.175375e+03,685.689655,1128.950304,798.230223,307.834686,254.594320,4283.165669
std,2.057034e+05,1500.356014,624.536805,331.346753,92.211870,201.974428,28585.533331,13327.694537,0.760364,78401.993177,...,2846.497848,899.103289,820.349086,4.983593e+04,10770.018260,17713.833744,12524.925775,4830.948047,3997.676748,1983.267551
min,-1.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,1.500000e+02,30.000000,50.000000,25.000000,0.000000,0.000000,0.000000
25%,4.620225e+06,1978.750000,120.000000,0.000000,5.000000,475.000000,33597.750000,19637.750000,1.000000,96556.750000,...,45.000000,0.000000,15.000000,1.001250e+03,185.000000,360.000000,250.000000,85.000000,65.000000,2896.750000
50%,4.620593e+06,2962.500000,525.000000,0.000000,15.000000,530.000000,44112.000000,24979.000000,2.000000,123753.500000,...,75.000000,15.000000,25.000000,1.495000e+03,305.000000,520.000000,370.000000,140.000000,110.000000,4133.500000
75%,4.620740e+06,3966.250000,1135.000000,90.000000,55.000000,593.000000,57925.000000,29940.000000,2.000000,155288.250000,...,120.000000,35.000000,35.000000,2.030000e+03,445.000000,720.000000,515.000000,205.000000,170.000000,5472.000000
max,4.622402e+06,6970.000000,3010.000000,3535.000000,715.000000,1468.000000,349609.000000,155196.000000,3.000000,964788.000000,...,89445.000000,28240.000000,25780.000000,1.566265e+06,338465.000000,556715.000000,393635.000000,151820.000000,125625.000000,14150.000000

In [ ]:
# output file name
output_file_name = '/content/drive/MyDrive/GentrificAItion/Montreal_data_from_census/Standardized_Census_Data/2001_2021_combined.csv'

# write to file
df.to_csv(output_file_name)
df.head()

,ctuid,All others 2001,"Apartment, building that has fewer than five storeys 2001","Apartment, building that has five or more storeys 2001","Apartment, detached duplex 2001",Average gross rent $ 2001,Average household income $ 2001,Average income $ 2001,Average number of persons in private households 2001,Average value of dwelling $ 2001,...,Walked 2021,Bicycle 2021,Other method 2021,Total - Commuting duration for the employed labour force aged 15 years and over with a usual place of work or no fixed workplace address - 25% sample data 2021,Less than 15 minutes 2021,15 to 29 minutes 2021,30 to 44 minutes 2021,45 to 59 minutes 2021,60 minutes and over 2021,"Population, 2021 2021"
0,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,4620001.0,2395.0,1025.0,0.0,30.0,554.0,42237.0,24971.0,2.0,107148.0,...,15.0,20.0,10.0,1030.0,180.0,360.0,255.0,135.0,100.0,2684.0
2,4620002.0,2595.0,690.0,70.0,220.0,528.0,36451.0,21095.0,2.0,107098.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3780.0
3,4620002.0,2595.0,690.0,70.0,220.0,528.0,36451.0,21095.0,2.0,107098.0,...,30.0,10.0,0.0,1395.0,210.0,485.0,325.0,185.0,185.0,NaN
4,4620003.0,6065.0,2250.0,0.0,115.0,541.0,43453.0,23997.0,2.0,139439.0,...,135.0,50.0,35.0,2530.0,470.0,800.0,660.0,370.0,230.0,6600.0

Gentrifiable Measure

In [5]:
# GENTRIFIABLE = median_income_tract < median_income_CMA
# GENTRIFIED = ((median_rent_tract < median_rent_CMA) or (median_home_value_tract < median_home_value_CMA)) and ((increase_uni_educated_residents_tract > increase_uni_educated_residents_CMA))

median_income_CMA_2021 = df.loc[df['ctuid'] == 462, "Median total income of household in 2020 ($) 2021"].values[0]
median_income_CMA_2016 = df.loc[df['ctuid'] == 462, "Median total income of households in 2015 ($) 2016"].values[0]
median_income_CMA_2011 = df.loc[df['ctuid'] == 462, "Median total income ($) 2011"].values[0]
median_income_CMA_2006 = 47979 # found online in Census data
median_income_CMA_2001 = 47267 # found online in Census data

df['Gentrifiable Ding 2021'] = df['Median total income of household in 2020 ($) 2021'] < median_income_CMA_2021
df['Gentrifiable Ding 2016'] = df['Median total income of households in 2015 ($) 2016'] < median_income_CMA_2016
df['Gentrifiable Ding 2011'] = df['Median total income ($) 2011'] < median_income_CMA_2011
df['Gentrifiable Ding 2006'] = df['Median household income $ 2006'] < median_income_CMA_2006
df['Gentrifiable Ding 2001'] = df['Median household income $ 2001'] < median_income_CMA_2001

df.head()

,ctuid,All others 2001,"Apartment, building that has fewer than five storeys 2001","Apartment, building that has five or more storeys 2001","Apartment, detached duplex 2001",Average gross rent $ 2001,Average household income $ 2001,Average income $ 2001,Average number of persons in private households 2001,Average value of dwelling $ 2001,...,15 to 29 minutes 2021,30 to 44 minutes 2021,45 to 59 minutes 2021,60 minutes and over 2021,"Population, 2021 2021",Gentrifiable Ding 2021,Gentrifiable Ding 2016,Gentrifiable Ding 2011,Gentrifiable Ding 2006,Gentrifiable Ding 2001
0,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,False,False,False,True,True
1,4620001.0,2395.0,1025.0,0.0,30.0,554.0,42237.0,24971.0,2.0,107148.0,...,360.0,255.0,135.0,100.0,2684.0,True,False,False,True,True
2,4620002.0,2595.0,690.0,70.0,220.0,528.0,36451.0,21095.0,2.0,107098.0,...,NaN,NaN,NaN,NaN,3780.0,True,False,False,True,True
3,4620002.0,2595.0,690.0,70.0,220.0,528.0,36451.0,21095.0,2.0,107098.0,...,485.0,325.0,185.0,185.0,NaN,False,False,False,True,True
4,4620003.0,6065.0,2250.0,0.0,115.0,541.0,43453.0,23997.0,2.0,139439.0,...,800.0,660.0,370.0,230.0,6600.0,True,False,False,True,True

In [ ]:
# output file name
output_file_name = '/content/drive/MyDrive/GentrificAItion/Montreal_data_from_census/Standardized_Census_Data/2001_2021_gentrifiable_measure.csv'

# write to file
df.to_csv(output_file_name)
df.head()

,ctuid,All others 2001,"Apartment, building that has fewer than five storeys 2001","Apartment, building that has five or more storeys 2001","Apartment, detached duplex 2001",Average gross rent $ 2001,Average household income $ 2001,Average income $ 2001,Average number of persons in private households 2001,Average value of dwelling $ 2001,...,15 to 29 minutes 2021,30 to 44 minutes 2021,45 to 59 minutes 2021,60 minutes and over 2021,"Population, 2021 2021",Gentrifiable Ding 2021,Gentrifiable Ding 2016,Gentrifiable Ding 2011,Gentrifiable Ding 2006,Gentrifiable Ding 2001
0,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,False,False,False,True,True
1,4620001.0,2395.0,1025.0,0.0,30.0,554.0,42237.0,24971.0,2.0,107148.0,...,360.0,255.0,135.0,100.0,2684.0,True,False,False,True,True
2,4620002.0,2595.0,690.0,70.0,220.0,528.0,36451.0,21095.0,2.0,107098.0,...,NaN,NaN,NaN,NaN,3780.0,True,False,False,True,True
3,4620002.0,2595.0,690.0,70.0,220.0,528.0,36451.0,21095.0,2.0,107098.0,...,485.0,325.0,185.0,185.0,NaN,False,False,False,True,True
4,4620003.0,6065.0,2250.0,0.0,115.0,541.0,43453.0,23997.0,2.0,139439.0,...,800.0,660.0,370.0,230.0,6600.0,True,False,False,True,True

Calculate Gentrified Ding Measures

In [ ]:
'''
 gentrifiable.at.previous.census = gentrifiable_prev,
           gentrified = gentrifiable_prev &
             (housing_price_change > housing_price_change_median | avg_month_rent_change > avg_month_rent_change_median) &
             pct_high_educ_change > pct_high_educ_change_median)
'''

In [24]:
def weighted_quantile(values, weights, quantiles):
    """
    Compute the weighted quantiles of data.

    Parameters:
    values : array-like
        Input data.
    weights : array-like
        Weights for the data.
    quantiles : array-like
        Quantiles to compute, which should be between 0 and 1.

    Returns:
    array-like
        Weighted quantiles of the input data.
    """
    values = np.array(values)
    weights = np.array(weights)

    # Remove NaN values
    mask = ~np.isnan(values) & ~np.isnan(weights)
    values = values[mask]
    weights = weights[mask]

    # Check if there are any values left after removing NaNs
    if len(values) == 0:
        return np.nan if isinstance(quantiles, float) else [np.nan] * len(quantiles)

    # Sort values and weights
    sorter = np.argsort(values)
    values = values[sorter]
    weights = weights[sorter]

    # Compute the cumulative sum of weights
    weighted_quantiles = np.cumsum(weights) - 0.5 * weights
    weighted_quantiles /= np.sum(weights)

    # Ensure quantiles is an array
    quantiles = np.array(quantiles)

    # Interpolate to get the quantiles
    result = np.interp(quantiles, weighted_quantiles, values)

    return result

# Redefine the weighted median to use the weighted_quantile function for consistency
def weighted_median(values, weights):
    return weighted_quantile(values, weights, 0.5)

1 Median Home Value

In [32]:
# Calculation: housing_price_change > housing_price_change_median

# get dwelling population for each tract
housing_price_pop_2021 = df["Owner 2021"]
housing_price_pop_2016 = df["Owner 2016"]
housing_price_pop_2011 = df["Owner 2011"]
housing_price_pop_2006 = df["Owned 2006"]
housing_price_pop_2001 = df["Owned 2001"]

# get avg home value for each tract
housing_price_2021 = df["Average value of dwellings ($) 2021"]
housing_price_2016 = df["Average value of dwellings ($) 2016"]
housing_price_2011 = df["Average value of dwellings ($) 2011"]
housing_price_2006 = df["Average value of dwelling $ 2006"]
housing_price_2001 = df["Average value of dwelling $ 2001"]

# calculate housing_price_change
housing_price_change_2021 = (housing_price_2021 - housing_price_2016) / housing_price_2016 * 100
housing_price_change_2016 = (housing_price_2016 - housing_price_2011) / housing_price_2011 * 100
housing_price_change_2011 = (housing_price_2011 - housing_price_2006) / housing_price_2006 * 100
housing_price_change_2006 = (housing_price_2006 - housing_price_2001) / housing_price_2001 * 100


# Calculate the weighted median using the weighted_median function
housing_price_change_median_2021 = weighted_median(housing_price_change_2021, housing_price_pop_2021)
housing_price_change_median_2016 = weighted_median(housing_price_change_2016, housing_price_pop_2016)
housing_price_change_median_2011 = weighted_median(housing_price_change_2011, housing_price_pop_2011)
housing_price_change_median_2006 = weighted_median(housing_price_change_2006, housing_price_pop_2006)

2 Median Rent

In [36]:
# Calculation: avg_month_rent_change > avg_month_rent_change_median

# get total renters per year
avg_rent_pop_2021 = df["Renter 2021"]
avg_rent_pop_2016 = df["Renter 2016"]
avg_rent_pop_2011 = df["Renter 2011"]
avg_rent_pop_2006 = df["Rented 2006"]
avg_rent_pop_2001 = df["Rented 2001"]

# avg_rent per year

avg_rent_2021 = df["Median monthly shelter costs for rented dwellings ($) 2021"]
avg_rent_2016 = df["Median monthly shelter costs for rented dwellings ($) 2016"]
avg_rent_2011 = df["Median monthly shelter costs for rented dwellings ($) 2011"]
avg_rent_2006 = df["Average gross rent $ 2006"]
avg_rent_2001 = df["Average gross rent $ 2001"]

# calculate avg_rent_change
avg_rent_change_2021 = (avg_rent_2021 - avg_rent_2016) / avg_rent_2016 * 100
avg_rent_change_2016 = (avg_rent_2016 - avg_rent_2011) / avg_rent_2011 * 100
avg_rent_change_2011 = (avg_rent_2011 - avg_rent_2006) / avg_rent_2006 * 100
avg_rent_change_2006 = (avg_rent_2006 - avg_rent_2001) / avg_rent_2001 * 100

# Calculate the weighted median using the weighted_median function
avg_rent_change_median_2021 = weighted_median(avg_rent_change_2021, avg_rent_pop_2021)
avg_rent_change_median_2016 = weighted_median(avg_rent_change_2016, avg_rent_pop_2016)
avg_rent_change_median_2011 = weighted_median(avg_rent_change_2011, avg_rent_pop_2011)
avg_rent_change_median_2006 = weighted_median(avg_rent_change_2006, avg_rent_pop_2006)

3 Percent Higher Education Change

In [37]:
# pct_high_educ_change > pct_high_educ_change_median

# identify column that gives population on which education is based
pct_high_educ_pop_2021 = df["Total - Highest certificate, diploma or degree for the population aged 15 years and over in private households - 25% sample data 2021"]
pct_high_educ_pop_2016 = df["Total - Highest certificate, diploma or degree for the population aged 15 years and over in private households - 25% sample data 2016"]
pct_high_educ_pop_2011 = df["University certificate, diploma or degree at bachelor level or above 2011"]
pct_high_educ_pop_2006 = df["Total population 15 to 24 years by highest certificate, diploma or degree - 20% sample data 2006"]
pct_high_educ_pop_2001 = df["Total population of females with postsecondary qualifications by major field of study 2001"] + df["Total population of males with postsecondary qualifications by major field of study 2001"]

# Calculate % education per year
pct_high_educ_2021 = df["Bachelor's degree or higher 2021"] / pct_high_educ_pop_2021 * 100
pct_high_educ_2016 = df["University certificate, diploma or degree at bachelor level or above 2016"] / pct_high_educ_pop_2016 * 100
pct_high_educ_2011 = df["University certificate, diploma or degree at bachelor level or above 2011"] / pct_high_educ_pop_2011 * 100
pct_high_educ_2006 = df["University certificate or degree 2006"] / pct_high_educ_pop_2006 * 100
pct_high_educ_2001 = df["With bachelor's degree or higher 2001"] / pct_high_educ_pop_2001 * 100

# Calculate the change in percentage of high education for each year compared to its previous year
pct_high_educ_change_2021 = pct_high_educ_2021 - pct_high_educ_2016
pct_high_educ_change_2016 = pct_high_educ_2016 - pct_high_educ_2011
pct_high_educ_change_2011 = pct_high_educ_2011 - pct_high_educ_2006
pct_high_educ_change_2006 = pct_high_educ_2006 - pct_high_educ_2001

# Calculate weighted mean of changes for each year
pct_high_educ_change_median_2021 = weighted_median(pct_high_educ_change_2021, pct_high_educ_pop_2021)
pct_high_educ_change_median_2016 = weighted_median(pct_high_educ_change_2016, pct_high_educ_pop_2016)
pct_high_educ_change_median_2011 = weighted_median(pct_high_educ_change_2011, pct_high_educ_pop_2011)
pct_high_educ_change_median_2006 = weighted_median(pct_high_educ_change_2006, pct_high_educ_pop_2006)

Calculate Gentrified

In [ ]:
'''
 gentrifiable.at.previous.census = gentrifiable_prev,
           gentrified = gentrifiable_prev &
             (housing_price_change > housing_price_change_median | avg_month_rent_change > avg_month_rent_change_median) &
             pct_high_educ_change > pct_high_educ_change_median)
'''

In [48]:
df['Gentrified Ding 2021'] = df['Gentrifiable Ding 2016'] \
                              & ((housing_price_change_2021 > housing_price_change_median_2021) | (avg_rent_change_2021 > avg_rent_change_median_2021)) \
                              & (pct_high_educ_change_2021 > pct_high_educ_change_median_2021)

df['Gentrified Ding 2016'] = df['Gentrifiable Ding 2016'] \
                              & ((housing_price_change_2016 > housing_price_change_median_2016) | (avg_rent_change_2016 > avg_rent_change_median_2016)) \
                              & (pct_high_educ_change_2016 > pct_high_educ_change_median_2016)

df['Gentrified Ding 2011'] = df['Gentrifiable Ding 2011'] \
                              & ((housing_price_change_2011 > housing_price_change_median_2011) | (avg_rent_change_2011 > avg_rent_change_median_2011)) \
                              & (pct_high_educ_change_2011 > pct_high_educ_change_median_2011)

df['Gentrified Ding 2006'] = df['Gentrifiable Ding 2006'] \
                              & ((housing_price_change_2006 > housing_price_change_median_2006) | (avg_rent_change_2006 > avg_rent_change_median_2006)) \
                              & (pct_high_educ_change_2006 > pct_high_educ_change_median_2006)

df.head()

At least one value in the column is True.

In [45]:
# output file name
output_file_name = '/content/drive/MyDrive/GentrificAItion/Montreal_data_from_census/Standardized_Census_Data/census_data_ding.csv'

# write to file
df.to_csv(output_file_name)
df.head()

,ctuid,All others 2001,"Apartment, building that has fewer than five storeys 2001","Apartment, building that has five or more storeys 2001","Apartment, detached duplex 2001",Average gross rent $ 2001,Average household income $ 2001,Average income $ 2001,Average number of persons in private households 2001,Average value of dwelling $ 2001,...,"Population, 2021 2021",Gentrifiable Ding 2021,Gentrifiable Ding 2016,Gentrifiable Ding 2011,Gentrifiable Ding 2006,Gentrifiable Ding 2001,Gentrified Ding 2021,Gentrified Ding 2016,Gentrified Ding 2011,Gentrified Ding 2006
0,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,False,False,False,True,True,False,False,False,False
1,4620001.0,2395.0,1025.0,0.0,30.0,554.0,42237.0,24971.0,2.0,107148.0,...,2684.0,True,False,False,True,True,False,False,False,True
2,4620002.0,2595.0,690.0,70.0,220.0,528.0,36451.0,21095.0,2.0,107098.0,...,3780.0,True,False,False,True,True,False,False,False,True
3,4620002.0,2595.0,690.0,70.0,220.0,528.0,36451.0,21095.0,2.0,107098.0,...,NaN,False,False,False,True,True,False,False,False,True
4,4620003.0,6065.0,2250.0,0.0,115.0,541.0,43453.0,23997.0,2.0,139439.0,...,6600.0,True,False,False,True,True,False,False,False,True