<a href="https://colab.research.google.com/github/EmilyHong77/degentrificAItion/blob/main/Extracting_2021_Census_Tract_Polygons.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import geopandas as gpd

# Load the shape file
shapefile_path = "/content/lct_000a21a_e.shp"
shape_data = gpd.read_file(shapefile_path)

# Display the first few rows of the shape file
print(shape_data.head())

# Display basic information about the shape file
print(shape_data.info())

# Display a summary of the geometries
print(shape_data.geometry)

# Display all rows (be cautious with large datasets)
print(shape_data)

        CTUID                DGUID   CTNAME  LANDAREA PRUID  \
0  2050007.00  2021S05072050007.00  0007.00    1.1604    12
1  2050008.00  2021S05072050008.00  0008.00    0.5039    12
2  2050009.00  2021S05072050009.00  0009.00    0.6349    12
3  2050010.00  2021S05072050010.00  0010.00    0.8344    12
4  2050011.00  2021S05072050011.00  0011.00    0.8075    12

                                            geometry
0  POLYGON ((8412200.771 1441060.534, 8412216.234...
1  POLYGON ((8412785.403 1440154.089, 8412778.809...
2  POLYGON ((8413015.203 1441192.709, 8412981.660...
3  POLYGON ((8412279.320 1442133.640, 8412012.717...
4  POLYGON ((8411560.451 1440489.006, 8411551.280...
<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 6247 entries, 0 to 6246
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   CTUID     6247 non-null   object
 1   DGUID     6247 non-null   object
 2   CTNAME    6247 non-null   object
 3   LANDAREA  6247 non-null   float64
 4   PRUID     6247 non-null   object
 5   geometry  6247 non-null   geometry
dtypes: float64(1), geometry(1), object(4)
memory usage: 293.0+ KB
None
0       POLYGON ((8412200.771 1441060.534, 8412216.234...
1       POLYGON ((8412785.403 1440154.089, 8412778.809...
2       POLYGON ((8413015.203 1441192.709, 8412981.660...
3       POLYGON ((8412279.320 1442133.640, 8412012.717...
4       POLYGON ((8411560.451 1440489.006, 8411551.280...
                              ...
6242    POLYGON ((7198859.677 892261.351, 7198979.054 ...
6243    POLYGON ((7195815.517 894739.054, 7195799.486 ...
6244    POLYGON ((7620551.200 1269683.017, 7620556.654...
6245    POLYGON ((7620812.809 1268702.900, 7620791.600...
6246    POLYGON ((7620734.574 1267917.897, 7620731.431...
Name: geometry, Length: 6247, dtype: geometry
           CTUID                DGUID   CTNAME  LANDAREA PRUID  \
0     2050007.00  2021S05072050007.00  0007.00    1.1604    12
1     2050008.00  2021S05072050008.00  0008.00    0.5039    12
2     2050009.00  2021S05072050009.00  0009.00    0.6349    12
3     2050010.00  2021S05072050010.00  0010.00    0.8344    12
4     2050011.00  2021S05072050011.00  0011.00    0.8075    12
...          ...                  ...      ...       ...   ...
6242  5370223.20  2021S05075370223.20  0223.20    4.1604    35
6243  5370224.03  2021S05075370224.03  0224.03    4.2213    35
6244  4620685.09  2021S05074620685.09  0685.09    1.1975    24
6245  4620685.10  2021S05074620685.10  0685.10    1.3794    24
6246  4620685.11  2021S05074620685.11  0685.11    0.9335    24

                                               geometry
0     POLYGON ((8412200.771 1441060.534, 8412216.234...
1     POLYGON ((8412785.403 1440154.089, 8412778.809...
2     POLYGON ((8413015.203 1441192.709, 8412981.660...
3     POLYGON ((8412279.320 1442133.640, 8412012.717...
4     POLYGON ((8411560.451 1440489.006, 8411551.280...
...                                                 ...
6242  POLYGON ((7198859.677 892261.351, 7198979.054 ...
6243  POLYGON ((7195815.517 894739.054, 7195799.486 ...
6244  POLYGON ((7620551.200 1269683.017, 7620556.654...
6245  POLYGON ((7620812.809 1268702.900, 7620791.600...
6246  POLYGON ((7620734.574 1267917.897, 7620731.431...

[6247 rows x 6 columns]

In [5]:
shape_data.head()  # Display the first few rows
shape_data  # Display the entire GeoDataFrame

,CTUID,DGUID,CTNAME,LANDAREA,PRUID,geometry
0,2050007.00,2021S05072050007.00,0007.00,1.1604,12,"POLYGON ((8412200.771 1441060.534, 8412216.234..."
1,2050008.00,2021S05072050008.00,0008.00,0.5039,12,"POLYGON ((8412785.403 1440154.089, 8412778.809..."
2,2050009.00,2021S05072050009.00,0009.00,0.6349,12,"POLYGON ((8413015.203 1441192.709, 8412981.660..."
3,2050010.00,2021S05072050010.00,0010.00,0.8344,12,"POLYGON ((8412279.320 1442133.640, 8412012.717..."
4,2050011.00,2021S05072050011.00,0011.00,0.8075,12,"POLYGON ((8411560.451 1440489.006, 8411551.280..."
...,...,...,...,...,...,...
6242,5370223.20,2021S05075370223.20,0223.20,4.1604,35,"POLYGON ((7198859.677 892261.351, 7198979.054 ..."
6243,5370224.03,2021S05075370224.03,0224.03,4.2213,35,"POLYGON ((7195815.517 894739.054, 7195799.486 ..."
6244,4620685.09,2021S05074620685.09,0685.09,1.1975,24,"POLYGON ((7620551.200 1269683.017, 7620556.654..."
6245,4620685.10,2021S05074620685.10,0685.10,1.3794,24,"POLYGON ((7620812.809 1268702.900, 7620791.600..."
6246,4620685.11,2021S05074620685.11,0685.11,0.9335,24,"POLYGON ((7620734.574 1267917.897, 7620731.431..."

In [6]:
# keep if CTUID starts with 462
shape_data['CTUID'] = shape_data['CTUID'].astype(str)

# Filter the rows where CTUID starts with '462'
filtered_df = shape_data[shape_data['CTUID'].str.startswith('462')]

print(filtered_df)
print(len(filtered_df))

           CTUID                DGUID   CTNAME  LANDAREA PRUID  \
137   4620725.07  2021S05074620725.07  0725.07    1.4729    24
138   4620652.04  2021S05074620652.04  0652.04    1.2708    24
174   4620887.07  2021S05074620887.07  0887.07    9.9483    24
176   4620688.03  2021S05074620688.03  0688.03    2.0325    24
182   4620688.04  2021S05074620688.04  0688.04    1.7953    24
...          ...                  ...      ...       ...   ...
6186  4620787.01  2021S05074620787.01  0787.01    4.6280    24
6229  4620791.02  2021S05074620791.02  0791.02    3.3961    24
6244  4620685.09  2021S05074620685.09  0685.09    1.1975    24
6245  4620685.10  2021S05074620685.10  0685.10    1.3794    24
6246  4620685.11  2021S05074620685.11  0685.11    0.9335    24

                                               geometry
137   POLYGON ((7601049.883 1245504.100, 7601042.180...
138   POLYGON ((7613072.743 1242515.569, 7613081.371...
174   POLYGON ((7641359.077 1255838.403, 7641365.129...
176   POLYGON ((7604681.389 1268050.166, 7604721.363...
182   POLYGON ((7605522.854 1269014.294, 7606064.611...
...                                                 ...
6186  POLYGON ((7592527.717 1268073.740, 7593791.929...
6229  POLYGON ((7585290.286 1267934.471, 7585329.569...
6244  POLYGON ((7620551.200 1269683.017, 7620556.654...
6245  POLYGON ((7620812.809 1268702.900, 7620791.600...
6246  POLYGON ((7620734.574 1267917.897, 7620731.431...

[1004 rows x 6 columns]
1004

In [7]:
print(list[filtered_df['CTUID']])

list[137     4620725.07
138     4620652.04
174     4620887.07
176     4620688.03
182     4620688.04
           ...
6186    4620787.01
6229    4620791.02
6244    4620685.09
6245    4620685.10
6246    4620685.11
Name: CTUID, Length: 1004, dtype: object]

In [8]:
new_df = filtered_df[['CTUID', 'CTNAME', 'geometry']]
print(new_df.head)

<bound method NDFrame.head of            CTUID   CTNAME                                           geometry
137   4620725.07  0725.07  POLYGON ((7601049.883 1245504.100, 7601042.180...
138   4620652.04  0652.04  POLYGON ((7613072.743 1242515.569, 7613081.371...
174   4620887.07  0887.07  POLYGON ((7641359.077 1255838.403, 7641365.129...
176   4620688.03  0688.03  POLYGON ((7604681.389 1268050.166, 7604721.363...
182   4620688.04  0688.04  POLYGON ((7605522.854 1269014.294, 7606064.611...
...          ...      ...                                                ...
6186  4620787.01  0787.01  POLYGON ((7592527.717 1268073.740, 7593791.929...
6229  4620791.02  0791.02  POLYGON ((7585290.286 1267934.471, 7585329.569...
6244  4620685.09  0685.09  POLYGON ((7620551.200 1269683.017, 7620556.654...
6245  4620685.10  0685.10  POLYGON ((7620812.809 1268702.900, 7620791.600...
6246  4620685.11  0685.11  POLYGON ((7620734.574 1267917.897, 7620731.431...

[1004 rows x 3 columns]>

In [9]:
new_df = new_df.sort_values(by='CTUID')
print(new_df.head)

<bound method NDFrame.head of            CTUID   CTNAME                                           geometry
184   4620001.00  0001.00  POLYGON ((7633420.543 1257782.831, 7633511.454...
185   4620002.00  0002.00  POLYGON ((7632364.234 1256737.103, 7632355.126...
186   4620003.00  0003.00  POLYGON ((7632009.014 1256663.311, 7632000.760...
187   4620004.00  0004.00  POLYGON ((7632334.797 1256115.866, 7632334.791...
188   4620005.00  0005.00  POLYGON ((7632445.626 1256798.271, 7632619.389...
...          ...      ...                                                ...
4201  4622303.00  2303.00  POLYGON ((7664543.217 1230741.357, 7664530.780...
4202  4622304.00  2304.00  POLYGON ((7662276.806 1231203.754, 7662251.246...
4611  4622400.00  2400.00  POLYGON ((7663795.874 1237499.017, 7664246.449...
4174  4622401.00  2401.00  POLYGON ((7664295.389 1225741.714, 7664190.974...
4608  4622402.00  2402.00  POLYGON ((7665001.297 1232818.683, 7665106.037...

[1004 rows x 3 columns]>

In [10]:
new_df.to_csv('/content/drive/MyDrive/Ai4Good Project/GentrificAItion/FrontEnd/2021_tract_geometry.csv', index=False)

creating geoJSON file

In [16]:
import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/Ai4Good Project/GentrificAItion/FrontEnd/2021_tract_geometry.csv')
print(df.head())

       CTUID  CTNAME                                           geometry
0  4620001.0     1.0  POLYGON ((7633420.542857185 1257782.831428606,...
1  4620002.0     2.0  POLYGON ((7632364.234285757 1256737.1028571762...
2  4620003.0     3.0  POLYGON ((7632009.014285758 1256663.3114286065...
3  4620004.0     4.0  POLYGON ((7632334.7971429005 1256115.865714319...
4  4620005.0     5.0  POLYGON ((7632445.625714324 1256798.2714286037...

In [17]:
import re


# Ensure 'geometry' column is treated as string
df['geometry'] = df['geometry'].astype(str)
print(df['geometry'])

# Function to extract coordinate pairs from POLYGON format
def extract_coordinates(polygon_str):
    coordinates = re.findall(r'[-+]?\d*\.\d+|[-+]?\d+', polygon_str)
    # Converting coordinates to floats and pairing them as (x, y)
    coordinates_pairs = [(float(coordinates[i]), float(coordinates[i+1])) for i in range(0, len(coordinates), 2)]
    # Formatting as required with square brackets
    formatted_pairs = [f"[{x}, {y}]" for x, y in coordinates_pairs]
    return formatted_pairs

# Applying the function to each row in the DataFrame
df['geometry'] = df['geometry'].apply(extract_coordinates)

# Displaying the transformed DataFrame
print(df)

0       POLYGON ((7633420.542857185 1257782.831428606,...
1       POLYGON ((7632364.234285757 1256737.1028571762...
2       POLYGON ((7632009.014285758 1256663.3114286065...
3       POLYGON ((7632334.7971429005 1256115.865714319...
4       POLYGON ((7632445.625714324 1256798.2714286037...
                              ...
999     POLYGON ((7664543.217142895 1230741.3571428917...
1000    POLYGON ((7662276.805714324 1231203.754285749,...
1001    POLYGON ((7663795.874285758 1237499.017142892,...
1002    POLYGON ((7664295.388571471 1225741.71428575, ...
1003    POLYGON ((7665001.2971429005 1232818.682857178...
Name: geometry, Length: 1004, dtype: object
          CTUID  CTNAME                                           geometry
0     4620001.0     1.0  [[7633420.542857185, 1257782.831428606], [7633...
1     4620002.0     2.0  [[7632364.234285757, 1256737.1028571762], [763...
2     4620003.0     3.0  [[7632009.014285758, 1256663.3114286065], [763...
3     4620004.0     4.0  [[7632334.7971429005, 1256115.865714319], [763...
4     4620005.0     5.0  [[7632445.625714324, 1256798.2714286037], [763...
...         ...     ...                                                ...
999   4622303.0  2303.0  [[7664543.217142895, 1230741.3571428917], [766...
1000  4622304.0  2304.0  [[7662276.805714324, 1231203.754285749], [7662...
1001  4622400.0  2400.0  [[7663795.874285758, 1237499.017142892], [7664...
1002  4622401.0  2401.0  [[7664295.388571471, 1225741.71428575], [76641...
1003  4622402.0  2402.0  [[7665001.2971429005, 1232818.6828571782], [76...

[1004 rows x 3 columns]

In [21]:
import pandas as pd
import json

def create_geojson(df):
    geojson = {
        "type": "FeatureCollection",
        "features": []
    }

    years = [2001, 2006, 2011, 2016, 2021, 2026]

    for index, row in df.iterrows():
        tract_id = row['CTNAME']
        coordinates = row['geometry']  # Ensure this is a list of lists of numerical values

        for year in years:
            feature = {
                "type": "Feature",
                "geometry": {
                    "type": "Polygon",
                    "coordinates": coordinates  # Use the coordinates directly
                },
                "properties": {
                    "tract_id": tract_id,
                    "year": year,
                    "gentrified": None,
                    "gentrifiable": None
                }
            }
            geojson["features"].append(feature)

    return geojson

In [31]:
# Create the GeoJSON structure
geojson_data = create_geojson(df)

# Write the GeoJSON data to a file
with open('tracts_geojson.json', 'w') as f:
    json.dump(geojson_data, f, indent=4)

In [55]:
file_path = '/content/tracts_geojson.json'

with open(file_path, 'r') as f:
    geojson_data = f.read()

adding gentrified and gentrifiable indexes

In [27]:
# get Dings

import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/Ai4Good Project/GentrificAItion/Montreal_data_from_census/Standardized_Census_Data/census_data_ding.csv')
print(df.head())

   Unnamed: 0.1      ctuid  All others 2001  \
0             0       -1.0              0.0
1             1  4620001.0           2395.0
2             2  4620002.0           2595.0
3             3  4620002.0           2595.0
4             4  4620003.0           6065.0

   Apartment, building that has fewer than five storeys 2001  \
0                                                0.0
1                                             1025.0
2                                              690.0
3                                              690.0
4                                             2250.0

   Apartment, building that has five or more storeys 2001  \
0                                                0.0
1                                                0.0
2                                               70.0
3                                               70.0
4                                                0.0

   Apartment, detached duplex 2001  Average gross rent $ 2001  \
0                              0.0                        0.0
1                             30.0                      554.0
2                            220.0                      528.0
3                            220.0                      528.0
4                            115.0                      541.0

   Average household income $ 2001  Average income $ 2001  \
0                              0.0                    0.0
1                          42237.0                24971.0
2                          36451.0                21095.0
3                          36451.0                21095.0
4                          43453.0                23997.0

   Average number of persons in private households 2001  ...  \
0                                                0.0     ...
1                                                2.0     ...
2                                                2.0     ...
3                                                2.0     ...
4                                                2.0     ...

   Gentrifiable Ding 2006  Gentrifiable Ding 2001  Gentrified Ding 2021  \
0                    True                    True                 False
1                    True                    True                  True
2                    True                    True                 False
3                    True                    True                 False
4                    True                    True                 False

   Gentrified Ding 2016  Gentrified Ding 2011  Gentrified Ding 2006  \
0                 False                 False                 False
1                  True                 False                  True
2                 False                 False                  True
3                 False                 False                  True
4                 False                 False                 False

   Gentrification Level Ding 2021  Gentrification Level Ding 2016  \
0                               0                               0
1                               2                               3
2                               0                               0
3                               0                               0
4                               0                               0

   Gentrification Level Ding 2011  Gentrification Level Ding 2006
0                               0                               0
1                               0                               3
2                               0                               3
3                               0                               3
4                               0                               0

[5 rows x 530 columns]

In [42]:
# Using negative indexing to create a list of column names for the last 13 columns
last_columns = df.columns[-13:].tolist()


# Creating new DataFrame with the last 13 columns
new_df = df[last_columns]
new_df['ctuid'] = df['ctuid']


print(new_df)

      Gentrifiable Ding 2021  Gentrifiable Ding 2016  Gentrifiable Ding 2011  \
0                      False                    True                    True
1                       True                    True                    True
2                       True                    True                    True
3                      False                    True                    True
4                       True                    True                    True
...                      ...                     ...                     ...
1003                   False                   False                   False
1004                   False                   False                   False
1005                   False                   False                   False
1006                   False                    True                   False
1007                   False                   False                   False

      Gentrifiable Ding 2006  Gentrifiable Ding 2001  Gentrified Ding 2021  \
0                       True                    True                 False
1                       True                    True                  True
2                       True                    True                 False
3                       True                    True                 False
4                       True                    True                 False
...                      ...                     ...                   ...
1003                   False                   False                 False
1004                   False                   False                 False
1005                   False                   False                 False
1006                   False                   False                 False
1007                   False                   False                 False

      Gentrified Ding 2016  Gentrified Ding 2011  Gentrified Ding 2006  \
0                    False                 False                 False
1                     True                 False                  True
2                    False                 False                  True
3                    False                 False                  True
4                    False                 False                 False
...                    ...                   ...                   ...
1003                 False                 False                 False
1004                 False                 False                 False
1005                 False                 False                 False
1006                 False                 False                 False
1007                 False                 False                 False

      Gentrification Level Ding 2021  Gentrification Level Ding 2016  \
0                                  0                               0
1                                  2                               3
2                                  0                               0
3                                  0                               0
4                                  0                               0
...                              ...                             ...
1003                               0                               0
1004                               0                               0
1005                               0                               0
1006                               0                               0
1007                               0                               0

      Gentrification Level Ding 2011  Gentrification Level Ding 2006  \
0                                  0                               0
1                                  0                               3
2                                  0                               3
3                                  0                               3
4                                  0                               0
...                              ...                             ...
1003                               0                               0
1004                               0                               0
1005                               0                               0
1006                               0                               0
1007                               0                               0

          ctuid
0          -1.0
1     4620001.0
2     4620002.0
3     4620002.0
4     4620003.0
...         ...
1003  4622304.0
1004  4622400.0
1005  4622401.0
1006  4622402.0
1007      462.0

[1008 rows x 14 columns]

<ipython-input-42-5156026a5885>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['ctuid'] = df['ctuid']

In [43]:
i = df[(df.ctuid == '-1.0')].index

new_df.drop(i)

,Gentrifiable Ding 2021,Gentrifiable Ding 2016,Gentrifiable Ding 2011,Gentrifiable Ding 2006,Gentrifiable Ding 2001,Gentrified Ding 2021,Gentrified Ding 2016,Gentrified Ding 2011,Gentrified Ding 2006,Gentrification Level Ding 2021,Gentrification Level Ding 2016,Gentrification Level Ding 2011,Gentrification Level Ding 2006,ctuid
0,False,True,True,True,True,False,False,False,False,0,0,0,0,-1.0
1,True,True,True,True,True,True,True,False,True,2,3,0,3,4620001.0
2,True,True,True,True,True,False,False,False,True,0,0,0,3,4620002.0
3,False,True,True,True,True,False,False,False,True,0,0,0,3,4620002.0
4,True,True,True,True,True,False,False,False,False,0,0,0,0,4620003.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1003,False,False,False,False,False,False,False,False,False,0,0,0,0,4622304.0
1004,False,False,False,False,False,False,False,False,False,0,0,0,0,4622400.0
1005,False,False,False,False,False,False,False,False,False,0,0,0,0,4622401.0
1006,False,True,False,False,False,False,False,False,False,0,0,0,0,4622402.0
1007,False,False,False,False,False,False,False,False,False,0,0,0,0,462.0

In [45]:

new_df.drop(1007)

,Gentrifiable Ding 2021,Gentrifiable Ding 2016,Gentrifiable Ding 2011,Gentrifiable Ding 2006,Gentrifiable Ding 2001,Gentrified Ding 2021,Gentrified Ding 2016,Gentrified Ding 2011,Gentrified Ding 2006,Gentrification Level Ding 2021,Gentrification Level Ding 2016,Gentrification Level Ding 2011,Gentrification Level Ding 2006,ctuid
0,False,True,True,True,True,False,False,False,False,0,0,0,0,-1.0
1,True,True,True,True,True,True,True,False,True,2,3,0,3,4620001.0
2,True,True,True,True,True,False,False,False,True,0,0,0,3,4620002.0
3,False,True,True,True,True,False,False,False,True,0,0,0,3,4620002.0
4,True,True,True,True,True,False,False,False,False,0,0,0,0,4620003.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1002,False,True,False,False,False,False,False,False,False,0,0,0,0,4622303.0
1003,False,False,False,False,False,False,False,False,False,0,0,0,0,4622304.0
1004,False,False,False,False,False,False,False,False,False,0,0,0,0,4622400.0
1005,False,False,False,False,False,False,False,False,False,0,0,0,0,4622401.0
1006,False,True,False,False,False,False,False,False,False,0,0,0,0,4622402.0

In [49]:
new_df = new_df.drop(0)
new_df = new_df.drop(1007)

In [50]:
print(new_df.head())

   Gentrifiable Ding 2021  Gentrifiable Ding 2016  Gentrifiable Ding 2011  \
1                    True                    True                    True
2                    True                    True                    True
3                   False                    True                    True
4                    True                    True                    True
5                    True                    True                    True

   Gentrifiable Ding 2006  Gentrifiable Ding 2001  Gentrified Ding 2021  \
1                    True                    True                  True
2                    True                    True                 False
3                    True                    True                 False
4                    True                    True                 False
5                    True                    True                 False

   Gentrified Ding 2016  Gentrified Ding 2011  Gentrified Ding 2006  \
1                  True                 False                  True
2                 False                 False                  True
3                 False                 False                  True
4                 False                 False                 False
5                  True                 False                 False

   Gentrification Level Ding 2021  Gentrification Level Ding 2016  \
1                               2                               3
2                               0                               0
3                               0                               0
4                               0                               0
5                               0                               3

   Gentrification Level Ding 2011  Gentrification Level Ding 2006      ctuid
1                               0                               3  4620001.0
2                               0                               3  4620002.0
3                               0                               3  4620002.0
4                               0                               0  4620003.0
5                               0                               0  4620004.0

In [51]:
 df.to_csv('/content/drive/MyDrive/Ai4Good Project/GentrificAItion/Montreal_data_from_census/Standardized_Census_Data/ding_and_ctuid.csv')