<a href="https://colab.research.google.com/github/EmilyHong77/degentrificAItion/blob/main/DataCleaning/Ding_Measures.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

import numpy as np
import pandas as pd

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


# Merging 5 datasets

In [2]:
df_2001 = pd.read_csv('/content/drive/MyDrive/GentrificAItion/Montreal_data_from_census/Standardized_Census_Data/2001_census_standardized.csv')
df_2006 = pd.read_csv('/content/drive/MyDrive/GentrificAItion/Montreal_data_from_census/Standardized_Census_Data/2006_census_standardized.csv')
df_2011 = pd.read_csv('/content/drive/MyDrive/GentrificAItion/Montreal_data_from_census/Standardized_Census_Data/2011_census_standardized.csv')
df_2016 = pd.read_csv('/content/drive/MyDrive/GentrificAItion/Montreal_data_from_census/Standardized_Census_Data/2016_census_standardized.csv')
df_2021 = pd.read_csv('/content/drive/MyDrive/GentrificAItion/Montreal_data_from_census/Standardized_Census_Data/2021_census_standardized.csv')
df_1996 = pd.read_csv('/content/drive/MyDrive/GentrificAItion/Montreal_data_from_census/Standardized_Census_Data/1996_census_standardized.csv')

df_2001 = df_2001.rename(columns={'target_ctuid': 'ctuid'})
df_2006 = df_2006.rename(columns={'target_ctuid': 'ctuid'})
df_2011 = df_2011.rename(columns={'target_ctuid': 'ctuid'})
df_2016 = df_2016.rename(columns={'target_ctuid': 'ctuid'})
df_1996 = df_1996.rename(columns={'target_ctuid': 'ctuid'})

print(df_2021.describe())

              ctuid  Population percentage change, 2016 to 2021 2021  \
count  1.007000e+03                                       992.000000
mean   4.615959e+06                                         5.696875
std    1.455918e+05                                        26.155321
min    4.620000e+02                                      -100.000000
25%    4.620226e+06                                        -0.900000
50%    4.620593e+06                                         1.800000
75%    4.620740e+06                                         6.025000
max    4.622402e+06                                       500.000000

       Total private dwellings 2021  \
count                  1.002000e+03
mean                   3.849494e+03
std                    6.089298e+04
min                    0.000000e+00
25%                    1.337000e+03
50%                    1.810500e+03
75%                    2.432000e+03
max                    1.929263e+06

       Private dwellings occupied by usual residents 2021  \
count                                       1.002000e+03
mean                                        3.662768e+03
std                                         5.793976e+04
min                                         0.000000e+00
25%                                         1.279000e+03
50%                                         1.741000e+03
75%                                         2.324000e+03
max                                         1.835698e+06

       Population density per square kilometre 2021  \
count                                   1002.000000
mean                                    5666.015170
std                                     5434.557316
min                                        0.000000
25%                                     1933.125000
50%                                     3785.450000
75%                                     8294.400000
max                                    48864.000000

       Total - Age groups of the population - 100% data 2021  \
count                                       9.860000e+02
mean                                        8.701324e+03
std                                         1.365516e+05
min                                         4.000000e+02
25%                                         2.998750e+03
50%                                         4.160000e+03
75%                                         5.485000e+03
max                                         4.291735e+06

       0 to 14 years 2021  15 to 19 years 2021  20 to 24 years 2021  \
count          986.000000           986.000000           986.000000
mean            16.134888           462.216024           522.834686
std              4.414176          7253.426674          8206.387973
min              2.300000             5.000000             5.000000
25%             13.600000           130.000000           175.000000
50%             16.400000           215.000000           240.000000
75%             18.700000           310.000000           320.000000
max             38.700000        227955.000000        257910.000000

       25 to 29 years 2021  ...   Walked 2021  Bicycle 2021  \
count           986.000000  ...    986.000000    986.000000
mean            591.424949  ...    181.323529     56.577079
std            9279.952303  ...   2846.497848    899.103289
min              10.000000  ...      0.000000      0.000000
25%             190.000000  ...     45.000000      0.000000
50%             270.000000  ...     75.000000     15.000000
75%             365.000000  ...    120.000000     35.000000
max          291650.000000  ...  89445.000000  28240.000000

       Other method 2021  \
count         986.000000
mean           52.074037
std           820.349086
min             0.000000
25%            15.000000
50%            25.000000
75%            35.000000
max         25780.000000

       Total - Commuting duration for the employed labour force aged 15 years and over with a usual place of work or no fixed workplace address - 25% sample data 2021  \
count                                       9.860000e+02
mean                                        3.175375e+03
std                                         4.983593e+04
min                                         1.500000e+02
25%                                         1.001250e+03
50%                                         1.495000e+03
75%                                         2.030000e+03
max                                         1.566265e+06

       Less than 15 minutes 2021  15 to 29 minutes 2021  \
count                 986.000000             986.000000
mean                  685.689655            1128.950304
std                 10770.018260           17713.833744
min                    30.000000              50.000000
25%                   185.000000             360.000000
50%                   305.000000             520.000000
75%                   445.000000             720.000000
max                338465.000000          556715.000000

       30 to 44 minutes 2021  45 to 59 minutes 2021  60 minutes and over 2021  \
count             986.000000             986.000000                986.000000
mean              798.230223             307.834686                254.594320
std             12524.925775            4830.948047               3997.676748
min                25.000000               0.000000                  0.000000
25%               250.000000              85.000000                 65.000000
50%               370.000000             140.000000                110.000000
75%               515.000000             205.000000                170.000000
max            393635.000000          151820.000000             125625.000000

       Population, 2021 2021
count            1002.000000
mean             4283.165669
std              1983.267551
min                 0.000000
25%              2896.750000
50%              4133.500000
75%              5472.000000
max             14150.000000

[8 rows x 103 columns]

In [3]:
from functools import reduce

df = reduce(lambda x,y: pd.merge(x,y, on='ctuid', how='outer'), [df_2001, df_2006, df_2011, df_2016, df_2021, df_1996])

print(len(df.columns))

df.describe()

523

,ctuid,All others 2001,"Apartment, building that has fewer than five storeys 2001","Apartment, building that has five or more storeys 2001","Apartment, detached duplex 2001",Average gross rent $ 2001,Average household income $ 2001,Average income $ 2001,Average number of persons in private households 2001,Average value of dwelling $ 2001,...,45 to 59 minutes 2021,60 minutes and over 2021,"Population, 2021 2021",Median household income $ 1996,Owned 1996,Average value of dwelling $ 1996,Rented 1996,Average gross rent $ 1996,Total population 15 years and over by highest level of schooling 1996,With bachelor's degree or higher 1996
count,1.008000e+03,968.000000,968.000000,968.000000,968.000000,968.000000,968.000000,968.000000,968.000000,968.000000,...,986.000000,986.000000,1002.000000,962.000000,962.000000,962.000000,962.000000,962.000000,962.000000,962.000000
mean,4.611379e+06,3022.377066,686.672521,126.982438,51.294421,509.099174,48063.589876,25607.246901,1.632231,130157.245868,...,307.834686,254.594320,4283.165669,28748.317048,675.608108,108567.967775,720.180873,438.490644,2771.423077,425.642412
std,2.057034e+05,1500.356014,624.536805,331.346753,92.211870,201.974428,28585.533331,13327.694537,0.760364,78401.993177,...,4830.948047,3997.676748,1983.267551,17133.114645,463.331706,70109.496931,578.359203,206.891317,1313.236849,377.865497
min,-1.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,4.620225e+06,1978.750000,120.000000,0.000000,5.000000,475.000000,33597.750000,19637.750000,1.000000,96556.750000,...,85.000000,65.000000,2896.750000,18176.500000,288.500000,57782.000000,234.250000,290.250000,1855.500000,175.250000
50%,4.620593e+06,2962.500000,525.000000,0.000000,15.000000,530.000000,44112.000000,24979.000000,2.000000,123753.500000,...,140.000000,110.000000,4133.500000,26050.500000,600.000000,108982.000000,630.000000,491.000000,2740.000000,315.000000
75%,4.620740e+06,3966.250000,1135.000000,90.000000,55.000000,593.000000,57925.000000,29940.000000,2.000000,155288.250000,...,205.000000,170.000000,5472.000000,36666.000000,1018.750000,136631.000000,1078.750000,544.000000,3698.250000,555.000000
max,4.622402e+06,6970.000000,3010.000000,3535.000000,715.000000,1468.000000,349609.000000,155196.000000,3.000000,964788.000000,...,151820.000000,125625.000000,14150.000000,194331.000000,2120.000000,745948.000000,3645.000000,1844.000000,6500.000000,2520.000000

In [4]:
# output file name
output_file_name = '/content/drive/MyDrive/GentrificAItion/Montreal_data_from_census/Standardized_Census_Data/1996_2021_combined.csv'

# write to file
df.to_csv(output_file_name)
df.head()

,ctuid,All others 2001,"Apartment, building that has fewer than five storeys 2001","Apartment, building that has five or more storeys 2001","Apartment, detached duplex 2001",Average gross rent $ 2001,Average household income $ 2001,Average income $ 2001,Average number of persons in private households 2001,Average value of dwelling $ 2001,...,45 to 59 minutes 2021,60 minutes and over 2021,"Population, 2021 2021",Median household income $ 1996,Owned 1996,Average value of dwelling $ 1996,Rented 1996,Average gross rent $ 1996,Total population 15 years and over by highest level of schooling 1996,With bachelor's degree or higher 1996
0,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,4620001.0,2395.0,1025.0,0.0,30.0,554.0,42237.0,24971.0,2.0,107148.0,...,135.0,100.0,2684.0,31045.0,405.0,109385.0,690.0,491.0,1990.0,125.0
2,4620002.0,2595.0,690.0,70.0,220.0,528.0,36451.0,21095.0,2.0,107098.0,...,NaN,NaN,3780.0,28694.0,500.0,100160.0,765.0,487.0,2360.0,70.0
3,4620002.0,2595.0,690.0,70.0,220.0,528.0,36451.0,21095.0,2.0,107098.0,...,185.0,185.0,NaN,28694.0,500.0,100160.0,765.0,487.0,2360.0,70.0
4,4620003.0,6065.0,2250.0,0.0,115.0,541.0,43453.0,23997.0,2.0,139439.0,...,370.0,230.0,6600.0,33312.0,1095.0,127379.0,1625.0,525.0,5405.0,435.0

Gentrifiable Measure

In [5]:
# GENTRIFIABLE = median_income_tract < median_income_CMA


# get median income for montreal for each year
median_income_CMA_2021 = df.loc[df['ctuid'] == 462, "Median total income of household in 2020 ($) 2021"].values[0]
median_income_CMA_2016 = 61790 # found on stats can (Median total income of households in 2015 ($))
median_income_CMA_2011 = 53024 # found on stats can (Median household total income)
median_income_CMA_2006 = 47979 # found online in Census data
median_income_CMA_2001 = 47267 # found online in Census data
median_income_CMA_1996 = 43856 # found online in Census data

# get median income for each tract
median_income_2021 = df["Median total income of household in 2020 ($) 2021"]
median_income_2016 = df["Median total income of households in 2015 ($) 2016"]
median_income_2011 = df["Median total income ($) 2011"]
median_income_2006 = df["Median household income $ 2006"]
median_income_2001 = df["Median household income $ 2001"]
median_income_1996 = df["Median household income $ 1996"]

# calculate gentrifiable measure
df['Gentrifiable Ding 2021'] = median_income_2021 < median_income_CMA_2021
df['Gentrifiable Ding 2016'] = median_income_2016 < median_income_CMA_2016
df['Gentrifiable Ding 2011'] = median_income_2011 < median_income_CMA_2011
df['Gentrifiable Ding 2006'] = median_income_2006 < median_income_CMA_2006
df['Gentrifiable Ding 2001'] = median_income_2001 < median_income_CMA_2001
df['Gentrifiable Ding 1996'] = median_income_1996 < median_income_CMA_1996
df.head()

true_count = (df['Gentrifiable Ding 1996'] == True).sum()
print(true_count)
print(len(df['Gentrifiable Ding 1996']))

819
1008

In [6]:
# output file name
output_file_name = '/content/drive/MyDrive/GentrificAItion/Montreal_data_from_census/Standardized_Census_Data/1996_2021_gentrifiable_measure.csv'

# write to file
df.to_csv(output_file_name)
df.head()

,ctuid,All others 2001,"Apartment, building that has fewer than five storeys 2001","Apartment, building that has five or more storeys 2001","Apartment, detached duplex 2001",Average gross rent $ 2001,Average household income $ 2001,Average income $ 2001,Average number of persons in private households 2001,Average value of dwelling $ 2001,...,Rented 1996,Average gross rent $ 1996,Total population 15 years and over by highest level of schooling 1996,With bachelor's degree or higher 1996,Gentrifiable Ding 2021,Gentrifiable Ding 2016,Gentrifiable Ding 2011,Gentrifiable Ding 2006,Gentrifiable Ding 2001,Gentrifiable Ding 1996
0,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,False,True,True,True,True,True
1,4620001.0,2395.0,1025.0,0.0,30.0,554.0,42237.0,24971.0,2.0,107148.0,...,690.0,491.0,1990.0,125.0,True,True,True,True,True,True
2,4620002.0,2595.0,690.0,70.0,220.0,528.0,36451.0,21095.0,2.0,107098.0,...,765.0,487.0,2360.0,70.0,True,True,True,True,True,True
3,4620002.0,2595.0,690.0,70.0,220.0,528.0,36451.0,21095.0,2.0,107098.0,...,765.0,487.0,2360.0,70.0,False,True,True,True,True,True
4,4620003.0,6065.0,2250.0,0.0,115.0,541.0,43453.0,23997.0,2.0,139439.0,...,1625.0,525.0,5405.0,435.0,True,True,True,True,True,True

Calculate Gentrified Ding Measures

In [7]:
# helper function

def weighted_quantile(values, weights, quantiles):
    """
    Compute the weighted quantiles of data.

    Parameters:
    values : array-like
        Input data.
    weights : array-like
        Weights for the data.
    quantiles : array-like
        Quantiles to compute, which should be between 0 and 1.

    Returns:
    array-like
        Weighted quantiles of the input data.
    """
    values = np.array(values)
    weights = np.array(weights)

    # Remove NaN values
    mask = ~np.isnan(values) & ~np.isnan(weights)
    values = values[mask]
    weights = weights[mask]

    # Check if there are any values left after removing NaNs
    if len(values) == 0:
        return np.nan if isinstance(quantiles, float) else [np.nan] * len(quantiles)

    # Sort values and weights
    sorter = np.argsort(values)
    values = values[sorter]
    weights = weights[sorter]

    # Compute the cumulative sum of weights
    weighted_quantiles = np.cumsum(weights) - 0.5 * weights
    weighted_quantiles /= np.sum(weights)

    # Ensure quantiles is an array
    quantiles = np.array(quantiles)

    # Interpolate to get the quantiles
    result = np.interp(quantiles, weighted_quantiles, values)

    return result

# Redefine the weighted median to use the weighted_quantile function for consistency
def weighted_median(values, weights):
    return weighted_quantile(values, weights, 0.5)

In [ ]:
'''
 gentrifiable.at.previous.census = gentrifiable_prev,
           gentrified = gentrifiable_prev &
             (housing_price_change > housing_price_change_median | avg_month_rent_change > avg_month_rent_change_median) &
             pct_high_educ_change > pct_high_educ_change_median)
'''

'\n gentrifiable.at.previous.census = gentrifiable_prev,\n           gentrified = gentrifiable_prev &\n             (housing_price_change > housing_price_change_median | avg_month_rent_change > avg_month_rent_change_median) &\n             pct_high_educ_change > pct_high_educ_change_median)\n'

1 Median Home Value

In [8]:
# Calculation: housing_price_change > housing_price_change_median

# get dwelling population for each tract
housing_price_pop_2021 = df["Total - Owner households in non-farm, non-reserve private dwellings - 25% sample data 2021"]
housing_price_pop_2016 = df["Total - Owner households in non-farm, non-reserve private dwellings - 25% sample data 2016"]
housing_price_pop_2011 = df["Number of owner households in non-farm, non-reserve private dwellings 2011"]
housing_price_pop_2006 = df["Owner-occupied private non-farm, non-reserve dwellings 2006"]
housing_price_pop_2001 = df["Owner households in non-farm, non-reserve private dwellings 2001"]
housing_price_pop_1996 = df["Owned 1996"]

# get avg home value for each tract
housing_price_2021 = df["Average value of dwellings ($) 2021"]
housing_price_2016 = df["Average value of dwellings ($) 2016"]
housing_price_2011 = df["Average value of dwellings ($) 2011"]
housing_price_2006 = df["Average value of dwelling $ 2006"]
housing_price_2001 = df["Average value of dwelling $ 2001"]
housing_price_1996 = df["Average value of dwelling $ 1996"]

# calculate housing_price_change
housing_price_change_2021 = (housing_price_2021 - housing_price_2016) / housing_price_2016 * 100
housing_price_change_2016 = (housing_price_2016 - housing_price_2011) / housing_price_2011 * 100
housing_price_change_2011 = (housing_price_2011 - housing_price_2006) / housing_price_2006 * 100
housing_price_change_2006 = (housing_price_2006 - housing_price_2001) / housing_price_2001 * 100
housing_price_change_2001 = (housing_price_2001 - housing_price_1996) / housing_price_1996 * 100


# Calculate the weighted median using the weighted_median function
housing_price_change_median_2021 = weighted_median(housing_price_change_2021, housing_price_pop_2021)
housing_price_change_median_2016 = weighted_median(housing_price_change_2016, housing_price_pop_2016)
housing_price_change_median_2011 = weighted_median(housing_price_change_2011, housing_price_pop_2011)
housing_price_change_median_2006 = weighted_median(housing_price_change_2006, housing_price_pop_2006)
housing_price_change_median_2001 = weighted_median(housing_price_change_2001, housing_price_pop_2001)

2 Median Rent

In [9]:
# Calculation: avg_month_rent_change > avg_month_rent_change_median

# get total renters per year
avg_rent_pop_2021 = df["Total - Tenant households in non-farm, non-reserve private dwellings - 25% sample data 2021"]
avg_rent_pop_2016 = df["Total - Tenant households in non-farm, non-reserve private dwellings - 25% sample data 2016"]
avg_rent_pop_2011 = df["Number of tenant households in non-farm, non-reserve private dwellings 2011"]
avg_rent_pop_2006 = df["Tenant-occupied private non-farm, non-reserve dwellings 2006"]
avg_rent_pop_2001 = df["Owner households in non-farm, non-reserve private dwellings 2001"]
avg_rent_pop_1996 = df["Rented 1996"]

# avg_rent per year

avg_rent_2021 = df["Median monthly shelter costs for rented dwellings ($) 2021"]
avg_rent_2016 = df["Median monthly shelter costs for rented dwellings ($) 2016"]
avg_rent_2011 = df["Median monthly shelter costs for rented dwellings ($) 2011"]
avg_rent_2006 = df["Average gross rent $ 2006"]
avg_rent_2001 = df["Average gross rent $ 2001"]
avg_rent_1996 = df["Average gross rent $ 1996"]

# calculate avg_rent_change
avg_rent_change_2021 = (avg_rent_2021 - avg_rent_2016) / avg_rent_2016 * 100
avg_rent_change_2016 = (avg_rent_2016 - avg_rent_2011) / avg_rent_2011 * 100
avg_rent_change_2011 = (avg_rent_2011 - avg_rent_2006) / avg_rent_2006 * 100
avg_rent_change_2006 = (avg_rent_2006 - avg_rent_2001) / avg_rent_2001 * 100
avg_rent_change_2001 = (avg_rent_2001 - avg_rent_1996) / avg_rent_1996 * 100

# Calculate the weighted median using the weighted_median function
avg_rent_change_median_2021 = weighted_median(avg_rent_change_2021, avg_rent_pop_2021)
avg_rent_change_median_2016 = weighted_median(avg_rent_change_2016, avg_rent_pop_2016)
avg_rent_change_median_2011 = weighted_median(avg_rent_change_2011, avg_rent_pop_2011)
avg_rent_change_median_2006 = weighted_median(avg_rent_change_2006, avg_rent_pop_2006)
avg_rent_change_median_2001 = weighted_median(avg_rent_change_2001, avg_rent_pop_2001)

3 Percent Higher Education Change

In [10]:
# pct_high_educ_change > pct_high_educ_change_median

# identify column that gives population on which education is based
pct_high_educ_pop_2021 = df["Total - Highest certificate, diploma or degree for the population aged 15 years and over in private households - 25% sample data 2021"]
pct_high_educ_pop_2016 = df["Total - Highest certificate, diploma or degree for the population aged 15 years and over in private households - 25% sample data 2016"]
pct_high_educ_pop_2011 = df["Total population aged 15 years and over by highest certificate, diploma or degree 2011"]
pct_high_educ_pop_2006 = df["Total population 15 to 24 years by highest certificate, diploma or degree - 20% sample data 2006"] \
                          + df["Total population 25 to 64 years by highest certificate, diploma or degree - 20% sample data 2006"] \
                          + df["Total population 65 years and over by highest certificate, diploma or degree - 20% sample data 2006"]
pct_high_educ_pop_2001 = df['0 to 19 years 2001'] + df['20 to 29 years 2001'] \
                          + df['30 to 39 years 2001'] \
                          + df['40 to 49 years 2001'] \
                          + df['50 to 59 years 2001'] \
                          + df['60+ years 2001']
pct_high_educ_pop_1996 = df["Total population 15 years and over by highest level of schooling 1996"]

# Calculate % education per year
pct_high_educ_2021 = df["Bachelor's degree or higher 2021"] / pct_high_educ_pop_2021 * 100
pct_high_educ_2016 = df["University certificate, diploma or degree at bachelor level or above 2016"] / pct_high_educ_pop_2016 * 100
pct_high_educ_2011 = df["University certificate, diploma or degree at bachelor level or above 2011"] / pct_high_educ_pop_2011 * 100
pct_high_educ_2006 = df["University certificate or degree 2006"] / pct_high_educ_pop_2006 * 100
pct_high_educ_2001 = df["With bachelor's degree or higher 2001"] / pct_high_educ_pop_2001 * 100
pct_high_educ_1996 = df["With bachelor's degree or higher 1996"] / pct_high_educ_pop_1996 * 100

# Calculate the change in percentage of high education for each year compared to its previous year
pct_high_educ_change_2021 = pct_high_educ_2021 - pct_high_educ_2016
pct_high_educ_change_2016 = pct_high_educ_2016 - pct_high_educ_2011
pct_high_educ_change_2011 = pct_high_educ_2011 - pct_high_educ_2006
pct_high_educ_change_2006 = pct_high_educ_2006 - pct_high_educ_2001
pct_high_educ_change_2001 = pct_high_educ_2001 - pct_high_educ_1996

# Calculate weighted mean of changes for each year
pct_high_educ_change_median_2021 = weighted_median(pct_high_educ_change_2021, pct_high_educ_pop_2021)
pct_high_educ_change_median_2016 = weighted_median(pct_high_educ_change_2016, pct_high_educ_pop_2016)
pct_high_educ_change_median_2011 = weighted_median(pct_high_educ_change_2011, pct_high_educ_pop_2011)
pct_high_educ_change_median_2006 = weighted_median(pct_high_educ_change_2006, pct_high_educ_pop_2006)
pct_high_educ_change_median_2001 = weighted_median(pct_high_educ_change_2001, pct_high_educ_pop_2001)

Calculate Gentrified

In [ ]:
'''
 gentrifiable.at.previous.census = gentrifiable_prev,
           gentrified = gentrifiable_prev &
             (housing_price_change > housing_price_change_median | avg_month_rent_change > avg_month_rent_change_median) &
             pct_high_educ_change > pct_high_educ_change_median)
'''

'\n gentrifiable.at.previous.census = gentrifiable_prev,\n           gentrified = gentrifiable_prev &\n             (housing_price_change > housing_price_change_median | avg_month_rent_change > avg_month_rent_change_median) &\n             pct_high_educ_change > pct_high_educ_change_median)\n'

In [11]:
df['Gentrified Ding 2021'] = df['Gentrifiable Ding 2016'] \
                              & ((housing_price_change_2021 > housing_price_change_median_2021) | (avg_rent_change_2021 > avg_rent_change_median_2021)) \
                              & (pct_high_educ_change_2021 > pct_high_educ_change_median_2021)

df['Gentrified Ding 2016'] = df['Gentrifiable Ding 2016'] \
                              & ((housing_price_change_2016 > housing_price_change_median_2016) | (avg_rent_change_2016 > avg_rent_change_median_2016)) \
                              & (pct_high_educ_change_2016 > pct_high_educ_change_median_2016)

df['Gentrified Ding 2011'] = df['Gentrifiable Ding 2011'] \
                              & ((housing_price_change_2011 > housing_price_change_median_2011) | (avg_rent_change_2011 > avg_rent_change_median_2011)) \
                              & (pct_high_educ_change_2011 > pct_high_educ_change_median_2011)

df['Gentrified Ding 2006'] = df['Gentrifiable Ding 2006'] \
                              & ((housing_price_change_2006 > housing_price_change_median_2006) | (avg_rent_change_2006 > avg_rent_change_median_2006)) \
                              & (pct_high_educ_change_2006 > pct_high_educ_change_median_2006)

df['Gentrified Ding 2001'] = df['Gentrifiable Ding 2001'] \
                              & ((housing_price_change_2001 > housing_price_change_median_2001) | (avg_rent_change_2001 > avg_rent_change_median_2001)) \
                              & (pct_high_educ_change_2001 > pct_high_educ_change_median_2001)

if True in df['Gentrified Ding 2001'].values:
    print("At least one value in the column is True.")
else:
    print("No value in the column is True.")

df.head()

At least one value in the column is True.

,ctuid,All others 2001,"Apartment, building that has fewer than five storeys 2001","Apartment, building that has five or more storeys 2001","Apartment, detached duplex 2001",Average gross rent $ 2001,Average household income $ 2001,Average income $ 2001,Average number of persons in private households 2001,Average value of dwelling $ 2001,...,Gentrifiable Ding 2016,Gentrifiable Ding 2011,Gentrifiable Ding 2006,Gentrifiable Ding 2001,Gentrifiable Ding 1996,Gentrified Ding 2021,Gentrified Ding 2016,Gentrified Ding 2011,Gentrified Ding 2006,Gentrified Ding 2001
0,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,True,True,True,True,True,False,False,False,False,False
1,4620001.0,2395.0,1025.0,0.0,30.0,554.0,42237.0,24971.0,2.0,107148.0,...,True,True,True,True,True,True,True,False,True,True
2,4620002.0,2595.0,690.0,70.0,220.0,528.0,36451.0,21095.0,2.0,107098.0,...,True,True,True,True,True,False,False,False,True,True
3,4620002.0,2595.0,690.0,70.0,220.0,528.0,36451.0,21095.0,2.0,107098.0,...,True,True,True,True,True,False,False,False,True,True
4,4620003.0,6065.0,2250.0,0.0,115.0,541.0,43453.0,23997.0,2.0,139439.0,...,True,True,True,True,True,False,False,False,False,False

In [12]:
# output file name
output_file_name = '/content/drive/MyDrive/GentrificAItion/Montreal_data_from_census/Standardized_Census_Data/census_data_ding.csv'

# write to file
df.to_csv(output_file_name)
df.head()

,ctuid,All others 2001,"Apartment, building that has fewer than five storeys 2001","Apartment, building that has five or more storeys 2001","Apartment, detached duplex 2001",Average gross rent $ 2001,Average household income $ 2001,Average income $ 2001,Average number of persons in private households 2001,Average value of dwelling $ 2001,...,Gentrifiable Ding 2016,Gentrifiable Ding 2011,Gentrifiable Ding 2006,Gentrifiable Ding 2001,Gentrifiable Ding 1996,Gentrified Ding 2021,Gentrified Ding 2016,Gentrified Ding 2011,Gentrified Ding 2006,Gentrified Ding 2001
0,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,True,True,True,True,True,False,False,False,False,False
1,4620001.0,2395.0,1025.0,0.0,30.0,554.0,42237.0,24971.0,2.0,107148.0,...,True,True,True,True,True,True,True,False,True,True
2,4620002.0,2595.0,690.0,70.0,220.0,528.0,36451.0,21095.0,2.0,107098.0,...,True,True,True,True,True,False,False,False,True,True
3,4620002.0,2595.0,690.0,70.0,220.0,528.0,36451.0,21095.0,2.0,107098.0,...,True,True,True,True,True,False,False,False,True,True
4,4620003.0,6065.0,2250.0,0.0,115.0,541.0,43453.0,23997.0,2.0,139439.0,...,True,True,True,True,True,False,False,False,False,False

Graded Gentrification Levels

In [ ]:
# Graded gentrification levels:
#  - Continued gentrification: not implemented (would require to load census data from 1996, or even from 1986)
#  - Weak gentrification: both median rent prices and home values in the bottom quartile of gentrifying CTs
#  - Intense gentrification: either median rent prices or median home values in the top quartile of gentrifying CTs
#  - Moderate gentrification: remaining CTs not categorized as weak or intense gentrification

In [13]:
# "weak": housing_price_change < housing_price_change_bottomQuartile & avg_month_rent_change < avg_month_rent_change_bottomQuartile
# "intense": housing_price_change > housing_price_change_topQuartile | avg_month_rent_change > avg_month_rent_change_topQuartile
# "moderate": not weak & not intense & gentrified

# calculate quartiles for housing
housing_price_change_bottomQuartile_2021, housing_price_change_topQuartile_2021 = weighted_quantile(
    housing_price_change_2021, housing_price_pop_2021, [0.25, 0.75])
housing_price_change_bottomQuartile_2016, housing_price_change_topQuartile_2016 = weighted_quantile(
    housing_price_change_2016, housing_price_pop_2016, [0.25, 0.75])
housing_price_change_bottomQuartile_2011, housing_price_change_topQuartile_2011 = weighted_quantile(
    housing_price_change_2011, housing_price_pop_2011, [0.25, 0.75])
housing_price_change_bottomQuartile_2006, housing_price_change_topQuartile_2006 = weighted_quantile(
    housing_price_change_2006, housing_price_pop_2006, [0.25, 0.75])
housing_price_change_bottomQuartile_2001, housing_price_change_topQuartile_2001 = weighted_quantile(
    housing_price_change_2001, housing_price_pop_2001, [0.25, 0.75])

# calculate quartiles for avg_month
avg_month_rent_change_bottomQuartile_2021, avg_month_rent_change_topQuartile_2021 = weighted_quantile(
        avg_rent_change_2021, avg_rent_pop_2021, [0.25, 0.75])
avg_month_rent_change_bottomQuartile_2016, avg_month_rent_change_topQuartile_2016 = weighted_quantile(
        avg_rent_change_2016, avg_rent_pop_2016, [0.25, 0.75])
avg_month_rent_change_bottomQuartile_2011, avg_month_rent_change_topQuartile_2011 = weighted_quantile(
        avg_rent_change_2011, avg_rent_pop_2011, [0.25, 0.75])
avg_month_rent_change_bottomQuartile_2006, avg_month_rent_change_topQuartile_2006 = weighted_quantile(
        avg_rent_change_2006, avg_rent_pop_2006, [0.25, 0.75])
avg_month_rent_change_bottomQuartile_2001, avg_month_rent_change_topQuartile_2001 = weighted_quantile(
        avg_rent_change_2001, avg_rent_pop_2001, [0.25, 0.75])

# add weak columns
# Define weak, intense, and moderate gentrification conditions
df['Weak Gentrified Ding 2021'] = df['Gentrified Ding 2021'] \
                              & (housing_price_change_2021 < housing_price_change_bottomQuartile_2021) \
                              & (avg_rent_change_2021 < avg_month_rent_change_bottomQuartile_2021)

df['Weak Gentrified Ding 2016'] = (df['Gentrified Ding 2016']==True) \
                              & (housing_price_change_2016 < housing_price_change_bottomQuartile_2016) \
                              & (avg_rent_change_2016 < avg_month_rent_change_bottomQuartile_2016)

df['Weak Gentrified Ding 2011'] = df['Gentrified Ding 2011'] \
                              & (housing_price_change_2011 < housing_price_change_bottomQuartile_2011) \
                              & (avg_rent_change_2011 < avg_month_rent_change_bottomQuartile_2011)

df['Weak Gentrified Ding 2006'] = df['Gentrified Ding 2006'] \
                              & (housing_price_change_2006 < housing_price_change_bottomQuartile_2006) \
                              & (avg_rent_change_2006 < avg_month_rent_change_bottomQuartile_2006)

df['Weak Gentrified Ding 2001'] = df['Gentrified Ding 2001'] \
                              & (housing_price_change_2001 < housing_price_change_bottomQuartile_2001) \
                              & (avg_rent_change_2001 < avg_month_rent_change_bottomQuartile_2001)

# add high columns
df['Intense Gentrified Ding 2021'] = df['Gentrified Ding 2021'] \
                              & ((housing_price_change_2021 > housing_price_change_topQuartile_2021) \
                              | (avg_rent_change_2021 > avg_month_rent_change_topQuartile_2021))

df['Intense Gentrified Ding 2016'] = (df['Gentrified Ding 2016']==True) \
                              & ((housing_price_change_2016 > housing_price_change_topQuartile_2016) \
                              | (avg_rent_change_2016 > avg_month_rent_change_topQuartile_2016))

df['Intense Gentrified Ding 2011'] = df['Gentrified Ding 2011'] \
                              & ((housing_price_change_2011 > housing_price_change_topQuartile_2011) \
                              | (avg_rent_change_2011 > avg_month_rent_change_topQuartile_2011))

df['Intense Gentrified Ding 2006'] = df['Gentrified Ding 2006'] \
                              & ((housing_price_change_2006 > housing_price_change_topQuartile_2006) \
                              | (avg_rent_change_2006 > avg_month_rent_change_topQuartile_2006))

df['Intense Gentrified Ding 2001'] = df['Gentrified Ding 2001'] \
                                  & ((housing_price_change_2001 > housing_price_change_topQuartile_2001) \
                                  | (avg_rent_change_2001 > avg_month_rent_change_topQuartile_2001))

# add moderate columns
df['Moderate Gentrified Ding 2021'] = df['Gentrified Ding 2021'] & ~df['Weak Gentrified Ding 2021'] & ~df['Intense Gentrified Ding 2021']
df['Moderate Gentrified Ding 2016'] = df['Gentrified Ding 2016'] & ~df['Weak Gentrified Ding 2016'] & ~df['Intense Gentrified Ding 2016']
df['Moderate Gentrified Ding 2011'] = df['Gentrified Ding 2011'] & ~df['Weak Gentrified Ding 2011'] & ~df['Intense Gentrified Ding 2011']
df['Moderate Gentrified Ding 2006'] = df['Gentrified Ding 2006'] & ~df['Weak Gentrified Ding 2006'] & ~df['Intense Gentrified Ding 2006']
df['Moderate Gentrified Ding 2001'] = df['Gentrified Ding 2001'] & ~df['Weak Gentrified Ding 2001'] & ~df['Intense Gentrified Ding 2001']

In [14]:
df.head()

true_count_gentrified = (df['Gentrified Ding 2021'] == True).sum()
true_count_high = (df['Intense Gentrified Ding 2021'] == True).sum()
true_count_weak = (df['Weak Gentrified Ding 2021'] == True).sum()
true_count_moderate = (df['Moderate Gentrified Ding 2021'] == True).sum()

print(true_count_gentrified)
print(true_count_high)
print(true_count_weak)
print(true_count_moderate)

256
174
0
82

In [15]:
# Function to determine the Gentrification Level
# 0 for not gentrified, 1 for weak, 2 for moderate, 3 for intense
def get_gentrification_level(row, year):
    if row[f'Intense Gentrified Ding {year}']:
        return 3
    elif row[f'Moderate Gentrified Ding {year}']:
        return 2
    elif row[f'Weak Gentrified Ding {year}']:
        return 1
    else:
        return 0  # Not gentrified

# List of years
years = [2021, 2016, 2011, 2006, 2001]

# Apply the function for each year to create new column
for year in years:
    df[f'Gentrification Level Ding {year}'] = df.apply(get_gentrification_level, axis=1, year=year)

# List of columns to drop
columns_to_drop = []
for year in years:
    columns_to_drop.extend([
        f'Weak Gentrified Ding {year}',
        f'Intense Gentrified Ding {year}',
        f'Moderate Gentrified Ding {year}'
    ])

# Drop the columns
df.drop(columns=columns_to_drop, inplace=True)


df.head()

,ctuid,All others 2001,"Apartment, building that has fewer than five storeys 2001","Apartment, building that has five or more storeys 2001","Apartment, detached duplex 2001",Average gross rent $ 2001,Average household income $ 2001,Average income $ 2001,Average number of persons in private households 2001,Average value of dwelling $ 2001,...,Gentrified Ding 2021,Gentrified Ding 2016,Gentrified Ding 2011,Gentrified Ding 2006,Gentrified Ding 2001,Gentrification Level Ding 2021,Gentrification Level Ding 2016,Gentrification Level Ding 2011,Gentrification Level Ding 2006,Gentrification Level Ding 2001
0,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,False,False,False,False,False,0,0,0,0,0
1,4620001.0,2395.0,1025.0,0.0,30.0,554.0,42237.0,24971.0,2.0,107148.0,...,True,True,False,True,True,2,3,0,3,2
2,4620002.0,2595.0,690.0,70.0,220.0,528.0,36451.0,21095.0,2.0,107098.0,...,False,False,False,True,True,0,0,0,3,2
3,4620002.0,2595.0,690.0,70.0,220.0,528.0,36451.0,21095.0,2.0,107098.0,...,False,False,False,True,True,0,0,0,3,2
4,4620003.0,6065.0,2250.0,0.0,115.0,541.0,43453.0,23997.0,2.0,139439.0,...,False,False,False,False,False,0,0,0,0,0

More data cleaning

In [16]:
# add population percentage change from 2001 to 2006
df['Population percentage change, 2001-2006 2006'] = ((df['Population  2006'] - df['Population, 2001 2001']) / df['Population, 2001 2001']) * 100

In [17]:
# bucket years
# Define the column mappings for each year
year_groups = {
    2011: {
        '0 to 19 years 2011': ['0 to 4 years 2011', '5 to 9 years 2011', '10 to 14 years 2011', '15 to 19 years 2011'],
        '20 to 29 years 2011': ['20 to 24 years 2011', '25 to 29 years 2011'],
        '30 to 39 years 2011': ['30 to 34 years 2011', '35 to 39 years 2011'],
        '40 to 49 years 2011': ['40 to 44 years 2011', '45 to 49 years 2011'],
        '50 to 59 years 2011': ['50 to 54 years 2011', '55 to 59 years 2011'],
        '60+ years 2011': ['60 to 64 years 2011', '65 to 69 years 2011', '70 to 74 years 2011', '75 to 79 years 2011', '80 to 84 years 2011', '85 years and over 2011']
    },
    2016: {
        '0 to 19 years 2016': ['0 to 14 years 2016', '15 to 19 years 2016'],
        '20 to 29 years 2016': ['20 to 24 years 2016', '25 to 29 years 2016'],
        '30 to 39 years 2016': ['30 to 34 years 2016', '35 to 39 years 2016'],
        '40 to 49 years 2016': ['40 to 44 years 2016', '45 to 49 years 2016'],
        '50 to 59 years 2016': ['50 to 54 years 2016', '55 to 59 years 2016'],
        '60+ years 2016': ['60 to 64 years 2016', '65 years and over 2016']
    },
    2021: {
        '0 to 19 years 2021': ['0 to 14 years 2021', '15 to 19 years 2021'],
        '20 to 29 years 2021': ['20 to 24 years 2021', '25 to 29 years 2021'],
        '30 to 39 years 2021': ['30 to 34 years 2021', '35 to 39 years 2021'],
        '40 to 49 years 2021': ['40 to 44 years 2021', '45 to 49 years 2021'],
        '50 to 59 years 2021': ['50 to 54 years 2021', '55 to 59 years 2021'],
        '60+ years 2021': ['60 to 64 years 2021', '65 years and over 2021']
    }
}

# Function to create new bucketed columns
def create_buckets(df, year_groups):
    for year, groups in year_groups.items():
        for new_col, old_cols in groups.items():
            df[new_col] = df[old_cols].sum(axis=1)
    return df

# Create new bucketed columns
df = create_buckets(df, year_groups)

In [18]:
# List of columns to rename
columns_to_rename = [
    'Age 0 to 9 2006',
    'Age 10 to 19 2006',
    'Age 20 to 29 2006',
    'Age 30 to 39 2006',
    'Age 40 to 49 2006',
    'Age 50 to 59 2006',
    'Age 60+ 2006'
]

# Rename columns by removing 'Age'
new_column_names = {col: col.replace('Age ', '') for col in columns_to_rename}
df.rename(columns=new_column_names, inplace=True)

In [19]:
# drop 1996 columns
df = df.loc[:, ~df.columns.str.endswith(' 1996')]

In [20]:
# output file name
output_file_name = '/content/drive/MyDrive/GentrificAItion/Montreal_data_from_census/Standardized_Census_Data/census_data_ding.csv'

# write to file
df.to_csv(output_file_name)
df.head()

,ctuid,All others 2001,"Apartment, building that has fewer than five storeys 2001","Apartment, building that has five or more storeys 2001","Apartment, detached duplex 2001",Average gross rent $ 2001,Average household income $ 2001,Average income $ 2001,Average number of persons in private households 2001,Average value of dwelling $ 2001,...,30 to 39 years 2016,40 to 49 years 2016,50 to 59 years 2016,60+ years 2016,0 to 19 years 2021,20 to 29 years 2021,30 to 39 years 2021,40 to 49 years 2021,50 to 59 years 2021,60+ years 2021
0,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,4620001.0,2395.0,1025.0,0.0,30.0,554.0,42237.0,24971.0,2.0,107148.0,...,380.0,365.0,485.0,235.0,98.6,380.0,450.0,330.0,405.0,250.0
2,4620002.0,2595.0,690.0,70.0,220.0,528.0,36451.0,21095.0,2.0,107098.0,...,530.0,470.0,535.0,330.0,171.5,470.0,600.0,510.0,525.0,325.0
3,4620002.0,2595.0,690.0,70.0,220.0,528.0,36451.0,21095.0,2.0,107098.0,...,530.0,470.0,535.0,330.0,0.0,0.0,0.0,0.0,0.0,0.0
4,4620003.0,6065.0,2250.0,0.0,115.0,541.0,43453.0,23997.0,2.0,139439.0,...,920.0,800.0,1030.0,600.0,321.7,810.0,985.0,885.0,875.0,515.0